from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional, Union

from morphalo.core.paths import make_node_output_path
from morphalo.dag import NodeRef
from morphalo.nodes.common.io import write_json_sidecar


@dataclass
class FileVideo(NodeRef):
    """
    Source node that exposes an existing video from the filesystem.

    This node does not perform any computation. It simply validates that the
    referenced file exists and returns a JSON-serializable output dictionary
    containing the video path.

    The node is typically used as a source in a DAG to provide an initial video
    for downstream nodes such as Txt2Video.

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    path : str or Path
        Filesystem path to the video to be used as a DAG input.

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class
        name (e.g. ``"video_image"``).

    Notes
    -----
    - The JSON sidecar produced by this node is used as a persistent cache.
      If the node implementation, its configuration, or specification changes,
      any previously generated sidecar files must be removed manually in order
      to avoid reusing stale cached outputs.
    """

    path: Union[str, Path]

    def run(self, output_dir, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        p = Path(str(self.path)).expanduser()
        p = p.resolve()

        if not p.exists():
            raise FileNotFoundError(
                f"FileImage node '{self.id}': file not found: {p}")
        if not p.is_file():
            raise FileNotFoundError(
                f"FileImage node '{self.id}': not a file: {p}")

        out = {
            'ok': True,
            'node': 'file_video',
            'id': self.id,
            'video': str(p),
        }

        out_path = make_node_output_path(
            out_dir=Path(output_dir),
            node_id=self.id,
            ext='json',
        )

        meta_path = write_json_sidecar(out_path, out)
        out['metadata'] = str(meta_path)

        return out
