import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

from morphalo.cache.ltx_models import (get_ltx_condition,
                                       get_ltx_latent_upsample)
from morphalo.dag import NodeRef
from morphalo.nodes.common.config_resolve import SpecInput
from morphalo.nodes.common.cuda_stat import (cuda_mem_stats, cuda_prerun,
                                             cuda_sync)
from morphalo.nodes.common.env import setup_env
from morphalo.nodes.ltx.conditioning import apply_ic_lora
from morphalo.nodes.ltx.io import finalize_video_output, save_video
from morphalo.nodes.ltx.ltx_resolve import resolve_ltx_common
from morphalo.nodes.ltx.mixins import IcLoRaMixin
from morphalo.nodes.ltx.video_utils import downscale_size, upscale_size
from morphalo.nodes.wiring.mixins import PromptMixin
from morphalo.nodes.wiring.prompt import PromptBundle


@dataclass
class Txt2Video(IcLoRaMixin, PromptMixin, NodeRef):
    """
    Text-to-video node based on LTX-Video.

    This node generates a short video clip from a text prompt using the
    LTX-Video diffusion model. Video content is produced through a
    multi-stage process that first generates a low-resolution latent
    video and then refines it into a final high-resolution sequence.

    Prompts are resolved from the node configuration and may optionally be
    overridden by an upstream prompt bundle attached through the prompt channel.

    Optionally, the generation can be conditioned using a single
    Image-Conditioned LoRA (IC-LoRA). When an IC-LoRA is attached, an
    upstream video (typically edge-based, depth, or similar structural
    guidance) is used to constrain the generated motion and geometry
    while preserving the model's generative freedom.

    The node produces a single primary output dictionary containing at least:
    - ``video``: filesystem path to the generated MP4 video
    - ``metadata``: filesystem path to a JSON sidecar with generation details

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    spec : dict or str or pathlib.Path or sequence of (dict or str or pathlib.Path)
        Node configuration specification.

        The specification may be provided as an in-memory dictionary, as a path
        to a HOCON configuration file, or as a sequence of such elements. When a
        sequence is given, each element is resolved independently and merged from
        left to right, with later elements overriding earlier ones.

        Typical keys include:

        - ``model``: model identifiers and runtime options
        - ``prompt``: text prompt describing the desired video
        - ``negative_prompt``: optional negative prompt
        - ``seed``: random seed (or ``"random"``)
        - ``params``:
            - ``width`` / ``height``: target output resolution
            - ``fps``: frames per second
            - ``num_frames``: total number of frames
            - ``steps_main``: diffusion steps for latent generation
            - ``steps_refine``: diffusion steps for refinement
            - ``denoise_strength``: refinement denoise strength
            - ``guidance_scale`` / ``guidance_rescale``: classifier-free guidance parameters
            - ``downscale_factor``: spatial downscaling factor for latent generation
            - ``decode_timestep`` / ``decode_noise_scale``: decode-time noise controls
            - ``image_cond_noise_scale``: noise applied to conditioning inputs

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class
        name (e.g. ``"txt2video"``).

    ic_lora : ICLoRaRegistry
        Registry used to attach a single Image-Conditioned LoRA (IC-LoRA)
        to this node. The registry exposes an AttachmentSink that allows
        an upstream video node to be wired as structural conditioning.
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by ``PromptMixin``.

    Inputs
    ------
    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Expected keys include ``prompt`` and ``negative_prompt``.

    Notes
    -----
    - This node does not consume any default DAG input.
    - When no IC-LoRA is attached, video motion and temporal structure
      are generated purely from the textual prompt.
    - When an IC-LoRA is attached, the conditioning video is used as a
      reference signal to guide motion and geometry, without directly
      copying pixel content.
    - Only one IC-LoRA attachment is supported by design.
    - The node executes in three conceptual stages:
        1. Latent video generation at reduced resolution
        2. Latent upsampling
        3. Short refinement pass to produce the final video
    """

    spec: SpecInput = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # HF env
        setup_env()

        ctx = resolve_ltx_common(self.spec)

        ic_lora_bundle = self.build_ic_lora_bundle(input)

        pipe = get_ltx_condition(
            model_id=ctx.model.model_id,
            device=ctx.model.device,
            dtype=ctx.model.dtype
        )
        pipe_upsample = get_ltx_latent_upsample(
            model_id=ctx.model.model_id,
            upscaler_id=ctx.model.upscaler_id,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        # --- sizes ---
        down_h, down_w = downscale_size(
            height=ctx.height,
            width=ctx.width,
            factor=ctx.downscale_factor,
            pipe=pipe)
        up_h, up_w = upscale_size(down_h, down_w, ctx.upscale_latent_factor)

        reference_video = apply_ic_lora(
            ic_lora_bundle,
            pipe=pipe,
            device=ctx.model.device
        )

        prompt_bundle = PromptBundle(
            spec=ctx.spec,
            input=input
        )

        cuda_prerun(ctx.model.device)
        t0 = time.perf_counter()

        # Part 1: generate at smaller res -> latent video
        latents = pipe(
            reference_video=reference_video,
            prompt=prompt_bundle.prompt,
            negative_prompt=prompt_bundle.negative_prompt,
            width=down_w,
            height=down_h,
            guidance_scale=ctx.guidance_scale,
            guidance_rescale=ctx.guidance_rescale,
            num_frames=ctx.num_frames,
            num_inference_steps=ctx.steps_main,
            decode_timestep=ctx.decode_timestep,
            decode_noise_scale=ctx.decode_noise_scale,
            image_cond_noise_scale=ctx.image_cond_noise_scale,
            generator=ctx.rng.gen,
            output_type="latent",
            max_sequence_length=ctx.max_sequence_length
        ).frames

        # Part 2: latent upsample
        up_latents = pipe_upsample(
            latents=latents,
            output_type='latent'
        ).frames

        # Part 3: short denoise refine
        video_out = pipe(
            prompt=prompt_bundle.prompt,
            negative_prompt=prompt_bundle.negative_prompt,
            width=up_w,
            height=up_h,
            guidance_scale=ctx.guidance_scale,
            guidance_rescale=ctx.guidance_rescale,
            num_frames=ctx.num_frames,
            denoise_strength=ctx.denoise_strength,
            num_inference_steps=ctx.steps_refine,
            latents=up_latents,
            decode_timestep=ctx.decode_timestep,
            decode_noise_scale=ctx.decode_noise_scale,
            image_cond_noise_scale=ctx.image_cond_noise_scale,
            generator=ctx.rng.gen,
            output_type="pil",
            max_sequence_length=ctx.max_sequence_length
        ).frames[0]

        cuda_sync(ctx.model.device)
        dt_s = time.perf_counter() - t0

        # Part 4: resize down to target
        video_out = [f.resize((ctx.width, ctx.height)) for f in video_out]

        video_path = save_video(
            out_dir=output_dir,
            node_id=self.id,
            seed=ctx.rng.seed,
            video_out=video_out,
            fps=ctx.fps,
        )

        mem = cuda_mem_stats(ctx.model.device)

        out = finalize_video_output(
            node_kind=str(self.op),
            node_id=self.id,
            video_path=video_path,
            seed=ctx.rng.seed,
            params={
                'guidance_scale': ctx.guidance_scale,
                'guidance_rescale': ctx.guidance_rescale,
                'width': ctx.width,
                'height': ctx.height,
                'fps': ctx.fps,
                'num_frames': ctx.num_frames,
                'steps_main': ctx.steps_main,
                'steps_refine': ctx.steps_refine,
                'denoise_strength': ctx.denoise_strength,
                'downscale_factor': ctx.downscale_factor,
                'decode_timestep': ctx.decode_timestep,
                'image_cond_noise_scale': ctx.image_cond_noise_scale,
                'max_sequence_length': ctx.max_sequence_length
            },
            dt_s=dt_s,
            cuda_mem=mem,
            ic_lora_specs=self.ic_lora.spec,
            model_info={
                'id': ctx.model.model_id,
                'upscaler': ctx.model.upscaler_id,
                'device': ctx.model.device,
                'dtype': str(ctx.model.dtype).replace('torch.', ''),
            }
        )

        return out
