from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from stability.dag import NodeRef


@dataclass
class FileImage(NodeRef):
    """
    Source node that exposes one or more existing image files from the filesystem.

    ``FileImage`` is a pure *source node*: it performs no computation and has no
    dependencies on upstream nodes. Its only responsibility is to validate that
    the referenced image files exist and to expose their absolute paths as a
    JSON-serializable output.

    This node is typically used at the edges of a DAG to provide external images
    to downstream nodes such as Img2Img pipelines, ControlNet-conditioned nodes,
    or IP-Adapter inputs (including reference images and masks).

    A single instance may expose either:
    - one image, or
    - an ordered list of images.

    When multiple images are provided, the order is preserved and can be relied
    upon by downstream nodes (for example, when associating images with
    per-index inputs such as IP-Adapter masks).

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.

    path : str or Path or Sequence[str or Path]
        Filesystem path or paths to the image file(s) to be exposed by this node.
        Paths may be relative or absolute and may include user home expansion
        (``~``).

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class name
        (for example ``'file_image'``).
    """

    path: Union[str, Path, List[Union[str, Path]]]

    def run(self, output_dir, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        """
        Returns the image path as node output.

        Parameters
        ----------
        output_dir : str or Path-like
            Unused (kept for interface compatibility).
        input : dict, optional
            Unused. Source nodes are executed with empty inputs.

        Returns
        -------
        dict
            Output dictionary containing:
            - 'ok': True
            - 'node': 'file_image'
            - 'id': node id
            - 'image': absolute path or list of paths to the image files
        """
        if not isinstance(self.path, list):
            paths = [self.path]
        else:
            paths = self.path

        paths = [Path(str(p)).expanduser().resolve() for p in paths]

        for p in paths:
            if not p.exists():
                raise FileNotFoundError(
                    f"FileImage node '{self.id}': file not found: {p}")
            if not p.is_file():
                raise FileNotFoundError(
                    f"FileImage node '{self.id}': not a file: {p}")

        return {
            'ok': True,
            'node': self.op,
            'id': self.id,
            'image': [str(p) for p in paths] if len(paths) > 1 else str(paths[0])
        }
