import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

from diffusers import (StableDiffusionXLControlNetImg2ImgPipeline,
                       StableDiffusionXLImg2ImgPipeline)
from PIL import Image

from stability.cache.models import get_sdxl_base_pipe
from stability.core.config import *
from stability.dag import NodeRef
from stability.nodes.sdxl_common import *
from stability.nodes.utils import *
from stability.nodes.wiring.prompt import PromptBundle


@dataclass
class Img2Img(ControlNetMixin, PromptMixin, NodeRef):
    """
    SDXL image-to-image generation node with optional ControlNet and IP-Adapter.

    This node performs an image-to-image transformation using Stable Diffusion XL.
    The initial image is provided by the upstream node connected to the default
    input channel (``input_id="default"``). Text prompts are resolved from the
    node configuration and may optionally be overridden by an upstream prompt
    bundle connected through the prompt channel (see Notes).

    If one or more ControlNet specifications are configured on this node, the
    underlying pipeline switches to ``StableDiffusionXLControlNetImg2ImgPipeline``
    and uses the attached ControlNet conditioning images. Otherwise, it uses
    the standard ``StableDiffusionXLImg2ImgPipeline``. IP-Adapter conditioning is
    enabled/disabled based on the resolved IP-Adapter bundle.

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : dict or str or pathlib.Path, optional
        Node configuration describing model selection, prompts, and generation
        parameters. The value may be a mapping (already-parsed spec) or a path
        reference (string/path) that is resolved by ``resolve_common``.

        Common keys include:

        - ``model`` (e.g. device, dtype, model path/id)
        - ``prompt`` and ``negative_prompt`` (simple or structured form)
        - ``params`` (e.g. ``steps``, ``guidance_scale``, ``strength``, ``width``, ``height``)
        - ``seed``
        - optional ``vae``

    Attributes
    ----------
    op : str
        Operator identifier derived from the concrete node class name (e.g. ``"img2img"``).
    controlnet : ControlNetRegistry
        Registry used to declare ControlNet conditioning inputs (via sinks), provided
        by ``ControlNetMixin``.
    ip_adapter : IpAdapterRegistry
        Registry used to declare IP-Adapter reference inputs (via sinks), provided
        by ``ControlNetMixin``.
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by ``PromptMixin``.

    Inputs
    ------
    default : dict
        Required. Upstream output dictionary containing the init image path. The node
        expects either ``"image"`` or ``"path"`` to point to the image file.

    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Expected keys include ``prompt``, ``prompt_2``, ``negative_prompt``,
        and ``negative_prompt_2``.

    Additional typed inputs may be attached via ControlNet/IP-Adapter sinks declared
    on this node (see Notes).

    Outputs
    -------
    dict
        Primary output dictionary with at least:

        - ``ok`` : bool
        - ``node`` : str (``"i2i"``)
        - ``id`` : str (node id)
        - ``image`` : str (path to the generated image)
        - ``metadata`` : str (path to a JSON sidecar with generation details)

        The metadata sidecar includes resolved parameters, timing information, and
        (when running on CUDA) memory statistics.

    Notes
    -----
    - The init image is loaded from the upstream path, converted to RGB, and resized
      to ``(width, height)`` prior to generation.
    - Prompt resolution is performed by ``PromptBundle``:
      if a prompt bundle is wired into ``prompt:default``, it takes precedence over
      the local ``spec``; otherwise the local ``spec`` is used.
    - ControlNet and IP-Adapter inputs are collected from DAG wiring through their
      respective registries and bundled via ``build_control_bundles``.
    - When ControlNet is enabled, the pipeline call uses ``image=init_image`` and
      ``control_image=<conditioning>``.
    """

    spec: Union[Dict[str, Any], str, Path] = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # HF env
        setup_env()

        spec, device, dtype, model_path, steps, cfg, \
            strength, width, height, seed, gen = resolve_common(self.spec)

        input = input or {}

        # 1) init image comes from default input_id
        init_up = input.get('default')
        if init_up is None:
            raise ValueError(
                'Img2Img requires an init image wired into the default input (src >> img2img).')

        init_path = init_up.get('image') or init_up.get('path')
        if not init_path:
            raise ValueError(
                "Init image upstream output must contain 'image' (path).")

        init_image = Image.open(init_path).convert(
            'RGB'
        ).resize((width, height))

        vae_id = spec.get('vae', {}).get('id') if isinstance(
            spec.get('vae'),
            dict
        ) else spec.get('vae')

        # --- resolve inputs from DAG wiring ---
        cn_bundle, ip_bundle, face_bundle = self.build_control_bundles(
            input=input,
            device=device,
            dtype=dtype
        )

        base = get_sdxl_base_pipe(
            model_path=model_path,
            device=device,
            dtype=dtype,
            vae_id=vae_id
        )

        if ip_bundle.has_ip_adapter and face_bundle.has_face_id:
            raise ValueError(
                'IP_Adapter and IP-Adapter-FaceID are mutually exclusive (chose one).'
            )

        # pipeline load (two-path: direct or via base components)
        if cn_bundle.has_controlnet:
            pipe = StableDiffusionXLControlNetImg2ImgPipeline(
                **base.components,
                controlnet=cn_bundle.controlnet_arg
            )
        else:
            pipe = StableDiffusionXLImg2ImgPipeline(
                **base.components
            )

        prompt_bundle = PromptBundle(
            spec=spec,
            input=input
        )

        cuda_prerun(device)
        t0 = time.perf_counter()

        apply_ip_adapter(ip_bundle, face_bundle, pipe, device, dtype)

        pipe_kwargs = build_pipe_kwargs(
            cn_bundle=cn_bundle,
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            height=height,
            width=width,
            device=device,
            dtype=dtype,
        )

        if 'cross_attention_kwargs' in pipe_kwargs:
            l = len(ip_bundle.weight_names_arg) + \
                len(face_bundle.weight_names_arg)
            masks = pipe_kwargs['cross_attention_kwargs']['ip_adapter_masks']
            assert len(masks) == l

        # IMPORTANT: Img2Img + ControlNet uses image=init and control_image=control :contentReference[oaicite:3]{index=3}
        result = pipe(
            prompt=prompt_bundle.prompt,
            prompt_2=prompt_bundle.prompt_2,
            negative_prompt=prompt_bundle.negative_prompt,
            negative_prompt_2=prompt_bundle.negative_prompt_2,
            image=init_image,
            strength=strength,
            num_inference_steps=steps,
            guidance_scale=cfg,
            generator=gen,
            width=width,
            height=height,
            **pipe_kwargs
        )

        cuda_sync(device)
        dt_s = time.perf_counter() - t0

        img = result.images[0]

        out_dir = ensure_out_dir(output_dir)
        img_path = save_image(out_dir, node_id=self.id, seed=seed, img=img)

        mem = cuda_mem_stats(device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_path,
            seed=seed,
            params={
                'steps': steps,
                'guidance_scale': cfg,
                'strength': strength,
                'width': width,
                'height': height,
            },
            dt_s=dt_s,
            cuda_mem=mem,
            controlnet_specs=self.controlnet.specs,
            ip_adapter_specs=self.ip_adapter.specs,
            face_id_specs=self.face_id.specs,
            model_info={
                'path': model_path,
                **({'vae_id': vae_id} if vae_id is not None else {}),
                'dtype': str(dtype).replace('torch.', ''),
                'device': device,
            }
        )

        return out
