import json
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

import torch
from diffusers import (StableDiffusionXLControlNetImg2ImgPipeline,
                       StableDiffusionXLImg2ImgPipeline)
from PIL import Image

from stability.cache.models import get_sdxl_base_pipe
from stability.core.config import *
from stability.dag import NodeRef
from stability.nodes import *


@dataclass
class Img2Img(NodeRef):
    """
    Image-to-image node with optional ControlNet conditioning.

    This node transforms an input image into a new image guided by a text
    prompt. The initial image is provided via the default DAG connection
    (``src >> img2img``), while one or more ControlNet inputs may be attached
    to further constrain the generation (e.g. depth, canny, lineart).

    ControlNet inputs are declared by calling ``createControlNet()`` or its
    alias ``addControlNet()``. Both names are equivalent and return an
    ``AttachmentSink`` that can be wired using the ``>>`` operator.

        The node produces a single primary output dictionary containing at least:
    - ``image``: filesystem path to the generated image
    - ``metadata``: filesystem path to a JSON sidecar with generation details

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    spec : dict
        Configuration dictionary describing the model, prompts, and
        image-to-image parameters. Typical keys include ``model``, ``prompt``,
        ``negative_prompt``, ``params`` (e.g. ``steps``, ``strength``,
        ``guidance_scale``), ``seed``, and optional ``vae``.

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class
        name (e.g. ``"img2img"``).

    Notes
    -----
    - The default input edge provides the *init image* for the image-to-image
      process.
    - ControlNet inputs are attached via dedicated sinks and are passed to
      the underlying SDXL ControlNet image-to-image pipeline as conditioning
      images.
    - If no ControlNet is configured, this node behaves as a standard
      image-to-image transformation.
    """

    spec: Union[Dict[str, Any], str, Path] = field(default_factory=dict)
    controlnet: ControlNetRegistry = field(init=False, repr=False)

    def __post_init__(self) -> None:
        super().__post_init__()  # registra il nodo nel DAG, assegna id/op
        self.controlnet = ControlNetRegistry(owner=self)

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # HF env
        os.environ['HF_HOME'] = HF_HOME
        os.environ['HF_HUB_CACHE'] = HF_HUB_CACHE
        os.environ['HF_HUB_DISABLE_TELEMETRY'] = HF_HUB_DISABLE_TELEMETRY

        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        spec = resolve_spec(self.spec)

        # model settings
        model = spec.get('model', {})
        device = model.get('device', 'cuda')
        dtype = resolve_dtype(model.get('dtype', 'bf16'))

        model_path = model.get('path')
        if not model_path:
            raise ValueError('spec.model.path is required')

        # prompts
        prompt = norm_prompt(spec.get('prompt'))
        negative = norm_prompt(spec.get('negative_prompt'), joiner=', ')

        # params
        params = spec.get('params', {})
        steps = int(params.get('steps', 30))
        cfg = float(params.get('cfg', params.get('guidance_scale', 6.0)))
        strength = float(params.get('strength', 0.7))
        width = int(params.get('width', 1024))
        height = int(params.get('height', 1024))

        # seed
        seed = resolve_seed(spec.get('seed', 'random'))
        gen = torch.Generator(device=device).manual_seed(seed)

        # inputs from DAG
        input = input or {}

        # 1) init image comes from default input_id
        init_up = input.get('default')
        if init_up is None:
            raise ValueError(
                'Img2Img requires an init image wired into the default input (src >> img2img).')

        init_path = init_up.get('image') or init_up.get('path')
        if not init_path:
            raise ValueError(
                "Init image upstream output must contain 'image' (path).")

        init_image = Image.open(init_path).convert(
            'RGB'
        ).resize((width, height))

        vae_id = spec.get('vae', {}).get('id') if isinstance(
            spec.get('vae'),
            dict
        ) else spec.get('vae')

        # --- resolve ControlNet inputs from DAG wiring ---
        cn_bundle = ControlNetBundle(
            self.controlnet.specs,
            dtype=dtype,
            device=device,
            input=input
        )

        base = get_sdxl_base_pipe(
            model_path=model_path,
            device=device,
            dtype=dtype,
            vae_id=vae_id
        )
        # pipeline load (two-path: direct or via base components)
        if cn_bundle.has_controlnet:
            pipe = StableDiffusionXLControlNetImg2ImgPipeline(
                **base.components,
                controlnet=cn_bundle.controlnet_arg
            )
        else:
            pipe = StableDiffusionXLImg2ImgPipeline(
                **base.components
            )

        # run
        if device.startswith('cuda'):
            torch.cuda.reset_peak_memory_stats()
            torch.cuda.synchronize()

        t0 = time.perf_counter()

        # IMPORTANT: Img2Img + ControlNet uses image=init and control_image=control :contentReference[oaicite:3]{index=3}
        result = pipe(
            prompt=prompt,
            negative_prompt=negative,
            image=init_image,
            strength=strength,
            num_inference_steps=steps,
            guidance_scale=cfg,
            generator=gen,
            width=width,
            height=height,
            **({
                'control_image': cn_bundle.control_image_arg,
                'controlnet_conditioning_scale': cn_bundle.conditioning_scale_arg,
            } if cn_bundle.has_controlnet else {})
        )

        if device.startswith('cuda'):
            torch.cuda.synchronize()

        dt_s = time.perf_counter() - t0
        img = result.images[0]

        # --- save image ---
        img_path = make_node_output_path(
            out_dir=out_dir,
            node_id=self.id,
            seed=seed
        )
        img.save(img_path)

        out = {
            'ok': True,
            'node': 'i2i',
            'id': self.id,
            'image': str(img_path),
            'seed': seed,
            'params': {
                'steps': steps,
                'guidance_scale': cfg,
                'strength': strength,
                'width': width,
                'height': height,
            },
            'controlnet': [
                {
                    'key': cn.key,
                    'model_id': cn.model_id,
                    'conditioning_scale': cn.conditioning_scale,
                    'input_id': f'controlnet:{cn.key}',
                }
                for cn in self.controlnet.specs
            ],
            'timing': {'seconds': round(dt_s, 3)},
        }

        meta_path = img_path.with_suffix('.json')
        meta_path.write_text(json.dumps(
            out, indent=2, ensure_ascii=False), encoding='utf-8')
        out['metadata'] = str(meta_path)

        return out
