import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

from diffusers import (StableDiffusionXLControlNetImg2ImgPipeline,
                       StableDiffusionXLImg2ImgPipeline)
from PIL import Image

from stability.cache.models import get_sdxl_base_pipe
from stability.core.config import *
from stability.core.paths import ensure_out_dir
from stability.dag import NodeRef
from stability.nodes.common.config_resolve import SpecInput
from stability.nodes.common.cuda_stat import *
from stability.nodes.common.env import setup_env
from stability.nodes.io import finalize_image_output, save_image
from stability.nodes.sdxl_pipe_builder import build_pipe_kwargs
from stability.nodes.sdxl_resolve import resolve_common
from stability.nodes.wiring.conditioning import apply_ip_adapter
from stability.nodes.wiring.mixins import ControlNetMixin, PromptMixin
from stability.nodes.wiring.prompt import PromptBundle


@dataclass
class Img2Img(ControlNetMixin, PromptMixin, NodeRef):
    """
    SDXL image-to-image generation node with optional ControlNet and IP-Adapter/FaceID conditioning.

    This node performs an image-to-image transformation using Stable Diffusion XL.
    The init image is provided by the upstream node connected to the default input
    channel (``input_id="default"``). Text prompts are resolved from the node
    configuration and may optionally be overridden by an upstream prompt bundle
    connected through the prompt channel (see Notes).

    If one or more ControlNet specifications are configured on this node, the
    underlying pipeline switches to ``StableDiffusionXLControlNetImg2ImgPipeline``
    and uses the attached ControlNet conditioning images. Otherwise, it uses the
    standard ``StableDiffusionXLImg2ImgPipeline``. IP-Adapter / FaceID conditioning
    is enabled or disabled based on the resolved bundles. IP-Adapter and FaceID are
    mutually exclusive.

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : dict or str or pathlib.Path or sequence of (dict or str or pathlib.Path)
        Node configuration specification.

        The specification may be provided as an in-memory dictionary, as a path
        to a HOCON configuration file, or as a sequence of such elements. When a
        sequence is given, each element is resolved independently and merged from
        left to right, with later elements overriding earlier ones.

        The node uses :func:`resolve_common` to resolve the shared SDXL configuration.
        Expected keys include:

        **Model / runtime**
        - ``model.path`` : str (required)
            Local path or identifier for the SDXL base model to load.
        - ``model.device`` : str, optional
            Device to run on (default: ``"cuda"``).
        - ``model.dtype`` : str, optional
            DType name resolved by ``resolve_dtype`` (default: ``"bf16"``).

        **VAE**
        - ``vae`` : str or dict, optional
            Either a VAE id string, or a dict with ``vae.id``.

        **Generation parameters** (under ``params``)
        - ``params.steps`` : int, optional
            Number of denoising steps (default: 30).
        - ``params.cfg`` or ``params.guidance_scale`` : float, optional
            Classifier-free guidance scale (default: 6.0). ``cfg`` takes precedence.
        - ``params.strength`` : float, optional
            Denoising strength controlling how strongly the init image is transformed
            (default: 0.7).
        - ``params.width`` : int, optional
            Output width (default: 1024).
        - ``params.height`` : int, optional
            Output height (default: 1024).

        **Randomness**
        - ``seed`` : int or str, optional
            Seed value or ``"random"`` (default: ``"random"``). Resolved by
            ``resolve_seed``.

    Attributes
    ----------
    op : str
        Operator identifier derived from the concrete node class name (e.g.
        ``"img2img"``).
    controlnet : ControlNetRegistry
        Registry used to declare ControlNet conditioning inputs (via sinks),
        provided by ``ControlNetMixin``.
    ip_adapter : IpAdapterRegistry
        Registry used to declare IP-Adapter reference inputs (via sinks),
        provided by ``ControlNetMixin``.
    face_id : FaceIdRegistry
        Registry used to declare FaceID reference inputs (via sinks),
        provided by ``ControlNetMixin``.
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by
        ``PromptMixin``.

    Inputs
    ------
    default : dict
        Required. Upstream output dictionary containing the init image path. The node
        expects either ``"image"`` or ``"path"`` to point to the image file.

    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Expected keys include ``prompt``, ``prompt_2``,
        ``negative_prompt``, and ``negative_prompt_2``.

    Additional typed inputs may be attached via ControlNet/IP-Adapter/FaceID sinks
    declared on this node (see Notes).

    Outputs
    -------
    dict
        Primary output dictionary with at least:

        - ``ok`` : bool
        - ``node`` : str (e.g. ``"img2img"``)
        - ``id`` : str (node id)
        - ``image`` : str (path to the generated image)
        - ``metadata`` : str (path to a JSON sidecar with generation details)

        The metadata sidecar includes resolved parameters, timing information, and
        (when running on CUDA) memory statistics.

    Notes
    -----
    - The init image is loaded from the upstream path, converted to RGB, and resized
    to ``(width, height)`` prior to generation.
    - Prompt resolution is performed by :class:`PromptBundle`: if a prompt bundle is
    wired into ``prompt:default``, it takes precedence over the local ``spec``;
    otherwise the local ``spec`` is used.
    - ControlNet, IP-Adapter, and FaceID inputs are collected from DAG wiring
    through their respective registries and bundled via
    ``build_control_bundles``.
    - When ControlNet is enabled, this node calls the img2img pipeline with
    ``image=init_image`` and passes ControlNet conditioning via ``control_image``
    (through ``build_pipe_kwargs(..., init_image_already_passed=True)``).
    - IP-Adapter and FaceID are mutually exclusive in this node.
    """

    spec: SpecInput = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # HF env
        setup_env()

        ctx = resolve_common(self.spec)

        input = input or {}

        # 1) init image comes from default input_id
        init_up = input.get('default')
        if init_up is None:
            raise ValueError(
                'Img2Img requires an init image wired into the default input (src >> img2img).')

        init_path = init_up.get('image') or init_up.get('path')
        if not init_path:
            raise ValueError(
                "Init image upstream output must contain 'image' (path).")

        init_image = Image.open(init_path) \
            .convert('RGB') \
            .resize((ctx.width, ctx.height))

        # --- resolve inputs from DAG wiring ---
        cn_bundle, ip_bundle, face_bundle = self.build_control_bundles(
            input=input,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        base = get_sdxl_base_pipe(
            model_ref=ctx.model.model_ref,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
            vae_id=ctx.model.vae_id,
        )

        if ip_bundle.has_ip_adapter and face_bundle.has_face_id:
            raise ValueError(
                'IP_Adapter and IP-Adapter-FaceID are mutually exclusive (chose one).'
            )

        # pipeline load (two-path: direct or via base components)
        if cn_bundle.has_controlnet:
            pipe = StableDiffusionXLControlNetImg2ImgPipeline(
                **base.components,
                controlnet=cn_bundle.controlnet_arg
            )
        else:
            pipe = StableDiffusionXLImg2ImgPipeline(
                **base.components
            )

        prompt_bundle = PromptBundle(spec=ctx.spec, input=input)

        cuda_prerun(ctx.model.device)
        t0 = time.perf_counter()

        apply_ip_adapter(
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            pipe=pipe,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        pipe_kwargs = build_pipe_kwargs(
            cn_bundle=cn_bundle,
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            height=ctx.height,
            width=ctx.width,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
            init_image_already_passed=True,
        )

        if 'cross_attention_kwargs' in pipe_kwargs:
            l = len(ip_bundle.weight_names_arg) + \
                len(face_bundle.weight_names_arg)
            masks = pipe_kwargs['cross_attention_kwargs']['ip_adapter_masks']
            assert len(masks) == l

        # IMPORTANT: Img2Img + ControlNet uses image=init and control_image=control :contentReference[oaicite:3]{index=3}
        result = pipe(
            prompt=prompt_bundle.prompt,
            prompt_2=prompt_bundle.prompt_2,
            negative_prompt=prompt_bundle.negative_prompt,
            negative_prompt_2=prompt_bundle.negative_prompt_2,
            image=init_image,
            strength=ctx.strength,
            num_inference_steps=ctx.steps,
            guidance_scale=ctx.cfg,
            generator=ctx.rng.gen,
            width=ctx.width,
            height=ctx.height,
            **pipe_kwargs
        )

        cuda_sync(ctx.model.device)
        dt_s = time.perf_counter() - t0

        img = result.images[0]

        out_dir = ensure_out_dir(output_dir)
        img_path = save_image(
            out_dir,
            node_id=self.id,
            seed=ctx.rng.seed,
            img=img,
        )

        mem = cuda_mem_stats(ctx.model.device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_path,
            seed=ctx.rng.seed,
            params={
                'steps': ctx.steps,
                'guidance_scale': ctx.cfg,
                'strength': ctx.strength,
                'width': ctx.width,
                'height': ctx.height,
            },
            dt_s=dt_s,
            cuda_mem=mem,
            controlnet_specs=self.controlnet.specs,
            ip_adapter_specs=self.ip_adapter.specs,
            face_id_specs=self.face_id.specs,
            model_info={
                'source': ctx.model.model_ref.source,
                'ref': ctx.model.model_ref.ref,
                **({'vae_id': ctx.model.vae_id} if ctx.model.vae_id is not None else {}),
                'dtype': str(ctx.model.dtype).replace('torch.', ''),
                'device': ctx.model.device,
            }
        )

        return out
