
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

import cv2
import numpy as np
import torch
from PIL import Image
from transformers import DPTForDepthEstimation, DPTImageProcessor

from stability.cache.models import get_depth_estimator
from stability.dag import NodeRef
from stability.nodes import make_node_output_path


@dataclass
class CannyEdge(NodeRef):
    """
    Image preprocessing node that computes a Canny edge map.

    This node takes an input image (via the default DAG connection),
    applies the Canny edge detection algorithm, and produces a 3-channel
    RGB edge image suitable for use as a ControlNet conditioning image.

    The output image is saved to disk and exposed via the standard
    ``image`` field in the node output dictionary.

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    low_threshold : int, optional
        Lower hysteresis threshold for the Canny algorithm.
    high_threshold : int, optional
        Upper hysteresis threshold for the Canny algorithm.

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the class name
        (``"canny_edge"``).
    """

    low_threshold: int = 100
    high_threshold: int = 200

    def run(self, output_dir, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        """
        Executes the Canny edge detection.

        Parameters
        ----------
        output_dir : str or Path-like
            Base directory where the generated edge image will be saved.
        input : dict, optional
            Mapping of input identifiers to upstream node outputs.
            The default input must contain an ``image`` field pointing
            to the source image path.

        Returns
        -------
        dict
            Output dictionary containing:
            - ``image``: path to the generated Canny edge image
            - ``metadata``: path to a JSON sidecar with parameters
        """
        input = input or {}

        upstream = input.get('default')
        if upstream is None:
            raise ValueError(
                'CannyEdge requires an input image wired to the default input.')

        img_path = upstream.get('image') or upstream.get('path')
        if not img_path:
            raise ValueError('Upstream output does not contain an image path.')

        # Load image
        img = Image.open(img_path).convert('RGB')
        img_np = np.array(img)

        # Apply Canny
        edges = cv2.Canny(
            img_np,
            threshold1=int(self.low_threshold),
            threshold2=int(self.high_threshold),
        )

        # Convert to 3-channel RGB (as expected by most ControlNets)
        edges_rgb = np.stack([edges, edges, edges], axis=2)
        edge_img = Image.fromarray(edges_rgb)

        # Save output
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        # --- save image ---
        out_path = make_node_output_path(out_dir=out_dir, node_id=self.id)
        edge_img.save(out_path)

        # Metadata
        out = {
            'ok': True,
            'node': self.op,
            'id': self.id,
            'image': str(out_path),
            'params': {
                'low_threshold': self.low_threshold,
                'high_threshold': self.high_threshold,
            },
        }

        meta_path = out_path.with_suffix('.json')
        meta_path.write_text(
            json.dumps(out, indent=2, ensure_ascii=False),
            encoding='utf-8',
        )
        out['metadata'] = str(meta_path)

        return out


@dataclass
class DepthMap(NodeRef):
    """
    Image preprocessing node that computes a depth map (MiDaS/DPT).

    This node takes an input image (via the default DAG connection),
    runs a depth estimation model (DPT), and produces a 3-channel RGB
    depth image suitable for use as a ControlNet conditioning image.

    The output image is saved to disk and exposed via the standard
    'image' field in the node output dictionary.

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    model_id : str, optional
        Hugging Face model id for depth estimation.
        Default: 'Intel/dpt-hybrid-midas'
    device : str, optional
        Device for inference (e.g. 'cuda', 'cpu').
    size : int, optional
        Output depth map size (square). ControlNet examples typically use 1024.
    autocast : bool, optional
        If True and device is CUDA, uses torch.autocast for faster inference.

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the class name
        (e.g. 'depth_map').
    """

    model_id: str = 'Intel/dpt-hybrid-midas'
    device: str = 'cuda'
    size: int = 1024
    autocast: bool = True

    # internal cached model/processor per-process (simple, effective)
    _model: Optional[DPTForDepthEstimation] = field(
        default=None, init=False, repr=False)
    _processor: Optional[DPTImageProcessor] = field(
        default=None, init=False, repr=False)

    def _lazy_load(self) -> None:
        if self._model is not None and self._processor is not None:
            return

        self._processor, self._model = get_depth_estimator(
            model_id=self.model_id,
            device=self.device
        )

    def run(self, output_dir, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        """
        Executes depth estimation and writes a depth map image to disk.

        Parameters
        ----------
        output_dir : str or Path-like
            Base directory where the generated depth image will be saved.
        input : dict, optional
            Mapping of input identifiers to upstream node outputs.
            The default input must contain an 'image' field pointing
            to the source image path.

        Returns
        -------
        dict
            Output dictionary containing:
            - 'image': path to the generated depth map image
            - 'metadata': path to a JSON sidecar with parameters
        """
        input = input or {}

        upstream = input.get('default')
        if upstream is None:
            raise ValueError(
                'DepthMap requires an input image wired to the default input.')

        img_path = upstream.get('image') or upstream.get('path')
        if not img_path:
            raise ValueError('Upstream output does not contain an image path.')

        self._lazy_load()

        src_img = Image.open(img_path).convert('RGB')

        # Preprocess
        assert self._processor is not None
        assert self._model is not None

        pixel_values = self._processor(
            images=src_img, return_tensors='pt').pixel_values.to(self.device)

        # Inference (match HF example semantics)
        use_autocast = bool(self.autocast) and str(
            self.device).startswith('cuda')
        with torch.no_grad():
            if use_autocast:
                with torch.autocast('cuda'):
                    depth = self._model(pixel_values).predicted_depth
            else:
                depth = self._model(pixel_values).predicted_depth

        # Resize to target size
        depth = torch.nn.functional.interpolate(
            depth.unsqueeze(1),
            size=(int(self.size), int(self.size)),
            mode='bicubic',
            align_corners=False,
        )

        # Normalize to [0, 1]
        depth_min = torch.amin(depth, dim=[1, 2, 3], keepdim=True)
        depth_max = torch.amax(depth, dim=[1, 2, 3], keepdim=True)
        depth = (depth - depth_min) / (depth_max - depth_min + 1e-8)

        # Convert to 3-channel RGB image (HWC uint8)
        rgb = torch.cat([depth] * 3, dim=1)
        rgb = rgb.permute(0, 2, 3, 1).detach().cpu().numpy()[0]
        rgb_img = Image.fromarray((rgb * 255.0).clip(0, 255).astype(np.uint8))

        # Save output
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        # --- save image ---
        out_path = make_node_output_path(out_dir=out_dir, node_id=self.id)
        rgb_img.save(out_path)

        out = {
            'ok': True,
            'node': self.op,
            'id': self.id,
            'image': str(out_path),
            'params': {
                'model_id': self.model_id,
                'device': self.device,
                'size': int(self.size),
                'autocast': bool(self.autocast),
            },
        }

        meta_path = out_path.with_suffix('.json')
        meta_path.write_text(
            json.dumps(out, indent=2, ensure_ascii=False),
            encoding='utf-8',
        )
        out['metadata'] = str(meta_path)

        return out
