import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

from diffusers import (StableDiffusionXLControlNetInpaintPipeline,
                       StableDiffusionXLInpaintPipeline)
from PIL import Image

from stability.cache.models import get_sdxl_base_pipe
from stability.core.config import *
from stability.core.paths import ensure_out_dir
from stability.dag import AttachmentSink, NodeRef
from stability.nodes.common.config_resolve import SpecInput
from stability.nodes.common.cuda_stat import *
from stability.nodes.common.env import setup_env
from stability.nodes.io import finalize_image_output, save_image
from stability.nodes.sdxl_pipe_builder import build_pipe_kwargs
from stability.nodes.sdxl_resolve import resolve_common
from stability.nodes.wiring.conditioning import apply_ip_adapter
from stability.nodes.wiring.mixins import ControlNetMixin, PromptMixin
from stability.nodes.wiring.prompt import PromptBundle


@dataclass
class Inpaint(ControlNetMixin, PromptMixin, NodeRef):
    """
    SDXL inpainting node with optional ControlNet and IP-Adapter/FaceID conditioning.

    This node performs inpainting using Stable Diffusion XL. The init image is
    provided by the upstream node connected to the default input channel
    (``input_id="default"``). The inpainting mask is provided by an upstream node
    connected to the mask input channel (``input_id="mask"``). Text prompts are
    resolved from the node configuration and may optionally be overridden by an
    upstream prompt bundle connected through the prompt channel (see Notes).

    If one or more ControlNet specifications are configured on this node, the
    underlying pipeline switches to ``StableDiffusionXLControlNetInpaintPipeline``
    and uses the attached ControlNet conditioning images. Otherwise, it uses the
    standard ``StableDiffusionXLInpaintPipeline``. IP-Adapter / FaceID conditioning
    is enabled or disabled based on the resolved bundles. IP-Adapter and FaceID are
    mutually exclusive.

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : dict or str or pathlib.Path or sequence of (dict or str or pathlib.Path)
        Node configuration specification.

        The specification may be provided as an in-memory dictionary, as a path
        to a HOCON configuration file, or as a sequence of such elements. When a
        sequence is given, each element is resolved independently and merged from
        left to right, with later elements overriding earlier ones.

        The node uses :func:`resolve_common` to resolve the shared SDXL configuration.
        Expected keys include:

        **Model / runtime**
        - ``model.path`` : str (required)
            Local path or identifier for the SDXL base model to load.
        - ``model.device`` : str, optional
            Device to run on (default: ``"cuda"``).
        - ``model.dtype`` : str, optional
            DType name resolved by ``resolve_dtype`` (default: ``"bf16"``).

        **VAE**
        - ``vae`` : str or dict, optional
            Either a VAE id string, or a dict with ``vae.id``.

        **Generation parameters** (under ``params``)
        - ``params.steps`` : int, optional
            Number of denoising steps (default: 30).
        - ``params.cfg`` or ``params.guidance_scale`` : float, optional
            Classifier-free guidance scale (default: 6.0). ``cfg`` takes precedence.
        - ``params.strength`` : float, optional
            Denoising strength controlling how strongly the masked region is
            re-synthesized (default: 0.7).
        - ``params.width`` : int, optional
            Output width (default: 1024).
        - ``params.height`` : int, optional
            Output height (default: 1024).

        **Randomness**
        - ``seed`` : int or str, optional
            Seed value or ``"random"`` (default: ``"random"``). Resolved by
            ``resolve_seed``.

    Attributes
    ----------
    op : str
        Operator identifier derived from the concrete node class name (e.g.
        ``"inpaint"``).
    controlnet : ControlNetRegistry
        Registry used to declare ControlNet conditioning inputs (via sinks),
        provided by ``ControlNetMixin``.
    ip_adapter : IpAdapterRegistry
        Registry used to declare IP-Adapter reference inputs (via sinks),
        provided by ``ControlNetMixin``.
    face_id : FaceIdRegistry
        Registry used to declare FaceID reference inputs (via sinks),
        provided by ``ControlNetMixin``.
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by
        ``PromptMixin``.

    Inputs
    ------
    default : dict
        Required. Upstream output dictionary containing the init image path. The
        node expects either ``"image"`` or ``"path"`` to point to the image file.

    mask : dict
        Required. Upstream output dictionary containing the mask image path. The
        node expects either ``"image"`` or ``"path"`` to point to the mask file.
        Convention: white areas are repainted; black areas are preserved.

    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Expected keys include ``prompt``, ``prompt_2``,
        ``negative_prompt``, and ``negative_prompt_2``.

    Additional typed inputs may be attached via ControlNet/IP-Adapter/FaceID sinks
    declared on this node (see Notes).

    Outputs
    -------
    dict
        Primary output dictionary with at least:

        - ``ok`` : bool
        - ``node`` : str (e.g. ``"inpaint"``)
        - ``id`` : str (node id)
        - ``image`` : str (path to the generated image)
        - ``metadata`` : str (path to a JSON sidecar with generation details)

        The metadata sidecar includes resolved parameters, timing information, and
        (when running on CUDA) memory statistics.

    Notes
    -----
    - The init image is loaded from the upstream path, converted to RGB, and resized
    to ``(width, height)`` prior to generation.
    - The mask image is loaded from the upstream path, converted to single-channel
    (``"L"``), and resized to ``(width, height)``. White areas are repainted and
    black areas preserved (mask polarity depends on mask authoring conventions).
    - Prompt resolution is performed by :class:`PromptBundle`: if a prompt bundle is
    wired into ``prompt:default``, it takes precedence over the local ``spec``;
    otherwise the local ``spec`` is used.
    - ControlNet, IP-Adapter, and FaceID inputs are collected from DAG wiring
    through their respective registries and bundled via
    ``build_control_bundles``.
    - When ControlNet is enabled, this node calls the inpaint pipeline with
    ``image=init_image`` and ``control_image=<conditioning>`` (via
    ``build_pipe_kwargs(..., init_image_already_passed=True)``).
    - IP-Adapter and FaceID are mutually exclusive in this node.
    """

    spec: SpecInput = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    def mask(self):
        """
        Declare the mask input sink for the inpainting operation.

        This method exposes an :class:`AttachmentSink` that allows an upstream node
        to provide the inpainting mask. The mask defines which regions of the init
        image are subject to modification during generation.

        The attached upstream output must contain an image path under either the
        ``"image"`` or ``"path"`` key. The mask image is interpreted according to
        Stable Diffusion XL inpainting conventions: white regions are repainted,
        while black regions are preserved.

        Returns
        -------
        AttachmentSink
            A sink bound to this node with ``input_id="mask"``, used to wire an
            upstream mask-producing node into the inpainting pipeline.

        Notes
        -----
        - The mask is loaded at runtime, converted to single-channel (``"L"``),
        and resized to match the resolved ``(width, height)`` of the generation.
        - Mask polarity (white = repaint, black = keep) follows Diffusers SDXL
        inpainting conventions; users are responsible for providing masks with
        the correct polarity.
        - This sink is required for successful execution of the ``Inpaint`` node.
        """
        return AttachmentSink(
            name=f'inpaint_mask:{self.id}',
            target=self,
            input_id=f'mask',
        )

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        setup_env()
        ctx = resolve_common(self.spec)

        input = input or {}

        # 1) init image (default)
        init_up = input.get('default')
        if init_up is None:
            raise ValueError(
                'Inpaint requires an init image wired into the default input (src >> inpaint).'
            )

        init_path = init_up.get('image') or init_up.get('path')
        if not init_path:
            raise ValueError(
                "Init image upstream output must contain 'image' (path).")

        init_image = Image.open(init_path) \
            .convert('RGB') \
            .resize((ctx.width, ctx.height))

        # 2) mask image (mask)
        mask_up = input.get('mask')
        if mask_up is None:
            raise ValueError(
                'Inpaint requires a mask image wired into input_id="mask" (src >> inpaint.mask). '
            )

        mask_path = mask_up.get('image') or mask_up.get('path')
        if not mask_path:
            raise ValueError(
                "Mask upstream output must contain 'image' (path).")

        # keep mask as single channel for sanity; resize to match
        mask_image = Image.open(mask_path) \
            .convert('L') \
            .resize((ctx.width, ctx.height))

        # --- resolve conditioning bundles from DAG wiring ---
        cn_bundle, ip_bundle, face_bundle = self.build_control_bundles(
            input=input,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        base = get_sdxl_base_pipe(
            model_ref=ctx.model.model_ref,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
            vae_id=ctx.model.vae_id,
        )

        if ip_bundle.has_ip_adapter and face_bundle.has_face_id:
            raise ValueError(
                'IP_Adapter and IP-Adapter-FaceID are mutually exclusive (chose one).'
            )

        # pipeline load (two-path: standard vs controlnet)
        if cn_bundle.has_controlnet:
            pipe = StableDiffusionXLControlNetInpaintPipeline(
                **base.components,
                controlnet=cn_bundle.controlnet_arg
            )
        else:
            pipe = StableDiffusionXLInpaintPipeline(
                **base.components
            )

        prompt_bundle = PromptBundle(spec=ctx.spec, input=input)

        cuda_prerun(ctx.model.device)
        t0 = time.perf_counter()

        apply_ip_adapter(
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            pipe=pipe,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        pipe_kwargs = build_pipe_kwargs(
            cn_bundle=cn_bundle,
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            height=ctx.height,
            width=ctx.width,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
            init_image_already_passed=True,
        )

        # sanity-check ip-adapter masks length if present
        if 'cross_attention_kwargs' in pipe_kwargs:
            l = len(ip_bundle.weight_names_arg) + \
                len(face_bundle.weight_names_arg)
            masks = pipe_kwargs['cross_attention_kwargs']['ip_adapter_masks']
            assert len(masks) == l

        result = pipe(
            prompt=prompt_bundle.prompt,
            prompt_2=prompt_bundle.prompt_2,
            negative_prompt=prompt_bundle.negative_prompt,
            negative_prompt_2=prompt_bundle.negative_prompt_2,
            image=init_image,
            mask_image=mask_image,
            strength=ctx.strength,
            num_inference_steps=ctx.steps,
            guidance_scale=ctx.cfg,
            generator=ctx.rng.gen,
            width=ctx.width,
            height=ctx.height,
            **pipe_kwargs
        )

        cuda_sync(ctx.model.device)
        dt_s = time.perf_counter() - t0

        img = result.images[0]

        out_dir = ensure_out_dir(output_dir)
        img_path = save_image(
            out_dir,
            node_id=self.id,
            seed=ctx.rng.seed,
            img=img,
        )

        mem = cuda_mem_stats(ctx.model.device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_path,
            seed=ctx.rng.seed,
            params={
                'steps': ctx.steps,
                'guidance_scale': ctx.cfg,
                'strength': ctx.strength,
                'width': ctx.width,
                'height': ctx.height,
            },
            dt_s=dt_s,
            cuda_mem=mem,
            controlnet_specs=self.controlnet.specs,
            ip_adapter_specs=self.ip_adapter.specs,
            face_id_specs=self.face_id.specs,
            model_info={
                'source': ctx.model.model_ref.source,
                'ref': ctx.model.model_ref.ref,
                **({'vae_id': ctx.model.vae_id} if ctx.model.vae_id is not None else {}),
                'dtype': str(ctx.model.dtype).replace('torch.', ''),
                'device': ctx.model.device,
            }
        )

        return out
