import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional, Union

from diffusers import (StableDiffusionXLAdapterPipeline,
                       StableDiffusionXLControlNetPipeline,
                       StableDiffusionXLPipeline)

from stability.cache.models import get_sdxl_base_pipe
from stability.core.config import *
from stability.core.paths import ensure_out_dir
from stability.dag import NodeRef
from stability.nodes.common.config_resolve import SpecInput
from stability.nodes.common.cuda_stat import *
from stability.nodes.common.env import setup_env
from stability.nodes.io import finalize_image_output, save_image
from stability.nodes.sdxl_pipe_builder import build_pipe_kwargs
from stability.nodes.sdxl_resolve import resolve_common
from stability.nodes.wiring.conditioning import apply_ip_adapter
from stability.nodes.wiring.mixins import *
from stability.nodes.wiring.prompt import PromptBundle


@dataclass
class Txt2Img(T2IAdapterMixin, ControlNetMixin, PromptMixin, NodeRef):
    """
    SDXL text-to-image generation node with optional ControlNet, T2I-Adapter, and IP-Adapter/FaceID.

    This node generates an image from text prompts using Stable Diffusion XL. Prompts
    are resolved from the node configuration and may optionally be overridden by an
    upstream prompt bundle attached through the prompt channel (see Notes).

    Depending on the configured conditioning mechanisms, the node selects one of the
    following pipelines:

    - If one or more ControlNet specifications are configured, the node uses
    ``StableDiffusionXLControlNetPipeline`` and conditions the generation on the
    attached ControlNet images (e.g. canny, depth, lineart).
    - Else, if one or more T2I-Adapter specifications are configured, the node uses
    ``StableDiffusionXLAdapterPipeline`` and conditions the generation on the
    attached adapter images.
    - Otherwise, the node falls back to the standard ``StableDiffusionXLPipeline``.

    IP-Adapter / FaceID conditioning (image-based reference guidance) is orthogonal
    to the above choices and may be enabled or disabled independently, based on the
    resolved bundles. IP-Adapter and FaceID are mutually exclusive.

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : dict or str or pathlib.Path or sequence of (dict or str or pathlib.Path)
        Node configuration specification.

        The specification may be provided as an in-memory dictionary, as a path to a
        HOCON configuration file, or as a sequence of such elements. When a sequence
        is given, each element is resolved independently and merged from left to
        right, with later elements overriding earlier ones.

        The node uses :func:`resolve_common` to resolve the shared SDXL configuration.
        Expected keys include:

        **Model / runtime**
        - ``model.path`` : str (required)
            Local path or identifier for the SDXL base model to load.
        - ``model.device`` : str, optional
            Device to run on (default: ``"cuda"``).
        - ``model.dtype`` : str, optional
            DType name resolved by ``resolve_dtype`` (default: ``"bf16"``).

        **VAE**
        - ``vae`` : str or dict, optional
            Either a VAE id string, or a dict with ``vae.id``.

        **Generation parameters** (under ``params``)
        - ``params.steps`` : int, optional
            Number of denoising steps (default: 30).
        - ``params.cfg`` or ``params.guidance_scale`` : float, optional
            Classifier-free guidance scale (default: 6.0). ``cfg`` takes precedence.
        - ``params.width`` : int, optional
            Output width (default: 1024).
        - ``params.height`` : int, optional
            Output height (default: 1024).

        **Randomness**
        - ``seed`` : int or str, optional
            Seed value or ``"random"`` (default: ``"random"``). Resolved by
            ``resolve_seed``.

    Attributes
    ----------
    op : str
        Operator identifier derived from the concrete node class name (e.g.
        ``"txt2img"``).
    controlnet : ControlNetRegistry
        Registry used to declare ControlNet conditioning inputs (via sinks),
        provided by ``ControlNetMixin``.
    t2i_adapter : T2IAdapterRegistry
        Registry used to declare T2I-Adapter conditioning inputs (via sinks),
        provided by ``T2IAdapterMixin``.
    ip_adapter : IpAdapterRegistry
        Registry used to declare IP-Adapter reference inputs (via sinks),
        provided by ``ControlNetMixin``.
    face_id : FaceIdRegistry
        Registry used to declare FaceID reference inputs (via sinks),
        provided by ``ControlNetMixin``.
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by
        ``PromptMixin``.

    Inputs
    ------
    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Expected keys include ``prompt``, ``prompt_2``,
        ``negative_prompt``, and ``negative_prompt_2``.

    Additional typed inputs may be attached via ControlNet, T2I-Adapter, IP-Adapter,
    or FaceID sinks declared on this node (see Notes).

    Outputs
    -------
    dict
        Primary output dictionary with at least:

        - ``ok`` : bool
        - ``node`` : str (e.g. ``"txt2img"``)
        - ``id`` : str (node id)
        - ``image`` : str (path to the generated image)
        - ``metadata`` : str (path to a JSON sidecar with generation details)

        The metadata sidecar includes resolved parameters, model information, timing
        information, and (when running on CUDA) memory statistics.

    Notes
    -----
    - Hugging Face cache and environment variables are configured via ``setup_env()``
    prior to loading any pipeline components.
    - Prompt resolution is performed by :class:`PromptBundle`: if a prompt bundle is
    wired into ``prompt:default``, it takes precedence over the local ``spec``;
    otherwise the local ``spec`` is used.
    - ControlNet and T2I-Adapter inputs are collected from DAG wiring through their
    respective registries and resolved into runtime bundles before pipeline
    construction.
    - ControlNet and T2I-Adapter are mutually exclusive within the same node.
    Attempting to enable both results in an error.
    - For ``StableDiffusionXLControlNetPipeline`` (txt2img), ControlNet conditioning
    images are passed via the pipeline ``image`` argument together with
    ``controlnet_conditioning_scale`` (via :func:`build_pipe_kwargs`).
    - For ``StableDiffusionXLAdapterPipeline`` (txt2img), adapter conditioning images
    are passed via the pipeline ``image`` argument together with
    ``adapter_conditioning_scale`` (via :func:`build_pipe_kwargs`).
    - IP-Adapter conditioning uses one or more reference images passed through
    ``ip_adapter_image``; FaceID uses precomputed embeddings passed through
    ``ip_adapter_image_embeds``. IP-Adapter and FaceID are mutually exclusive.
    - Outputs are written as an image file plus a JSON sidecar containing run metadata
    (parameters, model info, timing, and optional CUDA memory stats).
    """

    spec: SpecInput = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # --- Hugging Face env (must be set before loading) ---
        # HF env
        setup_env()

        ctx = resolve_common(self.spec)

        # --- resolve inputs from DAG wiring ---
        cn_bundle, ip_bundle, face_bundle = self.build_control_bundles(
            input=input,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )
        t2i_bundle = self.build_t2i_adapter_bundle(
            input=input,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        base = get_sdxl_base_pipe(
            model_ref=ctx.model.model_ref,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
            vae_id=ctx.model.vae_id,
        )

        if ip_bundle.has_ip_adapter and face_bundle.has_face_id:
            raise ValueError(
                'IP_Adapter and IP-Adapter-FaceID are mutually exclusive (chose one).'
            )

        if cn_bundle.has_controlnet and t2i_bundle.has_t2i_adapter:
            raise ValueError(
                'ControlNet and T2I-Adapter are mutually exclusive in Txt2Img (choose one).'
            )

        if cn_bundle.has_controlnet:
            pipe = StableDiffusionXLControlNetPipeline(
                **base.components,
                controlnet=cn_bundle.controlnet_arg
            )
        elif t2i_bundle.has_t2i_adapter:
            pipe = StableDiffusionXLAdapterPipeline(
                **base.components,
                adapter=t2i_bundle.adapter_model_arg
            )
        else:
            pipe = StableDiffusionXLPipeline(**base.components)

        prompt_bundle = PromptBundle(spec=ctx.spec, input=input)

        cuda_prerun(ctx.model.device)
        t0 = time.perf_counter()

        apply_ip_adapter(
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            pipe=pipe,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        pipe_kwargs = build_pipe_kwargs(
            cn_bundle=cn_bundle,
            t2i_bundle=t2i_bundle,
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            height=ctx.height,
            width=ctx.width,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        if 'cross_attention_kwargs' in pipe_kwargs:
            l = len(ip_bundle.weight_names_arg) + \
                len(face_bundle.weight_names_arg)
            masks = pipe_kwargs['cross_attention_kwargs']['ip_adapter_masks']
            assert len(masks) == l

        result = pipe(
            prompt=prompt_bundle.prompt,
            prompt_2=prompt_bundle.prompt_2,
            negative_prompt=prompt_bundle.negative_prompt,
            negative_prompt_2=prompt_bundle.negative_prompt_2,
            num_inference_steps=ctx.steps,
            guidance_scale=ctx.cfg,
            generator=ctx.rng.gen,
            width=ctx.width,
            height=ctx.height,
            **pipe_kwargs,
        )

        cuda_sync(ctx.model.device)
        dt_s = time.perf_counter() - t0

        img = result.images[0]

        out_dir = ensure_out_dir(output_dir)
        img_path = save_image(
            out_dir,
            node_id=self.id,
            seed=ctx.rng.seed,
            img=img,
        )

        mem = cuda_mem_stats(ctx.model.device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_path,
            seed=ctx.rng.seed,
            params={
                'steps': ctx.steps,
                'guidance_scale': ctx.cfg,
                'width': ctx.width,
                'height': ctx.height,
            },
            dt_s=dt_s,
            cuda_mem=mem,
            controlnet_specs=self.controlnet.specs,
            t2i_adapter_specs=self.t2i_adapter.specs,
            ip_adapter_specs=self.ip_adapter.specs,
            face_id_specs=self.face_id.specs,
            model_info={
                'source': ctx.model.model_ref.source,
                'ref': ctx.model.model_ref.ref,
                **({'vae_id': ctx.model.vae_id} if ctx.model.vae_id is not None else {}),
                'dtype': str(ctx.model.dtype).replace('torch.', ''),
                'device': ctx.model.device,
            }
        )

        return out
