import json
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

import torch
from diffusers import (StableDiffusionXLControlNetPipeline,
                       StableDiffusionXLPipeline)

from stability.cache.models import get_sdxl_base_pipe
from stability.core.config import *
from stability.dag import NodeRef
from stability.nodes import *


@dataclass
class Txt2Img(NodeRef):
    """
    Text-to-image node with optional ControlNet conditioning.

    This node generates an image from a text prompt using an SDXL-based
    text-to-image pipeline. One or more ControlNet inputs may be attached
    to guide the generation process.

    ControlNet inputs are declared by calling ``createControlNet()`` or its
    alias ``addControlNet()``. Both names are equivalent and return an
    ``AttachmentSink`` that can be wired using the ``>>`` operator.

    The node produces a single primary output dictionary containing at least:
    - ``image``: filesystem path to the generated image
    - ``metadata``: filesystem path to a JSON sidecar with generation details

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    spec : dict
        Configuration dictionary describing the model, prompts, and
        generation parameters. Typical keys include ``model``, ``prompt``,
        ``negative_prompt``, ``params``, ``seed``, and optional ``vae``.

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class
        name (e.g. ``"txt2img"``).
    """

    spec: Union[Dict[str, Any], str, Path] = field(default_factory=dict)
    controlnet: ControlNetRegistry = field(init=False, repr=False)
    ip_adapter: IpAdapterRegistry = field(init=False, repr=False)

    def __post_init__(self) -> None:
        super().__post_init__()  # registra il nodo nel DAG, assegna id/op
        self.controlnet = ControlNetRegistry(owner=self)
        self.ip_adapter = IpAdapterRegistry(owner=self)

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        """
        Executes the T2I node. If ControlNets were declared, uses an SDXL ControlNet pipeline.
        """
        # --- Hugging Face env (must be set before loading) ---
        os.environ['HF_HOME'] = HF_HOME
        os.environ['HF_HUB_CACHE'] = HF_HUB_CACHE
        os.environ['HF_HUB_DISABLE_TELEMETRY'] = HF_HUB_DISABLE_TELEMETRY

        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        spec = resolve_spec(self.spec)

        # --- model settings ---
        model = spec.get('model', {})
        device = model.get('device', 'cuda')
        dtype = resolve_dtype(model.get('dtype', 'bf16'))

        model_path = model.get('path')
        if not model_path:
            raise ValueError('spec.model.path is required')

        # --- prompts ---
        prompt, prompt_2 = norm_prompt_pair(spec.get('prompt'))
        negative_prompt, negative_prompt_2 = norm_prompt_pair(
            spec.get('negative_prompt'),
            joiner=', '
        )

        # --- params ---
        params = spec.get('params', {})
        steps = int(params.get('steps', 30))
        cfg = float(params.get('cfg', params.get('guidance_scale', 6.0)))
        width = int(params.get('width', 1024))
        height = int(params.get('height', 1024))

        # --- seed / generator ---
        seed = resolve_seed(spec.get('seed', 'random'))
        gen = torch.Generator(device=device).manual_seed(seed)

        # --- optional VAE fix ---
        vae_id = spec.get('vae', {}).get('id') if isinstance(
            spec.get('vae'),
            dict
        ) else spec.get('vae')

        # --- resolve ControlNet inputs from DAG wiring ---
        cn_bundle = ControlNetBundle(
            self.controlnet.specs,
            dtype=dtype,
            device=device,
            input=input
        )
        ip_bundle = IpAdapterBundle(
            self.ip_adapter.specs,
            dtype=dtype,
            device=device,
            input=input
        )

        base = get_sdxl_base_pipe(
            model_path=model_path,
            device=device,
            dtype=dtype,
            vae_id=vae_id
        )

        # --- load pipeline (with or without controlnet) ---
        # Path A: try direct ControlNet pipeline from single file (if supported in your diffusers version)
        if cn_bundle.has_controlnet:
            pipe = StableDiffusionXLControlNetPipeline(
                **base.components,
                controlnet=cn_bundle.controlnet_arg
            )
        else:
            pipe = StableDiffusionXLPipeline(
                **base.components
            )

        if ip_bundle.has_ip_adapter:
            pipe.register_modules(image_encoder=ip_bundle.image_encoder)
            pipe.load_ip_adapter(
                ip_bundle.model_id_arg,
                subfolder=ip_bundle.subfolder_arg,
                weight_name=[ip_bundle.weight_names_arg]
            )
            pipe.set_ip_adapter_scale(ip_bundle.scale_arg)

        # --- measure time + memory ---
        if device.startswith('cuda'):
            torch.cuda.reset_peak_memory_stats()
            torch.cuda.synchronize()

        t0 = time.perf_counter()

        # --- call pipeline ---
        result = pipe(
            prompt=prompt,
            prompt_2=prompt_2,
            negative_prompt=negative_prompt,
            negative_prompt_2=negative_prompt_2,
            num_inference_steps=steps,
            guidance_scale=cfg,
            width=width,
            height=height,
            generator=gen,
            **({
                'image': cn_bundle.control_image_arg,
                'controlnet_conditioning_scale': cn_bundle.conditioning_scale_arg,
            } if cn_bundle.has_controlnet else {}),
            **({
                'ip_adapter_image': ip_bundle.ip_adapter_image,
            } if ip_bundle.has_ip_adapter else {})
        )

        if device.startswith('cuda'):
            torch.cuda.synchronize()

        dt_s = time.perf_counter() - t0
        img = result.images[0]

        # --- save image ---
        img_path = make_node_output_path(
            out_dir=out_dir,
            node_id=self.id,
            seed=seed
        )
        img.save(img_path)

        # --- memory stats ---
        mem = {}
        if device.startswith('cuda'):
            mem = {
                'allocated_gb': round(torch.cuda.memory_allocated() / 1024**3, 3),
                'reserved_gb': round(torch.cuda.memory_reserved() / 1024**3, 3),
                'peak_allocated_gb': round(torch.cuda.max_memory_allocated() / 1024**3, 3),
                'peak_reserved_gb': round(torch.cuda.max_memory_reserved() / 1024**3, 3),
            }

        out = {
            'ok': True,
            'node': 't2i',
            'id': self.id,
            'image': str(img_path),
            'seed': seed,
            'model': {
                'path': model_path,
                'dtype': str(dtype).replace('torch.', ''),
                'device': device,
            },
            'params': {
                'steps': steps,
                'guidance_scale': cfg,
                'width': width,
                'height': height,
            },
            'controlnet': [
                {
                    'key': cn.key,
                    'model_id': cn.model_id,
                    'conditioning_scale': cn.conditioning_scale,
                    'input_id': f'controlnet:{cn.key}',
                }
                for cn in self.controlnet.specs
            ],
            'ip-adapters': [
                {
                    'key': ipa.key,
                    'model_id': ipa.model_id,
                    'weight_name': ipa.weight_name,
                    'subfolder': ipa.subfolder,
                    'scale': ipa.scale,
                    'encoder_key': ipa.encoder_key,
                    'encoder_subfolder': ipa.encoder_subfolder,
                    'input_id': f'ip-adapter:{ipa.key}',
                }
                for ipa in self.ip_adapter.specs
            ],
            'timing': {'seconds': round(dt_s, 3)},
            'cuda_mem': mem,
        }

        meta_path = img_path.with_suffix('.json')
        meta_path.write_text(json.dumps(
            out, indent=2, ensure_ascii=False), encoding='utf-8')
        out['metadata'] = str(meta_path)

        return out
