from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

import torch

from morphalo.cache.models import (dtype_key, evict_flux2_klein_pipe,
                                   get_flux2_klein_pipe)
from morphalo.dag import AttachmentSink, NodeRef
from morphalo.nodes.common.config_resolve import (SpecInput, resolve_dtype,
                                                 resolve_seed, resolve_spec)
from morphalo.nodes.common.cuda_mem import (cleanup_torch_cuda,
                                            synchronize_torch_cuda)
from morphalo.nodes.common.cuda_stat import (cuda_mem_stats, cuda_prerun,
                                             cuda_sync)
from morphalo.nodes.common.device import is_cuda_device
from morphalo.nodes.common.io import save_image
from morphalo.nodes.foundation.wiring import ImageSequenceMixin
from morphalo.nodes.img import resolve_long_side_size
from morphalo.nodes.image_output import ImageOutputMixin
from morphalo.nodes.io import finalize_image_output
from morphalo.nodes.wiring.conditioning import apply_lora, cleanup_adapters
from morphalo.nodes.wiring.mixins import LoraMixin, PromptMixin
from morphalo.nodes.wiring.prompt import PromptBundle


DEFAULT_FLUX2_KLEIN_MODEL_ID = 'black-forest-labs/FLUX.2-klein-base-4B'


@dataclass(frozen=True)
class Config:
    model_id: str
    dtype: torch.dtype
    device: str
    cpu_offload: bool
    steps: int
    cfg: float
    height: Optional[int]
    width: Optional[int]
    long_side: Optional[int]
    seed: int


def _read_cfg(spec: Dict[str, Any], node_id: str) -> Config:
    model = spec.get('model', {}) if isinstance(spec, dict) else {}
    params = spec.get('params', {}) if isinstance(spec, dict) else {}

    height = params.get('height', None)
    if height is not None:
        height = int(height)

    width = params.get('width', None)
    if width is not None:
        width = int(width)

    long_side = params.get('long_side', None)
    if long_side is not None:
        long_side = int(long_side)

    seed_spec = spec.get('seed', 'random') if isinstance(spec, dict) else 'random'

    return Config(
        model_id=model.get('id', DEFAULT_FLUX2_KLEIN_MODEL_ID),
        dtype=resolve_dtype(model.get('dtype', 'bf16')),
        device=model.get('device', 'cuda'),
        cpu_offload=bool(model.get('cpu_offload', True)),
        steps=int(params.get('steps', 50)),
        cfg=float(params.get('cfg', params.get('guidance_scale', 4.0))),
        height=height,
        width=width,
        long_side=long_side,
        seed=resolve_seed(seed_spec),
    )


@dataclass
class Flux2Klein(
    ImageOutputMixin,
    ImageSequenceMixin,
    LoraMixin,
    PromptMixin,
    NodeRef,
):
    """
    FLUX.2 Klein unified text-to-image and image-editing node.

    This node runs the Diffusers ``Flux2KleinPipeline``. FLUX.2 Klein unifies
    text-to-image generation and image-conditioned editing in a single pipeline:
    with no image inputs, the node behaves as text-to-image; with one or more
    image inputs, the images are passed as ordered edit/reference inputs.

    The node defaults to ``'black-forest-labs/FLUX.2-klein-base-4B'``. Other
    Klein checkpoints, such as the 9B variants, may be selected explicitly via
    ``model.id`` when the local environment has enough memory and the license is
    appropriate for the workflow.

    Parameters
    ----------
    name : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : SpecInput, optional
        Node specification dictionary.

        ``model`` keys:

        - ``id`` : str, optional
          Hugging Face model identifier. Defaults to
          ``'black-forest-labs/FLUX.2-klein-base-4B'``.
        - ``dtype`` : str, optional
          Torch dtype used to load model weights. Defaults to ``'bf16'``.
        - ``device`` : str, optional
          Runtime device used for the pipeline and generator. Defaults to
          ``'cuda'``.
        - ``cpu_offload`` : bool, optional
          If true and ``device`` is CUDA, enable Diffusers model CPU offload
          instead of moving the whole pipeline onto the device. Defaults to
          ``True``.

        ``params`` keys:

        - ``steps`` : int, optional
          Number of inference steps. Defaults to ``50``, matching the public
          Diffusers example and BFL's recommendation for undistilled Klein Base
          checkpoints. Distilled Klein variants are designed for fewer steps,
          typically around ``4``.
        - ``cfg`` or ``guidance_scale`` : float, optional
          Text guidance scale passed to ``Flux2KleinPipeline`` as
          ``guidance_scale``. ``cfg`` takes precedence when both are provided.
          Defaults to ``4.0``, matching the public Diffusers example for
          ``FLUX.2-klein-base-4B``.
        - ``width`` : int, optional
          Output image width. If omitted, the pipeline default is used unless
          ``long_side`` is provided.
        - ``height`` : int, optional
          Output image height. If omitted, the pipeline default is used unless
          ``long_side`` is provided.
        - ``long_side`` : int, optional
          Resolve output width and height from the first input image while
          preserving its aspect ratio, matching the ``Img2Img`` convention.
          ``long_side`` takes precedence over ``width`` and ``height``. Supplying
          ``long_side`` without any input image is an error.

        ``seed`` : int or str, optional
            Random seed used for generation. Can be an integer or ``'random'``.
    evict_after_run : bool, default=False
        If ``True``, evict the cached FLUX.2 Klein pipeline used by this node
        after a successful execution and trigger best-effort Python/CUDA
        cleanup.

    Inputs
    ------
    default : dict, optional
        Optional primary image payload. Must contain ``'image'``, ``'images'``,
        or ``'path'``. If provided, its image(s) are placed first in the model
        image sequence.
    prompt:default : dict, optional
        Optional upstream prompt bundle. If provided, it overrides prompt fields
        from ``spec``.
    image:<idx> : dict, optional
        Additional image payload declared with an integer index via
        ``image.add(idx=...)``, ``image(idx)``, or ``condition(idx)``. These
        images are appended after the optional default image(s), ordered by
        ascending index.

    Outputs
    -------
    dict
        Primary output dictionary with a single generated image and a JSON
        sidecar. The sidecar includes resolved parameters, model information,
        input image metadata, optional LoRA metadata, timing information, and
        CUDA memory statistics.

    Notes
    -----
    - The ordered image sequence is passed directly to the pipeline ``image``
      argument: omitted for text-to-image, a single PIL image for one input, and
      a list of PIL images for multiple inputs.
    - For multi-image usage, prompts should identify reference roles explicitly,
      either by position (for example, "image 1") or by visible subject/object.
    - The pipeline is obtained via ``get_flux2_klein_pipe(...)`` to enable
      process-wide caching when running under a single-process DAG runner.
    - CUDA execution defaults to Diffusers model CPU offload. This follows the
      public Diffusers examples for FLUX.2 Klein and avoids requiring the full
      pipeline to reside on GPU at once.
    - LoRA adapters may be declared with ``node.lora.add(...)``. They are loaded
      through Diffusers ``load_lora_weights`` and activated with
      ``set_adapters``; SDXL-only ``cross_attention_kwargs`` are not passed.
    - On high-power desktop GPUs, running Klein at 1024px and 50 steps may be
      thermally loud even when it fits comfortably in memory. For long local
      sessions, it can be useful to set a temporary NVIDIA power limit outside
      Morphalo before running the DAG, for example
      ``sudo nvidia-smi -pl 400``. Restore the board default manually when
      desired, for example ``sudo nvidia-smi -pl 575`` on an RTX 5090 whose
      default limit is 575W. Always verify the actual default for the installed
      GPU with ``nvidia-smi -q -d POWER``.
    """

    spec: SpecInput = field(default_factory=dict)
    evict_after_run: bool = False

    @property
    def uses_cuda(self) -> bool:
        spec = resolve_spec(self.spec)
        cfg = _read_cfg(spec, node_id=self.id)
        return is_cuda_device(cfg.device)

    def condition(self, idx: int) -> AttachmentSink:
        """
        Declare an additional ordered reference image.
        """
        return self.image.add(idx=idx)

    def run(
        self,
        output_dir: str | Path,
        input: Optional[Dict[str, Dict]] = None,
    ) -> Dict[str, Any]:
        input = input or {}
        spec = resolve_spec(self.spec)

        image_bundle = self.build_image_sequence_bundle(input)
        images = image_bundle.images
        image_metadata = image_bundle.metadata

        pb = PromptBundle(spec=spec, input=input)
        prompt = pb.prompt
        if not prompt:
            raise ValueError('Flux2Klein requires a non-empty prompt.')

        cfg = _read_cfg(spec, node_id=self.id)
        gen = torch.Generator(device=cfg.device).manual_seed(cfg.seed)

        width = cfg.width
        height = cfg.height
        if cfg.long_side is not None:
            if not images:
                raise ValueError(
                    "Flux2Klein params 'long_side' requires at least one input image."
                )
            width, height = resolve_long_side_size(
                image=images[0],
                long_side=cfg.long_side,
                multiple=8,
            )

        pipe = get_flux2_klein_pipe(
            model_id=cfg.model_id,
            dtype=cfg.dtype,
            device=cfg.device,
            cpu_offload=cfg.cpu_offload,
        )
        lora_bundle = self.build_lora_bundle()

        stats_device = cfg.device if is_cuda_device(cfg.device) else 'cpu'
        cuda_prerun(stats_device)
        t0 = time.perf_counter()

        call_kwargs: Dict[str, Any] = {
            'prompt': prompt,
            'num_inference_steps': cfg.steps,
            'guidance_scale': cfg.cfg,
            'generator': gen,
        }

        if images:
            call_kwargs['image'] = images[0] if len(images) == 1 else images
        if width is not None:
            call_kwargs['width'] = width
        if height is not None:
            call_kwargs['height'] = height

        cleanup_adapters(pipe)
        apply_lora(lora_bundle=lora_bundle, pipe=pipe)

        result = pipe(**call_kwargs)

        cuda_sync(stats_device)
        dt_s = time.perf_counter() - t0

        img = result.images[0]
        img_path = save_image(
            output_dir,
            node_id=self.id,
            seed=cfg.seed,
            img=img,
        )
        mem = cuda_mem_stats(stats_device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_path,
            seed=cfg.seed,
            params={
                'steps': cfg.steps,
                'guidance_scale': cfg.cfg,
                'num_input_images': len(images),
                'input_images': image_metadata,
                **({} if height is None else {'height': height}),
                **({} if width is None else {'width': width}),
                **({} if cfg.long_side is None else {'long_side': cfg.long_side}),
            },
            dt_s=dt_s,
            cuda_mem=mem,
            lora_specs=self.lora.specs,
            model_info={
                'id': cfg.model_id,
                'device': cfg.device,
                'dtype': dtype_key(cfg.dtype),
                'cpu_offload': cfg.cpu_offload,
                'pipeline': 'Flux2KleinPipeline',
            },
        )

        return out

    def post_run(self) -> None:
        """
        Optional post-run cleanup hook.
        """
        if self.uses_cuda:
            synchronize_torch_cuda()

        if not self.evict_after_run:
            return

        try:
            spec = resolve_spec(self.spec)
            cfg = _read_cfg(spec, node_id=self.id)

            obj = evict_flux2_klein_pipe(
                model_id=cfg.model_id,
                dtype=cfg.dtype,
                device=cfg.device,
                cpu_offload=cfg.cpu_offload,
            )

            if obj is None:
                raise RuntimeError(
                    'Flux2Klein cache model not found for eviction: '
                    f'model_id={cfg.model_id!r}, '
                    f'device={cfg.device!r}, '
                    f'cpu_offload={cfg.cpu_offload!r}, '
                    f'dtype={cfg.dtype!r}'
                )

            del obj
        finally:
            cleanup_torch_cuda()
