import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

import torch

from morphalo.cache.models import evict_omnigen, get_omnigen
from morphalo.dag import NodeRef
from morphalo.nodes.common.config_resolve import (SpecInput, resolve_dtype,
                                                  resolve_seed, resolve_spec)
from morphalo.nodes.common.cuda_mem import (cleanup_torch_cuda,
                                            synchronize_torch_cuda)
from morphalo.nodes.common.cuda_stat import (cuda_mem_stats, cuda_prerun,
                                             cuda_sync)
from morphalo.nodes.common.device import is_cuda_device
from morphalo.nodes.common.env import setup_env
from morphalo.nodes.common.io import save_image
from morphalo.nodes.foundation.wiring import (OmniGenImageBundle,
                                              OmniGenImageRegistry)
from morphalo.nodes.io import finalize_image_output
from morphalo.nodes.wiring.mixins import PromptMixin
from morphalo.nodes.wiring.prompt import PromptBundle


class OmniGenImageMixin:
    """
    Adds `omnigen_image` registry to a node, enabling wiring like ControlNet.

    Usage:
        img_node >> omnigen.omnigen_image.add(key="ref")
    """
    image: OmniGenImageRegistry

    def __post_init__(self) -> None:
        self.image = OmniGenImageRegistry(owner=self)
        super().__post_init__()


@dataclass
class OmniGen(OmniGenImageMixin, PromptMixin, NodeRef):
    """
    OmniGen text-to-image / image-edit node with multimodal image inputs.

    This node runs an OmniGen pipeline to generate an image from a text prompt and,
    optionally, one or more *wired* reference images. Wired images are provided by
    upstream DAG nodes through typed sinks declared on this node (see Attributes).

    Prompt text may reference wired images using templated placeholders that are
    expanded at runtime:

    - ``{{img:<key>}}``
        Shorthand for the *first* image associated with ``<key>``.
        Equivalent to ``{{img:<key>[0]}}``.

        Use this form when a key is expected to receive a single image, or
        when only the first image is relevant.

    - ``{{img:<key>[idx]}}``
        Select the *idx-th* image (0-based) among the images associated with
        ``<key>``.

        Use this form when multiple images are wired to the same key and you
        need to explicitly reference a specific one.

        Examples:
        - ``{{img:ref[0]}}`` -> first reference image
        - ``{{img:ref[1]}}`` -> second reference image

    At execution time, all wired images are flattened into a single list
    (``input_images``) passed to OmniGen, and placeholders are expanded to OmniGen
    tokens of the form::

        <img><|image_N|></img>

    where ``N`` is the 1-based index in the flattened image list.

    Parameters
    ----------
    name : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : dict or str or pathlib.Path or sequence of (dict or str or pathlib.Path)
        Node configuration specification.

        The specification may be provided as an in-memory dictionary, as a path to a
        HOCON configuration file, or as a sequence of such elements. When a sequence
        is given, each element is resolved independently and merged from left to
        right, with later elements overriding earlier ones.

        The node resolves the spec with :func:`resolve_spec`. Expected keys include:

        **Model / runtime**
        - ``model.id`` : str, optional
            Model identifier for OmniGen (default: ``"Shitao/OmniGen-v1-diffusers"``).
        - ``model.device`` : str, optional
            Device to run on (default: ``"cuda"``).
        - ``model.dtype`` : str, optional
            DType name resolved by :func:`resolve_dtype` (default: ``"bf16"``).

        **Generation parameters** (under ``params``)
        - ``params.width`` : int, optional
            Output width (default: 1024).
        - ``params.height`` : int, optional
            Output height (default: 1024).
        - ``params.steps`` : int, optional
            Number of denoising steps (default: 30).
        - ``params.guidance_scale`` : float, optional
            Text guidance scale (default: 2.0).
        - ``params.img_guidance_scale`` : float
            Image guidance scale for multimodal conditioning (default: 1.6).
        - ``params.img_size_as_out`` : bool, optional
            If True, keep the output resolution equal to the input image size when
            performing image-editing (default: False). Passed to OmniGen as
            ``use_input_image_size_as_output``.

        **Randomness**
        - ``seed`` : int or str, optional
            Seed value or ``"random"`` (default: ``"random"``). Resolved by
            :func:`resolve_seed`.
            
    evict_after_run : bool, optional
        If ``True``, evict the cached OmniGen pipeline used by this node
        after a successful execution and trigger best-effort Python/CUDA
        memory cleanup.

        This is a runtime resource-management flag and does not affect the
        semantic output of the node. It is useful when running multiple
        heavyweight nodes in the same process and GPU memory must be
        reclaimed between executions.

        Default: ``False``.

    Attributes
    ----------
    op : str
        Operator identifier (e.g. ``"omnigen_txt2img"``).
    image : OmniGenImageRegistry
        Registry used to declare multimodal image inputs (via sinks), provided by
        ``OmniGenImageMixin``.
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by
        ``PromptMixin``.

    Inputs
    ------
    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Prompt resolution is performed by :class:`PromptBundle`.

    Additional typed image inputs may be attached via sinks declared on
    ``self.image``. Each sink uses an ``input_id`` of the form
    ``"omnigen:image:<key>"`` and expects the upstream output dictionary to contain:

    - ``image`` : str or list[str]
      Path (or list of paths) to image files.

    Outputs
    -------
    dict
        Primary output dictionary with at least:

        - ``ok`` : bool
        - ``node`` : str (e.g. ``"omnigen_txt2img"``)
        - ``id`` : str (node id)
        - ``image`` : str (path to the generated image)
        - ``metadata`` : str (path to a JSON sidecar with generation details)

        The metadata sidecar includes resolved parameters, model information, timing
        information, and (when running on CUDA) memory statistics.

    Notes
    -----
    - Hugging Face cache and environment variables are configured via ``setup_env()``
      prior to loading any pipeline components.
    - Prompt resolution is performed by :class:`PromptBundle`: if a prompt bundle is
      wired into ``prompt:default``, it takes precedence over the local ``spec``;
      otherwise the local ``spec`` is used.
    - Wired images are collected from DAG wiring through :class:`OmniGenImageRegistry`
      and resolved into a runtime :class:`OmniGenImageBundle`, which:
        (1) flattens images into ``input_images`` (preserving declaration order),
        (2) expands ``{{img:...}}`` placeholders into OmniGen tokens.
    - If images are wired but the prompt does not reference them via ``{{img:...}}``,
      the bundle may raise a validation error to prevent silent conditioning loss.
    - The OmniGen pipeline is obtained via ``get_omnigen(...)`` to enable process-wide
      caching when running under a single-process runner.
    - Outputs are written as an image file plus a JSON sidecar containing run metadata
      (parameters, model info, timing, and optional CUDA memory stats).
    - The OmniGen pipeline is obtained via ``get_omnigen(...)`` to enable process-wide
      caching when running under a single-process runner.
    - If ``evict_after_run`` is ``True``, the cached OmniGen pipeline corresponding
      to this node configuration is removed after execution via ``post_run()``,
      followed by best-effort Python/CUDA memory cleanup. 
    """

    spec: SpecInput = field(default_factory=dict)
    evict_after_run: bool = False

    @property
    def uses_cuda(self) -> bool:
        spec = resolve_spec(self.spec)
        return is_cuda_device(spec.get('model', {}).get('device', 'cuda'))

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        from diffusers.utils import load_image

        # --- HF env ---
        setup_env()

        spec = resolve_spec(self.spec)

        # --- resolve prompts (PromptBundle precedence like Txt2Img) ---
        prompt = PromptBundle(spec=spec, input=input).prompt

        # --- model / runtime ---
        model = spec.get('model', {}) if isinstance(spec, dict) else {}
        model_id = model.get('id', 'Shitao/OmniGen-v1-diffusers')

        device = model.get('device', 'cuda')
        dtype = resolve_dtype(model.get('dtype', 'bf16'))

        # --- params ---
        params = spec.get('params', {})
        height = int(params.get('height', 1024))
        width = int(params.get('width', 1024))
        steps = int(params.get('steps', 30))
        guidance_scale = float(params.get('guidance_scale', 2.0))
        img_guidance_scale = params.get('img_guidance_scale', 1.6)
        img_size_as_out = bool(params.get('img_size_as_out', False))

        # --- seed ---
        seed = resolve_seed(spec.get('seed', 'random'))
        # Generator: OmniGen example uses cpu generator; we keep that for safety.
        gen = torch.Generator(device='cpu').manual_seed(seed)

        # --- resolve wired images ---
        bundle = OmniGenImageBundle(self.image.specs, input=input)
        if bundle.flat_paths:
            # Replace {{img:key}} placeholders with <img><|image_N|></img>
            prompt = bundle.render_prompt(prompt)

            # Load PIL images in the exact flatten order
            input_images = [load_image(p) for p in bundle.flat_paths]
        else:
            input_images = None

        # --- load pipeline (cache-friendly in your runner; process-per-node will reload) ---
        pipe = get_omnigen(
            model_id=model_id,
            device=device,
            dtype=dtype
        )

        # --- run + stats ---
        cuda_prerun(device)
        t0 = time.perf_counter()

        result = pipe(
            prompt=prompt,
            height=height,
            width=width,
            input_images=input_images,
            num_inference_steps=steps,
            guidance_scale=guidance_scale,
            img_guidance_scale=img_guidance_scale,
            use_input_image_size_as_output=img_size_as_out,
            generator=gen,
        )

        cuda_sync(device)
        dt_s = time.perf_counter() - t0

        img = result.images[0]

        img_path = save_image(
            output_dir,
            node_id=self.id,
            seed=seed,
            img=img,
        )

        mem = cuda_mem_stats(device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_path,
            seed=seed,
            params={
                'height': height,
                'width': width,
                'steps': steps,
                'guidance_scale': guidance_scale,
                'img_guidance_scale': img_guidance_scale,
                'use_input_image_size_as_output': img_size_as_out,
            },
            dt_s=dt_s,
            cuda_mem=mem,
            model_info={
                'id': model_id,
                'device': device,
                'dtype': str(dtype).replace('torch.', ''),
            }
        )

        return out

    def post_run(self) -> None:
        """
        Optional post-run cleanup hook.

        Notes
        -----
        When ``evict_after_run`` is enabled, this hook removes the cached
        OmniGen pipeline corresponding to the resolved runtime configuration
        and then triggers best-effort Python/CUDA cleanup.
        """
        if self.uses_cuda:
            synchronize_torch_cuda()

        if not self.evict_after_run:
            return

        try:
            spec = resolve_spec(self.spec)

            model = spec.get('model', {}) if isinstance(spec, dict) else {}
            model_id = model.get('id', 'Shitao/OmniGen-v1-diffusers')
            device = model.get('device', 'cuda')
            dtype = resolve_dtype(model.get('dtype', 'bf16'))

            obj = evict_omnigen(
                model_id=model_id,
                device=device,
                dtype=dtype,
            )

            if obj is None:
                raise RuntimeError(
                    f'OmniGen cache model not found for eviction: '
                    f'model_id={model_id!r}, device={device!r}, '
                    f'dtype={dtype!r}'
                )

            del obj
        finally:
            cleanup_torch_cuda()
