import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

from PIL import Image

from morphalo.cache.models import (evict_qwen_image_edit_pipe,
                                   get_qwen_image_edit_pipe)
from morphalo.dag import NodeRef
from morphalo.nodes.common.config_resolve import SpecInput, resolve_spec
from morphalo.nodes.common.cuda_mem import (cleanup_torch_cuda,
                                            synchronize_torch_cuda)
from morphalo.nodes.common.cuda_stat import (cuda_mem_stats, cuda_prerun,
                                             cuda_sync)
from morphalo.nodes.common.env import setup_env
from morphalo.nodes.common.io import save_image
from morphalo.nodes.foundation.qwen_utils import (qwen_cpu_generator,
                                                 qwen_stats_device,
                                                 resolve_qwen_image_edit_params,
                                                 resolve_qwen_model_config,
                                                 resolve_qwen_seed)
from morphalo.nodes.io import finalize_image_output
from morphalo.nodes.wiring.mixins import PromptMixin
from morphalo.nodes.wiring.prompt import PromptBundle


@dataclass
class QwenImageEdit(PromptMixin, NodeRef):
    """
    Image editing node based on Qwen-Image-Edit.

    This node applies a natural-language editing instruction to an input image
    using the Qwen-Image-Edit Diffusers pipeline. Unlike traditional img2img
    diffusion, the input image is treated as a semantic reference rather than
    a strict geometric constraint: the model may change pose, viewpoint, or
    structure when explicitly or implicitly requested by the prompt.

    The node expects a single input image wired into the default input slot,
    following the same conventions as Img2Img nodes.

    Parameters
    ----------
    name : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : SpecInput, optional
        Node specification dictionary. Expected fields include:

        model : dict, optional
            Model configuration.

            - id : str, optional
                Hugging Face model identifier. Defaults to
                ``'Qwen/Qwen-Image-Edit'``.
            - dtype : str, optional
                Torch dtype used to load model weights (e.g. ``'bf16'``,
                ``'fp16'``). Defaults to ``'bf16'``.
            - device_map : {'balanced'}, optional
                Accelerate device map used for model dispatch. Defaults to
                ``'balanced'``. ``QwenImageEdit`` currently supports only
                ``'balanced'``. This mode lets Accelerate distribute pipeline
                components across available devices while balancing memory
                pressure, which helps run large Qwen models on domestic hardware
                with limited VRAM. The node always loads the model through
                ``device_map`` and does not call ``pipe.to(device)``.

        params : dict, optional
            Inference parameters.

            - steps : int, optional
                Number of inference steps. Defaults to 25.
            - true_cfg_scale : float, optional
                True classifier-free guidance scale controlling how strongly
                the textual instruction overrides the input image.
            - width : int, optional
                Output image width. If omitted, the input image width is used.
            - height : int, optional
                Output image height. If omitted, the input image height is used.

        seed : int or str, optional
            Random seed used for generation. Can be an integer or ``'random'``.
    evict_after_run : bool, optional
        If ``True``, evict the cached Qwen-Image-Edit pipeline used by this
        node after a successful execution and trigger best-effort Python/CUDA
        memory cleanup.

        This is a runtime resource-management flag and does not affect the
        semantic output of the node. It is useful when multiple heavyweight
        nodes are executed in the same process and GPU memory should be
        reclaimed between runs.

        Default: ``False``.

    Input
    -----
    default : dict
        Upstream image payload. Must contain either:

        - 'image' : str
            Path to the input image file.
        - 'path' : str
            Alternative key for the image path.

    Outputs
    -------
    dict
        Primary output dictionary.

        This node always produces a single image.

        - ``ok`` : bool
        - ``node`` : str (e.g. ``"qwen_image_edit"``)
        - ``id`` : str
        - ``image`` : str
            Path to the generated image.
        - ``seed`` : int
            Seed used for generation.
        - ``metadata`` : str
            Path to a JSON sidecar containing generation details.

        The metadata sidecar includes resolved parameters, model information,
        timing information, and (when running on CUDA) memory statistics.

    Notes
    -----
    - Editing is instruction-driven rather than noise-driven; parameters such
      as `strength` are not supported.
    - The primary control parameters are the textual prompt and `true_cfg_scale`.
    - If `width` and `height` are not provided, the output resolution defaults
      to the input image resolution.
    - The model may regenerate parts of the image beyond local pixel edits
      (e.g. changing pose or camera angle) when prompted.
    - The Qwen-Image-Edit pipeline is obtained via
      ``get_qwen_image_edit_pipe(...)`` to enable process-wide caching when
      running under a single-process runner.
    - The pipeline is dispatched using Accelerate ``device_map='balanced'``,
      rather than an explicit ``.to(device)`` call. This balances memory across
      available devices and is the supported path for limited-VRAM setups.
    - If ``evict_after_run`` is ``True``, the cached pipeline corresponding
      to this node configuration is removed after execution via ``post_run()``,
      followed by best-effort Python/CUDA memory cleanup.
    """

    spec: SpecInput = field(default_factory=dict)
    evict_after_run: bool = False

    def __post_init__(self) -> None:
        super().__post_init__()

    @property
    def uses_cuda(self) -> bool:
        return True

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        setup_env()

        input = input or {}

        init_up = input.get('default')
        if init_up is None:
            raise ValueError(
                'QwenImageEdit requires an init image wired into the default input (src >> qwen_edit).'
            )

        init_path = init_up.get('image') or init_up.get('path')
        if not init_path:
            raise ValueError(
                "Init image upstream output must contain 'image' (path).")

        init_image = Image.open(init_path).convert('RGB')

        spec = resolve_spec(self.spec)

        # prompt
        pb = PromptBundle(spec=spec, input=input)
        prompt = pb.prompt
        negative = pb.negative_prompt

        # model
        model_cfg = resolve_qwen_model_config(
            spec,
            default_model_id='Qwen/Qwen-Image-Edit',
            node_name='QwenImageEdit',
            supported_by='QwenImageEdit',
        )

        # params
        params = resolve_qwen_image_edit_params(spec)

        # seed / generator
        seed = resolve_qwen_seed(spec)
        gen = qwen_cpu_generator(seed)

        # pipeline
        pipe = get_qwen_image_edit_pipe(
            model_id=model_cfg.model_id,
            dtype=model_cfg.dtype,
            device_map=model_cfg.device_map,
        )

        # --- run + stats ---
        stats_device = qwen_stats_device()
        cuda_prerun(stats_device)
        t0 = time.perf_counter()

        call_kwargs = {
            'image': init_image,
            'prompt': prompt,
            'negative_prompt': negative or ' ',
            'num_inference_steps': params.steps,
            'generator': gen,
        }

        if params.true_cfg_scale is not None:
            call_kwargs['true_cfg_scale'] = params.true_cfg_scale
        if params.width is not None:
            call_kwargs['width'] = params.width
        if params.height is not None:
            call_kwargs['height'] = params.height

        result = pipe(**call_kwargs)

        cuda_sync(stats_device)
        dt_s = time.perf_counter() - t0

        img = result.images[0]

        img_path = save_image(output_dir, node_id=self.id, seed=seed, img=img)

        mem = cuda_mem_stats(stats_device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_path,
            seed=seed,
            params={
                'steps': params.steps,
                **({} if params.true_cfg_scale is None else {'true_cfg_scale': params.true_cfg_scale}),
                **({} if params.height is None else {'height': params.height}),
                **({} if params.width is None else {'width': params.width}),
            },
            dt_s=dt_s,
            cuda_mem=mem,
            model_info={
                'id': model_cfg.model_id,
                'device_map': model_cfg.device_map,
                'dtype': str(model_cfg.dtype).replace('torch.', ''),
            }
        )

        return out

    def post_run(self) -> None:
        """
        Optional post-run cleanup hook.

        Notes
        -----
        When ``evict_after_run`` is enabled, this hook removes the cached
        QwenImageEdit pipeline corresponding to the resolved runtime configuration
        and then triggers best-effort Python/CUDA cleanup.
        """
        if self.uses_cuda:
            synchronize_torch_cuda()

        if not self.evict_after_run:
            return

        try:
            spec = resolve_spec(self.spec)

            model_cfg = resolve_qwen_model_config(
                spec,
                default_model_id='Qwen/Qwen-Image-Edit',
                node_name='QwenImageEdit',
                supported_by='QwenImageEdit',
            )

            obj = evict_qwen_image_edit_pipe(
                model_id=model_cfg.model_id,
                device_map=model_cfg.device_map,
                dtype=model_cfg.dtype,
            )

            if obj is None:
                raise RuntimeError(
                    f'QwenImageEditiGen cache model not found for eviction: '
                    f'model_id={model_cfg.model_id!r}, '
                    f'device_map={model_cfg.device_map!r}, '
                    f'dtype={model_cfg.dtype!r}'
                )

            del obj
        finally:
            cleanup_torch_cuda()
