import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

import torch

from morphalo.cache.models import evict_qwen_image, get_qwen_image
from morphalo.dag import NodeRef
from morphalo.nodes.common.config_resolve import (SpecInput, resolve_dtype,
                                                  resolve_seed, resolve_spec)
from morphalo.nodes.common.cuda_mem import cleanup_torch_cuda
from morphalo.nodes.common.cuda_stat import (cuda_mem_stats, cuda_prerun,
                                             cuda_sync)
from morphalo.nodes.common.env import setup_env
from morphalo.nodes.common.io import save_image
from morphalo.nodes.io import finalize_image_output
from morphalo.nodes.wiring.mixins import PromptMixin
from morphalo.nodes.wiring.prompt import PromptBundle


@dataclass
class QwenImage(PromptMixin, NodeRef):
    """
    Qwen-Image text-to-image generation node.

    This node generates an image from a text prompt using the Qwen-Image family
    of diffusion-based foundation models via the Diffusers
    ``DiffusionPipeline`` interface. The pipeline is typically dispatched using
    an Accelerate ``device_map`` (e.g. ``"balanced"``) and cached process-wide.

    Prompt resolution follows the same precedence rules as ``Txt2Img``:
    prompts defined in the node specification may be overridden by an upstream
    prompt bundle attached through the prompt channel.

    Parameters
    ----------
    name : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : dict or str or pathlib.Path or sequence of (dict or str or pathlib.Path)
        Node configuration specification.

        The specification may be provided as an in-memory dictionary, as a path to a
        HOCON configuration file, or as a sequence of such elements. When a sequence
        is given, each element is resolved independently and merged from left to
        right, with later elements overriding earlier ones.

        The node resolves the specification using :func:`resolve_spec`.
        Expected keys include:

        **Model / runtime**
        - ``model.id`` : str, optional
            Model identifier for Qwen-Image
            (default: ``"Qwen/Qwen-Image"``).
        - ``model.dtype`` : str, optional
            DType name resolved by :func:`resolve_dtype`
            (default: ``"bf16"``).
        - ``model.device_map`` : str, optional
            Accelerate device map used to dispatch the model across available
            devices (default: ``"balanced"``).

        **Generation parameters** (under ``params``)
        - ``params.steps`` : int, optional
            Number of inference (denoising) steps
            (default: 25).
        - ``params.guidance_scale`` : float, optional
            Guidance scale controlling the strength of text conditioning.
            Passed directly to the pipeline when provided.
        - ``params.true_cfg_scale`` : float, optional
            Classifier-free guidance scale for models that distinguish between
            distilled guidance and true CFG. Passed through when provided.
        - ``params.width`` : int, optional
            Target output width, if supported by the underlying pipeline.
        - ``params.height`` : int, optional
            Target output height, if supported by the underlying pipeline.

        **Randomness**
        - ``seed`` : int or str, optional
            Seed value or ``"random"`` (default: ``"random"``). Resolved by
            :func:`resolve_seed`.
    evict_after_run : bool, optional
        If ``True``, evict the cached Qwen-Image pipeline used by this node
        after a successful execution and trigger best-effort Python/CUDA
        memory cleanup.

        This is a runtime resource-management flag and does not affect the
        semantic output of the node. It is useful when multiple heavyweight
        nodes are executed in the same process and GPU memory should be
        reclaimed between runs.

        Default: ``False``.

    Attributes
    ----------
    op : str
        Operator identifier (e.g. ``"qwen_image"``).
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by
        ``PromptMixin``.

    Inputs
    ------
    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields
        from ``spec``. Expected keys include ``prompt`` and
        ``negative_prompt``.

    Outputs
    -------
    dict
        Primary output dictionary.

        This node always produces a single image.

        - ``ok`` : bool
        - ``node`` : str (e.g. ``"qwen_image"``)
        - ``id`` : str
        - ``image`` : str
            Path to the generated image.
        - ``seed`` : int
            Seed used for generation.
        - ``metadata`` : str
            Path to a JSON sidecar with generation details.

        The metadata sidecar includes resolved parameters, model information,
        timing information, and (when CUDA devices are involved) memory statistics.

    Notes
    -----
    - Qwen-Image distinguishes between two guidance mechanisms:
        - **Classifier-free guidance (CFG)**, controlled by ``true_cfg_scale``, which
            is only enabled when a ``negative_prompt`` is explicitly provided.
            If ``true_cfg_scale`` is set but no ``negative_prompt`` is given, CFG is
            disabled by design and the parameter is ignored by the pipeline.
        - **Guidance-distilled scaling**, controlled by ``guidance_scale``, which is
            only applicable to guidance-distilled model variants. For non-distilled
            Qwen-Image models, ``guidance_scale`` is ignored.
        - As a consequence, providing ``guidance_scale`` alone (without
        ``true_cfg_scale`` and ``negative_prompt``) results in unguided or weakly
        guided generation, depending on the model defaults.
        - This behavior is intentional and reflects the design of the Qwen-Image
        pipelines. The node does not inject or infer a ``negative_prompt`` implicitly;
        users are expected to specify one explicitly when classifier-free guidance
        is desired.

    - Hugging Face cache and environment variables are configured via
      ``setup_env()`` prior to loading any pipeline components.
    - Prompt resolution is performed by :class:`PromptBundle`: if a prompt
      bundle is wired into ``prompt:default``, it takes precedence over the
      local ``spec``; otherwise the local ``spec`` is used.
    - The Qwen-Image pipeline is obtained via ``get_qwen_image(...)``, enabling
      process-wide caching and reuse when running under a single-process
      DAG runner.
    - The pipeline is typically dispatched using an Accelerate ``device_map``
      (e.g. ``"balanced"``), rather than an explicit ``.to(device)`` call.
    - Only parameters explicitly present in ``spec`` are forwarded to the
      pipeline, to avoid passing unsupported arguments to different Qwen-Image
      variants.
    - Outputs are written as an image file plus a JSON sidecar containing run
      metadata (parameters, model info, timing, and optional CUDA memory stats).
    - The Qwen-Image pipeline is obtained via
    ``get_qwen_image(...)`` to enable process-wide caching when
    running under a single-process runner.
    - If ``evict_after_run`` is ``True``, the cached pipeline corresponding
    to this node configuration is removed after execution via ``post_run()``,
    followed by best-effort Python/CUDA memory cleanup.
    """

    spec: SpecInput = field(default_factory=dict)
    evict_after_run: bool = False

    def run(
        self,
        output_dir: str | Path,
        input: Optional[Dict[str, Dict]] = None,
    ) -> Dict[str, Any]:
        # --- HF env ---
        setup_env()

        spec = resolve_spec(self.spec)

        # --- prompt bundle ---
        pb = PromptBundle(spec=spec, input=input)
        prompt = pb.prompt
        negative = pb.negative_prompt  # optional; some pipelines accept it

        # --- model settings ---
        model = spec.get('model', {}) if isinstance(spec, dict) else {}
        model_id = model.get('id', 'Qwen/Qwen-Image')
        dtype = resolve_dtype(model.get('dtype', 'bf16'))
        device_map = model.get('device_map', 'balanced')

        # --- params ---
        params = spec.get('params', {}) if isinstance(spec, dict) else {}
        steps = int(params.get('steps', 25))

        guidance_scale = params.get('guidance_scale', None)
        if guidance_scale is not None:
            guidance_scale = float(guidance_scale)

        true_cfg_scale = params.get('true_cfg_scale', None)
        if true_cfg_scale is not None:
            true_cfg_scale = float(true_cfg_scale)

        # optional size (only pass if explicitly set; avoids breaking pipelines)
        height = params.get('height', None)
        width = params.get('width', None)
        if height is not None:
            height = int(height)
        if width is not None:
            width = int(width)

        # --- seed / generator ---
        seed = resolve_seed(spec.get('seed', 'random'))
        gen = torch.Generator(device='cpu').manual_seed(seed)

        # --- load cached pipeline ---
        pipe = get_qwen_image(
            model_id=model_id,
            dtype=dtype,
            device_map=device_map,
        )

        # --- run + stats ---
        # cuda_prerun expects a string device; with device_map it’s still useful if CUDA is involved.
        # We'll treat 'balanced'/'auto' as 'cuda' for stats, since modules may be on GPU.
        stats_device = 'cuda' if str(device_map) in (
            'balanced', 'auto', 'cuda'
        ) else 'cpu'
        cuda_prerun(stats_device)

        t0 = time.perf_counter()

        call_kwargs: Dict[str, Any] = dict(
            prompt=prompt,
            num_inference_steps=steps,
            generator=gen,
        )

        # Optional args (only pass when set / non-empty)
        if negative:
            call_kwargs['negative_prompt'] = negative
        if guidance_scale is not None:
            call_kwargs['guidance_scale'] = guidance_scale
        if true_cfg_scale is not None:
            call_kwargs['true_cfg_scale'] = true_cfg_scale
        if height is not None:
            call_kwargs['height'] = height
        if width is not None:
            call_kwargs['width'] = width

        result = pipe(**call_kwargs)

        cuda_sync(stats_device)
        dt_s = time.perf_counter() - t0

        img = result.images[0]

        img_path = save_image(
            output_dir,
            node_id=self.id,
            seed=seed,
            img=img,
        )

        mem = cuda_mem_stats(stats_device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_path,
            seed=seed,
            params={
                'steps': steps,
                **({} if guidance_scale is None else {'guidance_scale': guidance_scale}),
                **({} if true_cfg_scale is None else {'true_cfg_scale': true_cfg_scale}),
                **({} if height is None else {'height': height}),
                **({} if width is None else {'width': width}),
            },
            dt_s=dt_s,
            cuda_mem=mem,
            model_info={
                'id': model_id,
                'device_map': device_map,
                'dtype': str(dtype).replace('torch.', ''),
            },
        )

        return out

    def post_run(self) -> None:
        """
        Optional post-run cleanup hook.

        Notes
        -----
        When ``evict_after_run`` is enabled, this hook removes the cached
        QwenImage pipeline corresponding to the resolved runtime configuration
        and then triggers best-effort Python/CUDA cleanup.
        """
        if not self.evict_after_run:
            return

        spec = resolve_spec(self.spec)

        model = spec.get('model', {}) if isinstance(spec, dict) else {}
        model_id = model.get('id', 'Qwen/Qwen-Image')
        dtype = resolve_dtype(model.get('dtype', 'bf16'))
        device_map = model.get('device_map', 'balanced')

        obj = evict_qwen_image(
            model_id=model_id,
            device_map=device_map,
            dtype=dtype,
        )

        if obj is None:
            raise RuntimeError(
                f'QwenImage cache model not found for eviction: '
                f'model_id={model_id!r}, device_map={device_map!r}, dtype={dtype!r}'
            )

        del obj

        cleanup_torch_cuda()
