from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

from morphalo.cache.models import (dtype_key, evict_qwen_image_edit_plus_pipe,
                                   get_qwen_image_edit_plus_pipe)
from morphalo.dag import AttachmentSink, NodeRef
from morphalo.nodes.common.config_resolve import SpecInput, resolve_spec
from morphalo.nodes.common.cuda_mem import (cleanup_torch_cuda,
                                            synchronize_torch_cuda)
from morphalo.nodes.common.cuda_stat import (cuda_mem_stats, cuda_prerun,
                                             cuda_sync)
from morphalo.nodes.common.io import save_image
from morphalo.nodes.foundation.qwen_utils import (qwen_cpu_generator,
                                                 qwen_stats_device,
                                                 resolve_qwen_image_edit_plus_params,
                                                 resolve_qwen_model_config,
                                                 resolve_qwen_seed)
from morphalo.nodes.foundation.wiring import ImageSequenceMixin
from morphalo.nodes.image_output import ImageOutputMixin
from morphalo.nodes.io import finalize_image_output
from morphalo.nodes.wiring.conditioning import apply_lora, cleanup_adapters
from morphalo.nodes.wiring.mixins import LoraMixin, PromptMixin
from morphalo.nodes.wiring.prompt import PromptBundle


DEFAULT_QWEN_IMAGE_EDIT_PLUS_MODEL_ID = 'Qwen/Qwen-Image-Edit-2511'


@dataclass
class QwenImageEditPlus(
    ImageOutputMixin,
    ImageSequenceMixin,
    LoraMixin,
    PromptMixin,
    NodeRef,
):
    """
    Image editing node based on Qwen-Image-Edit Plus models.

    This node applies an instruction-driven image edit using the Diffusers
    ``QwenImageEditPlusPipeline``. It is intended as the updated counterpart of
    ``QwenImageEdit`` and defaults to ``'Qwen/Qwen-Image-Edit-2511'``.

    Unlike the older single-image node, this node supports one or more input
    images. The optional default input, when present, contributes the first
    image(s). Additional wired images follow in ascending integer index order.
    Images may be ordinary references or control-like maps such as edge maps,
    depth maps, keypoint maps, or sketches. Their role is not typed at the API
    level. Because the underlying multi-image model is trained through image
    concatenation, prompts should describe visible subjects, objects, and roles
    rather than relying only on phrases such as "the first image" or "the second
    image".

    Parameters
    ----------
    name : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : SpecInput, optional
        Node specification dictionary.

        ``model`` keys:

        - ``id`` : str, optional
          Hugging Face model identifier. Defaults to
          ``'Qwen/Qwen-Image-Edit-2511'``.

          Currently relevant Qwen Image Edit Plus checkpoints:
          - ``'Qwen/Qwen-Image-Edit-2511'``: current default, newer model with
            improved consistency and editing capabilities.
          - ``'Qwen/Qwen-Image-Edit-2509'``: previous model, useful for
            reproducibility or comparison with older runs.
        - ``dtype`` : str, optional
          Torch dtype used to load model weights. Defaults to ``'bf16'``.
        - ``device_map`` : {'balanced'}, optional
          Accelerate device map used to dispatch the model. Defaults to ``'balanced'``.
          ``QwenImageEditPlusPipeline`` currently supports only ``'balanced'``.
          This mode lets Accelerate distribute pipeline components across available
          devices while balancing memory pressure, which helps run large Qwen
          models on domestic hardware with limited VRAM. The node always loads the
          model through ``device_map`` and does not call ``pipe.to(device)``.

        ``params`` keys:

        - ``steps`` : int, optional
          Number of inference steps. Defaults to ``40``.
        - ``true_cfg_scale`` : float, optional
          True classifier-free guidance scale. Defaults to ``4.0``.
          ``guidance_scale`` is intentionally not exposed here for now; it may
          be revisited if Morphalo adds support for guidance-distilled Qwen edit
          variants.
        - ``width`` : int, optional
          Output image width. If omitted, the pipeline default is used.
        - ``height`` : int, optional
          Output image height. If omitted, the pipeline default is used.
        - ``max_images`` : int or null, optional
          Optional maximum number of input images allowed by this node. If
          omitted, no local limit is enforced.

        ``seed`` : int or str, optional
            Random seed used for generation. Can be an integer or ``'random'``.
    evict_after_run : bool, default=False
        If ``True``, evict the cached Qwen Image Edit Plus pipeline used by this
        node after a successful execution and trigger best-effort Python/CUDA
        cleanup.

    Inputs
    ------
    default : dict, optional
        Optional primary image payload. Must contain ``'image'``, ``'images'``,
        or ``'path'``. If provided, its image(s) are placed first in the model
        image sequence. At least one image must be provided through ``default``
        or through registry-declared ``image:<idx>`` inputs.
    prompt:default : dict, optional
        Optional upstream prompt bundle. If provided, it overrides prompt fields
        from ``spec``.
    image:<idx> : dict, optional
        Additional image payload declared with an integer index via
        ``image.add(idx=...)``, ``image(idx)``, or ``condition(idx)``. These
        images are appended after the optional default image(s), ordered by
        ascending index. This order controls the image sequence passed to the
        pipeline, but prompts are usually more reliable when they identify the
        relevant subject or object in each source instead of referring only to
        image positions.

    Outputs
    -------
    dict
        Primary output dictionary with a single generated image and a JSON
        sidecar. The sidecar includes resolved parameters, model information,
        input image metadata, optional LoRA metadata, timing information, and
        CUDA memory statistics.

    Notes
    -----
    - Editing is instruction-driven rather than noise-driven; parameters such as
      ``strength`` are not supported.
    - For multi-image usage, the prompt should explicitly identify image roles
      by visible subject or object, for example:
      ``'Place the woman in the red coat in the city street scene, preserving
      the street perspective.'`` or ``'Use the pose skeleton as a keypoint
      control map for the dancer.'``.
    - The model card currently indicates that best multi-image performance is
      typically obtained with one to three input images. This node does not
      enforce that limit unless ``params.max_images`` is set.
    - The Qwen Image Edit Plus pipeline is obtained via
      ``get_qwen_image_edit_plus_pipe(...)`` to enable process-wide caching.
    - The pipeline is dispatched using Accelerate ``device_map='balanced'``,
      rather than an explicit ``.to(device)`` call. This balances memory across
      available devices and is the supported path for limited-VRAM setups.
    - LoRA adapters may be declared with ``node.lora.add(...)``. Qwen Image
      LoRAs are loaded via Diffusers ``load_lora_weights`` and activated via
      ``set_adapters``; SDXL-only ``cross_attention_kwargs`` are not passed.
    """

    spec: SpecInput = field(default_factory=dict)
    evict_after_run: bool = False

    @property
    def uses_cuda(self) -> bool:
        return True

    def condition(self, idx: int) -> AttachmentSink:
        """
        Declare an additional condition/reference image for the Qwen input sequence.

        This method is a semantic alias for ``self.image.add(idx=idx)``. It exposes
        an indexed image input that is appended to the ordered image sequence passed
        to ``QwenImageEditPlusPipeline``.

        The input sequence is built as follows:

        1. image(s) received from the optional ``default`` input, in payload order;
        2. image(s) received from indexed condition inputs, sorted by ascending
        ``idx``.

        Qwen Image Edit Plus does not receive typed condition channels through this
        method. All additional inputs are passed as ordinary images in the pipeline
        ``image`` argument. Their role must therefore be described explicitly in the
        prompt, for example:

        ``'Use the portrait person as the facial identity reference for the
        subject in the wide scene.'`` or ``'Use the pose skeleton as a keypoint
        control map for the dancer.'``

        Parameters
        ----------
        idx : int
            Ordering index for this condition image. The value is not a semantic
            condition type; it only controls the relative position of this input
            among the registry-declared images.

            Indexes must be unique within the node image registry. Lower indexes
            appear earlier in the image sequence after the optional ``default``
            image(s).

        Returns
        -------
        AttachmentSink
            A sink bound to this node with input id ``'image:<idx>'``. Wire an
            upstream image-producing node into this sink using the ``>>`` operator.

        Notes
        -----
        - The upstream payload must provide one of ``'image'``, ``'images'``, or
          ``'path'``.
        - A single upstream payload may provide multiple images via ``'images'``;
          these are inserted at the position associated with ``idx`` while
          preserving their payload order.
        - This method is intentionally only an alias: it does not validate whether
          the input is an edge map, depth map, keypoint map, sketch, reference image,
          or ordinary image.
        - Because Qwen prompts refer to images by position, changing ``idx`` values
          can change the meaning of prompts such as "the second image" or "the third
          image".
        """
        return self.image.add(idx=idx)

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        input = input or {}
        spec = resolve_spec(self.spec)

        image_bundle = self.build_image_sequence_bundle(input)
        images = image_bundle.images
        image_metadata = image_bundle.metadata

        # Prompt
        pb = PromptBundle(spec=spec, input=input)
        prompt = pb.prompt
        negative = pb.negative_prompt
        if not prompt:
            raise ValueError('QwenImageEditPlus requires a non-empty prompt.')

        # Model
        model_cfg = resolve_qwen_model_config(
            spec,
            default_model_id=DEFAULT_QWEN_IMAGE_EDIT_PLUS_MODEL_ID,
            node_name='QwenImageEditPlus',
            supported_by='QwenImageEditPlusPipeline',
        )

        # Params
        params = resolve_qwen_image_edit_plus_params(spec)
        if params.max_images is not None and len(images) > params.max_images:
            raise ValueError(
                f'QwenImageEditPlus received {len(images)} image(s), '
                f'but params.max_images={params.max_images}.'
            )

        # Seed / generator
        seed = resolve_qwen_seed(spec)
        gen = qwen_cpu_generator(seed)

        # Pipeline
        pipe = get_qwen_image_edit_plus_pipe(
            model_id=model_cfg.model_id,
            dtype=model_cfg.dtype,
            device_map=model_cfg.device_map,
        )
        lora_bundle = self.build_lora_bundle()

        stats_device = qwen_stats_device()
        cuda_prerun(stats_device)
        t0 = time.perf_counter()

        call_kwargs: Dict[str, Any] = {
            'image': images[0] if len(images) == 1 else images,
            'prompt': prompt,
            'negative_prompt': negative or ' ',
            'num_inference_steps': params.steps,
            'true_cfg_scale': params.true_cfg_scale,
            'num_images_per_prompt': 1,
            'generator': gen,
        }

        if params.width is not None:
            call_kwargs['width'] = params.width
        if params.height is not None:
            call_kwargs['height'] = params.height

        cleanup_adapters(pipe)
        apply_lora(lora_bundle=lora_bundle, pipe=pipe)

        result = pipe(**call_kwargs)

        cuda_sync(stats_device)
        dt_s = time.perf_counter() - t0

        img = result.images[0]
        img_path = save_image(output_dir, node_id=self.id, seed=seed, img=img)
        mem = cuda_mem_stats(stats_device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_path,
            seed=seed,
            params={
                'steps': params.steps,
                'true_cfg_scale': params.true_cfg_scale,
                'num_input_images': len(images),
                'input_images': image_metadata,
                **({} if params.height is None else {'height': params.height}),
                **({} if params.width is None else {'width': params.width}),
                **({} if params.max_images is None else {'max_images': params.max_images}),
            },
            dt_s=dt_s,
            cuda_mem=mem,
            lora_specs=self.lora.specs,
            model_info={
                'id': model_cfg.model_id,
                'device_map': model_cfg.device_map,
                'dtype': dtype_key(model_cfg.dtype),
                'pipeline': 'QwenImageEditPlusPipeline',
            },
        )

        return out

    def post_run(self) -> None:
        """
        Optional post-run cleanup hook.

        Notes
        -----
        When ``evict_after_run`` is enabled, this hook removes the cached
        Qwen Image Edit Plus pipeline corresponding to the resolved runtime
        configuration and then triggers best-effort Python/CUDA cleanup.
        """
        if self.uses_cuda:
            synchronize_torch_cuda()

        if not self.evict_after_run:
            return

        try:
            spec = resolve_spec(self.spec)
            model_cfg = resolve_qwen_model_config(
                spec,
                default_model_id=DEFAULT_QWEN_IMAGE_EDIT_PLUS_MODEL_ID,
                node_name='QwenImageEditPlus',
                supported_by='QwenImageEditPlusPipeline',
            )

            obj = evict_qwen_image_edit_plus_pipe(
                model_id=model_cfg.model_id,
                dtype=model_cfg.dtype,
                device_map=model_cfg.device_map,
            )

            if obj is None:
                raise RuntimeError(
                    'QwenImageEditPlus cache model not found for eviction: '
                    f'model_id={model_cfg.model_id!r}, '
                    f'device_map={model_cfg.device_map!r}, '
                    f'dtype={model_cfg.dtype!r}'
                )

            del obj
        finally:
            cleanup_torch_cuda()
