from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from morphalo.dag import NodeRef


@dataclass
class LoraSpec:
    """
    Declarative specification for a LoRA adapter.

    A ``LoraSpec`` stores the information needed to load one LoRA checkpoint
    into a Diffusers pipeline and register it under a stable adapter name.

    Attributes
    ----------
    key : str
        Stable framework-level identifier for this LoRA declaration.
        If not provided by the caller, it is generated by
        :class:`LoraRegistry` as ``lora1``, ``lora2``, ...
    model_id : str
        Hugging Face repository identifier or local path passed to
        ``pipe.load_lora_weights(...)``.
    weight_name : str or None
        Optional LoRA weight filename inside ``model_id``, commonly a
        ``.safetensors`` file. When omitted, Diffusers resolves the default
        LoRA weights for the repository/path.
    adapter_name : str
        Name under which Diffusers registers the loaded adapter. This is the
        name later passed to ``pipe.set_adapters(...)``.
    adapter_weight : float
        Relative adapter weight passed to ``pipe.set_adapters``. When multiple
        LoRAs are active, these values control their blend.
    """

    key: str
    model_id: str
    weight_name: Optional[str]
    adapter_name: str
    adapter_weight: float


class LoraRegistry:
    """
    Declarative registry for LoRA adapters on a DAG node.

    This registry lets a :class:`~morphalo.dag.NodeRef` declare one or more
    LoRA adapters without introducing additional DAG inputs. Unlike ControlNet
    or IP-Adapter, a standard LoRA does not consume an upstream image, video,
    mask, or conditioning payload; it is a model-side adapter loaded directly
    into the pipeline before inference.

    The registry itself is purely declarative:
    it does not load weights, mutate a pipeline, validate remote files, or
    execute inference. It records enough information for the execution phase to:
    - load each LoRA checkpoint via ``pipe.load_lora_weights(...)``;
    - activate the loaded adapters via ``pipe.set_adapters(...)``;
    - preserve declaration order so adapter names and weights stay aligned.

    Notes
    -----
    - LoRA declarations are ordered. Runtime loading and ``set_adapters`` use
      the same order in which :meth:`add` was called.
    - The registry is backend-neutral except for ``cross_attention_scale``,
      which is consumed only by Stable Diffusion style pipelines that accept
      LoRA scaling through ``cross_attention_kwargs``.
    """

    def __init__(self, owner: NodeRef):
        self._owner = owner
        self._counter = 0
        self._specs: List[LoraSpec] = []
        self._cross_attention_scale = 1.0

    def add(
        self,
        model_id: str,
        *,
        weight_name: Optional[str] = None,
        adapter_name: Optional[str] = None,
        adapter_weight: float = 1.0,
        key: Optional[str] = None,
    ) -> LoraSpec:
        """
        Declare a LoRA adapter for the owning node.

        This method appends a LoRA specification to the registry and returns the
        created :class:`LoraSpec`. No DAG edge is created because LoRA adapters
        do not consume upstream node outputs.

        Parameters
        ----------
        model_id : str
            Hugging Face repository identifier or local path for the LoRA
            weights. Passed as the first argument to
            ``pipe.load_lora_weights(...)``.
        weight_name : str, optional
            Optional LoRA weight filename inside ``model_id``, commonly a
            ``.safetensors`` file. This is forwarded to Diffusers as
            ``weight_name`` when provided.
        adapter_name : str, optional
            Name used by Diffusers to register the adapter. If omitted, the
            generated framework ``key`` is reused as the adapter name.
        adapter_weight : float, optional
            Relative adapter weight passed to
            ``pipe.set_adapters(..., adapter_weights=[...])``. Defaults to
            ``1.0``.
        key : str, optional
            Stable framework-level identifier for this LoRA declaration. If not
            provided, an incremental key is generated (``lora1``, ``lora2``,
            ...).

        Returns
        -------
        LoraSpec
            The recorded LoRA declaration.

        Notes
        -----
        - ``adapter_weight`` controls the relative contribution of individual
          adapters in ``set_adapters``.
        - For Stable Diffusion pipelines, :meth:`set_scale` configures the
          separate call-time LoRA multiplier passed through
          ``cross_attention_kwargs``.
        """
        if key is None:
            self._counter += 1
            key = f'lora{self._counter}'

        if adapter_name is None:
            adapter_name = key

        spec = LoraSpec(
            key=key,
            model_id=model_id,
            weight_name=weight_name,
            adapter_name=adapter_name,
            adapter_weight=float(adapter_weight),
        )
        self._specs.append(spec)
        return spec

    def set_scale(self, scale: float) -> None:
        """
        Set the Stable Diffusion call-time LoRA scale.

        This value is used only for Stable Diffusion style Diffusers pipelines
        that accept LoRA scaling through ``cross_attention_kwargs={'scale': ...}``
        during the pipeline call. It is intentionally ignored by Qwen Image
        pipelines, which use the same ``load_lora_weights`` / ``set_adapters``
        adapter interface but do not use Stable Diffusion cross-attention kwargs
        for LoRA strength.

        Parameters
        ----------
        scale : float
            Global call-time LoRA multiplier for supported Stable Diffusion
            pipelines. Defaults to ``1.0`` when not explicitly set.

        Notes
        -----
        This is distinct from ``adapter_weight`` on each LoRA:
        ``adapter_weight`` controls the relative blend between adapters, while
        ``scale`` controls the overall applied LoRA strength for compatible
        Stable Diffusion pipelines.
        """
        self._cross_attention_scale = float(scale)

    @property
    def specs(self) -> List[LoraSpec]:
        """
        Ordered list of LoRA declarations for the owning node.
        """
        return self._specs

    @property
    def cross_attention_scale(self) -> float:
        """
        Stable Diffusion call-time LoRA scale recorded by :meth:`set_scale`.
        """
        return self._cross_attention_scale


class LoraBundle:
    """
    Runtime bundle for LoRA declarations.

    ``LoraBundle`` is the execution-time counterpart of
    :class:`LoraRegistry`. It normalizes an optional list of declarations and
    exposes the concrete argument lists expected by Diffusers adapter APIs.

    The bundle does not mutate pipelines directly. Pipeline mutation is handled
    by ``morphalo.nodes.wiring.conditioning.apply_lora``.
    """

    def __init__(
        self,
        loras: Optional[List[LoraSpec]],
        *,
        cross_attention_scale: float = 1.0,
    ):
        self._loras = list(loras or [])
        self._cross_attention_scale = float(cross_attention_scale)

    @property
    def has_lora(self) -> bool:
        """
        Whether at least one LoRA adapter is active for the node.
        """
        return bool(self._loras)

    @property
    def specs(self) -> List[LoraSpec]:
        """
        Ordered LoRA specifications represented by this bundle.
        """
        return self._loras

    @property
    def adapter_names_arg(self) -> List[str]:
        """
        Adapter names passed to ``pipe.set_adapters(...)``.
        """
        return [lora.adapter_name for lora in self._loras]

    @property
    def adapter_weights_arg(self) -> List[float]:
        """
        Adapter weights passed to ``pipe.set_adapters(..., adapter_weights=...)``.
        """
        return [lora.adapter_weight for lora in self._loras]

    @property
    def cross_attention_scale(self) -> float:
        """
        Stable Diffusion call-time LoRA scale for compatible pipelines.
        """
        return self._cross_attention_scale
