import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional, Union

from stability.cache.ltx_models import (get_ltx_condition,
                                        get_ltx_latent_upsample)
from stability.core.config import *
from stability.dag import NodeRef
from stability.nodes import *
from stability.nodes.ltx.ltx_common import *
from stability.nodes.sdxl_common import PromptMixin, setup_env


@dataclass
class Img2Video(PromptMixin, NodeRef):
    """
    Image-to-video node based on LTX-Video (single-keyframe conditioning).

    This node generates a short video clip from a single input image (keyframe)
    using the LTX-Video diffusion model. The input image is provided via the
    default DAG connection (``src >> img2video``) and is converted into a
    one-frame LTX condition (``LTXVideoCondition``). The condition is then passed
    through the pipeline using the native ``conditions=[...]`` mechanism.

    Video content is produced through a multi-stage process that first generates
    a low-resolution latent video and then refines it into a final high-resolution
    sequence.

    Prompts are resolved from the node configuration and may optionally be
    overridden by an upstream prompt bundle attached through the prompt channel.

    The node produces a single primary output dictionary containing at least:
    - ``video``: filesystem path to the generated MP4 video
    - ``metadata``: filesystem path to a JSON sidecar with generation details

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    spec : dict | str | pathlib.Path
        Configuration describing the model, prompts, and image-to-video parameters.
        The value may be a mapping (already-parsed spec) or a path reference
        (string/path) that is resolved by ``resolve_ltx_common``.

        Typical keys include:

        - ``model``: model identifiers and runtime options
        - ``prompt``: text prompt describing the desired video
        - ``negative_prompt``: optional negative prompt
        - ``seed``: random seed (or ``'random'``)
        - ``params``:
            - ``width`` / ``height``: target output resolution
            - ``fps``: frames per second
            - ``num_frames``: total number of frames
            - ``steps_main``: diffusion steps for latent generation
            - ``steps_refine``: diffusion steps for refinement
            - ``denoise_strength``: refinement denoise strength
            - ``guidance_scale`` / ``guidance_rescale``: classifier-free guidance parameters
            - ``downscale_factor``: spatial downscaling factor for latent generation
            - ``upscale_latent_factor``: latent upscaling factor (latent upsampler stage)
            - ``decode_timestep`` / ``decode_noise_scale``: decode-time noise controls
            - ``image_cond_noise_scale``: noise applied to the image conditioning signal
            - ``max_sequence_length``: tokenizer sequence length cap for prompts
            - ``frame_index``: index used by ``LTXVideoCondition`` to anchor the image
              conditioning in the generated sequence (default 0)

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class
        name (e.g. ``'img2video'``).
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by ``PromptMixin``.

    Inputs
    ------
    default : dict
        Required upstream output mapping that must contain the input image path.
        The node expects either:

        - ``image`` : str
            Filesystem path to the input keyframe image.
        - ``path`` : str
            Alternative key for the filesystem path.

    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Expected keys include ``prompt`` and ``negative_prompt`` (and
        optionally ``prompt_2`` / ``negative_prompt_2`` if your PromptBundle supports them).

    Outputs
    -------
    dict
        Primary output dictionary with at least:

        - ``ok`` : bool
        - ``node`` : str (typically ``'img2video'``)
        - ``id`` : str (node id)
        - ``video`` : str (path to the generated MP4)
        - ``metadata`` : str (path to a JSON sidecar with generation details)

        The metadata sidecar includes resolved parameters, model information,
        timing information, and (when running on CUDA) memory statistics.

    Notes
    -----
    - Hugging Face cache/environment variables are configured via ``setup_env()``
      prior to loading any pipeline components.
    - The node executes in three conceptual stages:
        1. Latent video generation at reduced resolution (``steps_main``)
        2. Latent upsampling (latent upsampler)
        3. Short refinement pass to produce the final video (``steps_refine``)
      A final resizing step ensures the output frames match exactly
      ``params.width``/``params.height``.

    - Image conditioning is implemented by converting the input image to a one-frame
      video and wrapping it into an ``LTXVideoCondition``. The condition is then
      passed using ``conditions=[condition]`` in both the latent generation stage
      and the refinement stage.

    - This node intentionally does NOT support IC-LoRA at the moment (by design),
      as mixing multiple conditioning mechanisms can introduce fragile interactions.
      Structural or motion guidance beyond the keyframe should be implemented as a
      separate node (or reintroduced later with explicit validation and tests).

    - The output video is written using ``export_to_video`` and is intended for
      preview/inference usage. If you need lossless control artifacts, consider
      exporting individual frames (PNG) instead.
    """

    spec: Union[Dict[str, Any], str, Path] = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # HF env
        setup_env()

        spec, device, dtype, model_id, upscaler_id, guidance_scale, \
            guidance_rescale, height, width, fps, num_frames, steps_main, \
            steps_refine, denoise_strength, downscale_factor, upscale_factor, \
            decode_timestep, decode_noise_scale, image_cond_noise_scale, \
            max_sequence_length, seed, gen = resolve_ltx_common(
                self.spec)  # :contentReference[oaicite:3]{index=3}

        input = input or {}
        init_up = input.get('default')
        if init_up is None:
            raise ValueError(
                'Img2Video requires an init image wired into the default input (src >> img2video).'
            )

        init_path = init_up.get('image') or init_up.get('path')
        if not init_path:
            raise ValueError("Upstream output must contain 'image' (path).")

        # Img2Video-only param (belongs to LTXVideoCondition)
        params = spec.get('params', {})
        frame_index = int(params.get('frame_index', 0))

        # Pipelines
        pipe = get_ltx_condition(model_id=model_id, device=device, dtype=dtype)
        pipe_upsample = get_ltx_latent_upsample(
            model_id=model_id,
            upscaler_id=upscaler_id,
            device=device,
            dtype=dtype
        )

        # Build 1-frame condition
        condition = build_image_condition(
            image_path=str(init_path),
            frame_index=frame_index
        )

        # Resolve prompt (+ optional upstream override)
        prompt_bundle = PromptBundle(
            spec=spec,
            input=input
        )

        # --- sizes ---
        down_h, down_w = downscale_size(height, width, downscale_factor, pipe)
        up_h, up_w = upscale_size(down_h, down_w, upscale_factor)

        cuda_prerun(device)
        t0 = time.perf_counter()

        # Part 1: generate at smaller res -> latent video
        latents = pipe(
            conditions=[condition],
            prompt=prompt_bundle.prompt,
            negative_prompt=prompt_bundle.negative_prompt,
            width=down_w,
            height=down_h,
            guidance_scale=guidance_scale,
            guidance_rescale=guidance_rescale,
            num_frames=num_frames,
            num_inference_steps=steps_main,
            decode_timestep=decode_timestep,
            decode_noise_scale=decode_noise_scale,
            image_cond_noise_scale=image_cond_noise_scale,
            generator=gen,
            output_type='latent',
            max_sequence_length=max_sequence_length,
        ).frames

        # Part 2: latent upsample
        up_latents = pipe_upsample(
            latents=latents,
            output_type='latent',
        ).frames

        # Part 3: short denoise refine
        video_out = pipe(
            conditions=[condition],
            prompt=prompt_bundle.prompt,
            negative_prompt=prompt_bundle.negative_prompt,
            width=up_w,
            height=up_h,
            guidance_scale=guidance_scale,
            guidance_rescale=guidance_rescale,
            num_frames=num_frames,
            denoise_strength=denoise_strength,
            num_inference_steps=steps_refine,
            latents=up_latents,
            decode_timestep=decode_timestep,
            decode_noise_scale=decode_noise_scale,
            image_cond_noise_scale=image_cond_noise_scale,
            generator=gen,
            output_type='pil',
            max_sequence_length=max_sequence_length,
        ).frames[0]

        cuda_sync(device)
        dt_s = time.perf_counter() - t0

        # Part 4: resize down to target output size
        video_out = [f.resize((width, height)) for f in video_out]

        out_dir = ensure_out_dir(output_dir)
        video_path = save_video(
            out_dir=out_dir,
            node_id=self.id,
            seed=seed,
            video_out=video_out,
            fps=fps,
        )

        mem = cuda_mem_stats(device)

        out = finalize_video_output(
            node_kind=str(self.op),
            input_image=str(init_path),
            node_id=self.id,
            video_path=video_path,
            seed=seed,
            params={
                'guidance_scale': guidance_scale,
                'guidance_rescale': guidance_rescale,
                'width': width,
                'height': height,
                'fps': fps,
                'num_frames': num_frames,
                'steps_main': steps_main,
                'steps_refine': steps_refine,
                'denoise_strength': denoise_strength,
                'downscale_factor': downscale_factor,
                'upscale_latent_factor': upscale_factor,
                'decode_timestep': decode_timestep,
                'decode_noise_scale': decode_noise_scale,
                'image_cond_noise_scale': image_cond_noise_scale,
                'max_sequence_length': max_sequence_length,
                'frame_index': frame_index,
            },
            dt_s=dt_s,
            cuda_mem=mem,
            ic_lora_specs=None,  # intentionally disabled here
            model_info={
                'id': model_id,
                'upscaler': upscaler_id,
                'device': device,
                'dtype': str(dtype).replace('torch.', ''),
            },
        )

        return out
