import json
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

import torch
from diffusers.pipelines.ltx.pipeline_ltx_condition import LTXVideoCondition
from diffusers.utils import export_to_video, load_image, load_video

from stability.cache.ltx_models import (get_ltx_condition,
                                        get_ltx_latent_upsample)
from stability.core.config import *
from stability.dag import NodeRef
from stability.nodes import *
from stability.nodes.ltx import round_to_vae

_default_model = 'Lightricks/LTX-Video-0.9.7-dev'
_default_upscaler = 'Lightricks/ltxv-spatial-upscaler-0.9.7'


@dataclass
class Img2Video(NodeRef):
    """
    Image-to-video node based on LTX-Video.

    This node generates a short video clip starting from a single keyframe
    image and a text prompt. The input image is provided through the default
    DAG connection (``src >> img2video``) and is internally treated as a
    one-frame video condition.

    The node produces a single primary output dictionary containing at least:
    - ``video``: filesystem path to the generated MP4 video
    - ``metadata``: filesystem path to a JSON sidecar with generation details

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    spec : dict
        Configuration dictionary describing the model, prompts, and
        image-to-video parameters. Typical keys include ``model``, ``prompt``,
        ``negative_prompt``, ``params`` (e.g. ``width``, ``height``,
        ``num_frames``, ``fps``, ``steps_main``, ``steps_refine``,
        ``denoise_strength``), and ``seed``.

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class
        name (e.g. ``"img2video"``).

    Notes
    -----
    - The default input edge provides the *keyframe image* used to initialize
      the video generation.
    - Internally, the image is converted into a one-frame video condition
      compatible with the LTX-Video pipeline.
    - This node does not require ControlNet inputs; motion and temporal
      coherence are inferred by the underlying video diffusion model.
    """

    spec: Union[Dict[str, Any], str, Path] = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # HF env
        os.environ['HF_HOME'] = HF_HOME
        os.environ['HF_HUB_CACHE'] = HF_HUB_CACHE
        os.environ['HF_HUB_DISABLE_TELEMETRY'] = HF_HUB_DISABLE_TELEMETRY

        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        spec = resolve_spec(self.spec)

        # model settings
        model = spec.get('model', {})
        device = model.get('device', 'cuda')
        dtype = resolve_dtype(model.get('dtype', 'bf16'))
        model_id = model.get('id', _default_model)
        upscaler_id = model.get('upscaler', _default_upscaler)

        # prompts
        prompt = norm_prompt(spec.get('prompt'))
        negative_prompt = norm_prompt(
            spec.get('negative_prompt'),
            joiner=', '
        )

        # params
        params = spec.get('params', {})
        height = int(params.get('height', 480))
        width = int(params.get('width', 832))
        fps = int(params.get('fps', 24))
        num_frames = int(params.get('num_frames', 96))
        steps_main = int(params.get('steps_main', 30))
        steps_refine = int(params.get('steps_refine', 10))
        denoise_strength = float(params.get('denoise_strength', 0.4))
        downscale_factor = float(params.get('downscale_factor', 2 / 3))
        upscale_factor = float(params.get('upscale_latent_factor', 2))
        max_sequence_length = int(params.get('max_sequence_length', 512))

        decode_timestep = float(params.get('decode_timestep', 0.05))
        image_cond_noise_scale = float(
            params.get('image_cond_noise_scale', 0.025))
        frame_index = int(params.get('frame_index', 0))

        # seed
        seed = resolve_seed(spec.get('seed', 'random'))
        gen = torch.Generator(device=device).manual_seed(seed)

        # Inputs from DAG
        input = input or {}

        # 1) init image comes from default input_id
        init_up = input.get('default')
        if init_up is None:
            raise ValueError(
                'Img2Video requires an init image wired into the default input (src >> img2video).')

        init_path = init_up.get('image') or init_up.get('path')
        if not init_path:
            raise ValueError(
                "Init image upstream output must contain 'image' (path).")

        pipe = get_ltx_condition(model_id=model_id, device=device, dtype=dtype)
        pipe_upsample = get_ltx_latent_upsample(
            model_id=model_id,
            upscaler_id=upscaler_id,
            device=device,
            dtype=dtype
        )

        # --- build condition from single image ---
        image = load_image(init_path)

        # NOTE: this is the same trick as your original script:
        # export_to_video([image]) -> a 1-frame mp4 -> load_video(mp4_bytes/path) -> LTXVideoCondition
        video_1frame = load_video(export_to_video([image]))
        condition = LTXVideoCondition(
            video=video_1frame,
            frame_index=frame_index
        )

        # --- sizes ---
        expected_h, expected_w = height, width
        down_h = int(expected_h * downscale_factor)
        down_w = int(expected_w * downscale_factor)
        down_h, down_w = round_to_vae(down_h, down_w, pipe)

        gen = torch.Generator(device=device).manual_seed(seed)

        # --- measure time + memory ---
        if device.startswith('cuda'):
            torch.cuda.reset_peak_memory_stats()
            torch.cuda.synchronize()

        t0 = time.perf_counter()

        # Part 1: generate at smaller res -> latent video
        latents = pipe(
            conditions=[condition],
            prompt=prompt,
            negative_prompt=negative_prompt,
            width=down_w,
            height=down_h,
            num_frames=num_frames,
            num_inference_steps=steps_main,
            generator=gen,
            output_type='latent',
            max_sequence_length=max_sequence_length
        ).frames

        # Part 2: latent upsample (2x)
        up_h, up_w = int(down_h * upscale_factor), int(down_w * upscale_factor)
        up_latents = pipe_upsample(
            latents=latents, output_type='latent').frames

        # Part 3: short denoise refine
        video = pipe(
            conditions=[condition],
            prompt=prompt,
            negative_prompt=negative_prompt,
            width=up_w,
            height=up_h,
            num_frames=num_frames,
            denoise_strength=denoise_strength,
            num_inference_steps=steps_refine,
            latents=up_latents,
            decode_timestep=decode_timestep,
            image_cond_noise_scale=image_cond_noise_scale,
            generator=gen,
            output_type='pil',
            max_sequence_length=max_sequence_length
        ).frames[0]

        dt_s = time.perf_counter() - t0

        # Part 4: resize down to target
        video = [f.resize((expected_w, expected_h)) for f in video]

        out_path = make_node_output_path(
            out_dir=out_dir,
            node_id=self.id,
            seed=seed,
            ext='mp4'
        )
        export_to_video(video, str(out_path), fps=fps)

        # --- memory stats ---
        mem = {}
        if device.startswith('cuda'):
            mem = {
                'allocated_gb': round(torch.cuda.memory_allocated() / 1024**3, 3),
                'reserved_gb': round(torch.cuda.memory_reserved() / 1024**3, 3),
                'peak_allocated_gb': round(torch.cuda.max_memory_allocated() / 1024**3, 3),
                'peak_reserved_gb': round(torch.cuda.max_memory_reserved() / 1024**3, 3),
            }

        meta = {
            'ok': True,
            'node': 'ltx_i2v',
            'input_image': str(init_path),
            'id': self.id,
            'video': str(out_path),
            'model': {
                'id': model_id,
                'upscaler': upscaler_id,
                'device': device,
                'dtype': str(dtype).replace('torch.', ''),
            },
            'params': {
                'width': expected_w,
                'height': expected_h,
                'fps': fps,
                'num_frames': num_frames,
                'seed': seed,
                'steps_main': steps_main,
                'steps_refine': steps_refine,
                'denoise_strength': denoise_strength,
                'downscale_factor': downscale_factor,
                'decode_timestep': decode_timestep,
                'image_cond_noise_scale': image_cond_noise_scale,
                'frame_index': frame_index,
            },
            'timing': {'seconds': round(dt_s, 3)},
            'cuda_mem': mem,
        }
        meta_path = out_path.with_suffix('.json')
        meta_path.write_text(
            json.dumps(meta, indent=2, ensure_ascii=False),
            encoding='utf-8'
        )

        return meta
