import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

from stability.cache.ltx_models import (get_ltx_condition,
                                        get_ltx_latent_upsample)
from stability.dag import NodeRef
from stability.nodes.common.config_resolve import SpecInput
from stability.nodes.common.cuda_stat import *
from stability.nodes.common.env import setup_env
from stability.nodes.common.paths import ensure_out_dir
from stability.nodes.ltx.conditioning import build_image_condition
from stability.nodes.ltx.io import finalize_video_output, save_video
from stability.nodes.ltx.ltx_resolve import resolve_ltx_common
from stability.nodes.ltx.video_utils import downscale_size, upscale_size
from stability.nodes.wiring.mixins import PromptMixin
from stability.nodes.wiring.prompt import PromptBundle


@dataclass
class Img2Video(PromptMixin, NodeRef):
    """
    Image-to-video node based on LTX-Video (single-keyframe conditioning).

    This node generates a short video clip from a single input image (keyframe)
    using the LTX-Video diffusion model. The input image is provided via the
    default DAG connection (``src >> img2video``) and is converted into a
    one-frame LTX condition (``LTXVideoCondition``). The condition is then passed
    through the pipeline using the native ``conditions=[...]`` mechanism.

    Video content is produced through a multi-stage process that first generates
    a low-resolution latent video and then refines it into a final high-resolution
    sequence.

    Prompts are resolved from the node configuration and may optionally be
    overridden by an upstream prompt bundle attached through the prompt channel.

    The node produces a single primary output dictionary containing at least:
    - ``video``: filesystem path to the generated MP4 video
    - ``metadata``: filesystem path to a JSON sidecar with generation details

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    spec : dict or str or pathlib.Path or sequence of (dict or str or pathlib.Path)
        Node configuration specification.

        The specification may be provided as an in-memory dictionary, as a path
        to a HOCON configuration file, or as a sequence of such elements. When a
        sequence is given, each element is resolved independently and merged from
        left to right, with later elements overriding earlier ones.

        Typical keys include:

        - ``model``: model identifiers and runtime options
        - ``prompt``: text prompt describing the desired video
        - ``negative_prompt``: optional negative prompt
        - ``seed``: random seed (or ``'random'``)
        - ``params``:
            - ``width`` / ``height``: target output resolution
            - ``fps``: frames per second
            - ``num_frames``: total number of frames
            - ``steps_main``: diffusion steps for latent generation
            - ``steps_refine``: diffusion steps for refinement
            - ``denoise_strength``: refinement denoise strength
            - ``guidance_scale`` / ``guidance_rescale``: classifier-free guidance parameters
            - ``downscale_factor``: spatial downscaling factor for latent generation
            - ``upscale_latent_factor``: latent upscaling factor (latent upsampler stage)
            - ``decode_timestep`` / ``decode_noise_scale``: decode-time noise controls
            - ``image_cond_noise_scale``: noise applied to the image conditioning signal
            - ``max_sequence_length``: tokenizer sequence length cap for prompts
            - ``frame_index``: index used by ``LTXVideoCondition`` to anchor the image
              conditioning in the generated sequence (default 0)

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class
        name (e.g. ``'img2video'``).
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by ``PromptMixin``.

    Inputs
    ------
    default : dict
        Required upstream output mapping that must contain the input image path.
        The node expects either:

        - ``image`` : str
            Filesystem path to the input keyframe image.
        - ``path`` : str
            Alternative key for the filesystem path.

    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Expected keys include ``prompt`` and ``negative_prompt`` (and
        optionally ``prompt_2`` / ``negative_prompt_2`` if your PromptBundle supports them).

    Outputs
    -------
    dict
        Primary output dictionary with at least:

        - ``ok`` : bool
        - ``node`` : str (typically ``'img2video'``)
        - ``id`` : str (node id)
        - ``video`` : str (path to the generated MP4)
        - ``metadata`` : str (path to a JSON sidecar with generation details)

        The metadata sidecar includes resolved parameters, model information,
        timing information, and (when running on CUDA) memory statistics.

    Notes
    -----
    - Hugging Face cache/environment variables are configured via ``setup_env()``
      prior to loading any pipeline components.
    - The node executes in three conceptual stages:
        1. Latent video generation at reduced resolution (``steps_main``)
        2. Latent upsampling (latent upsampler)
        3. Short refinement pass to produce the final video (``steps_refine``)
      A final resizing step ensures the output frames match exactly
      ``params.width``/``params.height``.

    - Image conditioning is implemented by converting the input image to a one-frame
      video and wrapping it into an ``LTXVideoCondition``. The condition is then
      passed using ``conditions=[condition]`` in both the latent generation stage
      and the refinement stage.

    - This node intentionally does NOT support IC-LoRA at the moment (by design),
      as mixing multiple conditioning mechanisms can introduce fragile interactions.
      Structural or motion guidance beyond the keyframe should be implemented as a
      separate node (or reintroduced later with explicit validation and tests).

    - The output video is written using ``export_to_video`` and is intended for
      preview/inference usage. If you need lossless control artifacts, consider
      exporting individual frames (PNG) instead.
    """

    spec: SpecInput = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # HF env
        setup_env()

        ctx = resolve_ltx_common(self.spec)

        input = input or {}
        init_up = input.get('default')
        if init_up is None:
            raise ValueError(
                'Img2Video requires an init image wired into the default input (src >> img2video).'
            )

        init_path = init_up.get('image') or init_up.get('path')
        if not init_path:
            raise ValueError("Upstream output must contain 'image' (path).")

        # Pipelines
        pipe = get_ltx_condition(
            model_id=ctx.model.model_id,
            device=ctx.model.device,
            dtype=ctx.model.dtype
        )
        pipe_upsample = get_ltx_latent_upsample(
            model_id=ctx.model.model_id,
            upscaler_id=ctx.model.upscaler_id,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        # Build 1-frame condition
        condition = build_image_condition(
            image_path=str(init_path),
            frame_index=ctx.frame_index
        )

        # Resolve prompt (+ optional upstream override)
        prompt_bundle = PromptBundle(
            spec=ctx.spec,
            input=input
        )

        # --- sizes ---
        down_h, down_w = downscale_size(
            height=ctx.height,
            width=ctx.width,
            factor=ctx.downscale_factor,
            pipe=pipe)
        up_h, up_w = upscale_size(down_h, down_w, ctx.upscale_latent_factor)

        cuda_prerun(ctx.model.device)
        t0 = time.perf_counter()

        # Part 1: generate at smaller res -> latent video
        latents = pipe(
            conditions=[condition],
            prompt=prompt_bundle.prompt,
            negative_prompt=prompt_bundle.negative_prompt,
            width=down_w,
            height=down_h,
            guidance_scale=ctx.guidance_scale,
            guidance_rescale=ctx.guidance_rescale,
            num_frames=ctx.num_frames,
            num_inference_steps=ctx.steps_main,
            decode_timestep=ctx.decode_timestep,
            decode_noise_scale=ctx.decode_noise_scale,
            image_cond_noise_scale=ctx.image_cond_noise_scale,
            generator=ctx.rng.gen,
            output_type='latent',
            max_sequence_length=ctx.max_sequence_length,
        ).frames

        # Part 2: latent upsample
        up_latents = pipe_upsample(
            latents=latents,
            output_type='latent',
        ).frames

        # Part 3: short denoise refine
        video_out = pipe(
            conditions=[condition],
            prompt=prompt_bundle.prompt,
            negative_prompt=prompt_bundle.negative_prompt,
            width=up_w,
            height=up_h,
            guidance_scale=ctx.guidance_scale,
            guidance_rescale=ctx.guidance_rescale,
            num_frames=ctx.num_frames,
            denoise_strength=ctx.denoise_strength,
            num_inference_steps=ctx.steps_refine,
            latents=up_latents,
            decode_timestep=ctx.decode_timestep,
            decode_noise_scale=ctx.decode_noise_scale,
            image_cond_noise_scale=ctx.image_cond_noise_scale,
            generator=ctx.rng.gen,
            output_type='pil',
            max_sequence_length=ctx.max_sequence_length,
        ).frames[0]

        cuda_sync(ctx.model.device)
        dt_s = time.perf_counter() - t0

        # Part 4: resize down to target output size
        video_out = [f.resize((ctx.width, ctx.height)) for f in video_out]

        out_dir = ensure_out_dir(output_dir)
        video_path = save_video(
            out_dir=out_dir,
            node_id=self.id,
            seed=ctx.rng.seed,
            video_out=video_out,
            fps=ctx.fps,
        )

        mem = cuda_mem_stats(ctx.model.device)

        out = finalize_video_output(
            node_kind=str(self.op),
            input_image=str(init_path),
            node_id=self.id,
            video_path=video_path,
            seed=ctx.rng.seed,
            params={
                'guidance_scale': ctx.guidance_scale,
                'guidance_rescale': ctx.guidance_rescale,
                'width': ctx.width,
                'height': ctx.height,
                'fps': ctx.fps,
                'num_frames': ctx.num_frames,
                'steps_main': ctx.steps_main,
                'steps_refine': ctx.steps_refine,
                'denoise_strength': ctx.denoise_strength,
                'downscale_factor': ctx.downscale_factor,
                'upscale_latent_factor': ctx.upscale_latent_factor,
                'decode_timestep': ctx.decode_timestep,
                'decode_noise_scale': ctx.decode_noise_scale,
                'image_cond_noise_scale': ctx.image_cond_noise_scale,
                'max_sequence_length': ctx.max_sequence_length,
                'frame_index': ctx.frame_index,
            },
            dt_s=dt_s,
            cuda_mem=mem,
            model_info={
                'id': ctx.model.model_id,
                'upscaler': ctx.model.upscaler_id,
                'device': ctx.model.device,
                'dtype': str(ctx.model.dtype).replace('torch.', ''),
            },
        )

        return out
