import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

from stability.cache.ltx_models import *
from stability.core.config import *
from stability.dag import NodeRef
from stability.nodes import *
from stability.nodes.ltx import *
from stability.nodes.ltx.ltx_common import *
from stability.nodes.sdxl_common import PromptMixin, setup_env


@dataclass
class Txt2Video(IcLoRaMixin, PromptMixin, NodeRef):
    """
    Text-to-video node based on LTX-Video.

    This node generates a short video clip from a text prompt using the
    LTX-Video diffusion model. Video content is produced through a
    multi-stage process that first generates a low-resolution latent
    video and then refines it into a final high-resolution sequence.

    Prompts are resolved from the node configuration and may optionally be
    overridden by an upstream prompt bundle attached through the prompt channel.

    Optionally, the generation can be conditioned using a single
    Image-Conditioned LoRA (IC-LoRA). When an IC-LoRA is attached, an
    upstream video (typically edge-based, depth, or similar structural
    guidance) is used to constrain the generated motion and geometry
    while preserving the model's generative freedom.

    The node produces a single primary output dictionary containing at least:
    - ``video``: filesystem path to the generated MP4 video
    - ``metadata``: filesystem path to a JSON sidecar with generation details

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    spec : dict
        Configuration dictionary describing the model, prompts, and
        text-to-video parameters.

        Typical keys include:

        - ``model``: model identifiers and runtime options
        - ``prompt``: text prompt describing the desired video
        - ``negative_prompt``: optional negative prompt
        - ``seed``: random seed (or ``"random"``)
        - ``params``:
            - ``width`` / ``height``: target output resolution
            - ``fps``: frames per second
            - ``num_frames``: total number of frames
            - ``steps_main``: diffusion steps for latent generation
            - ``steps_refine``: diffusion steps for refinement
            - ``denoise_strength``: refinement denoise strength
            - ``guidance_scale`` / ``guidance_rescale``: classifier-free guidance parameters
            - ``downscale_factor``: spatial downscaling factor for latent generation
            - ``decode_timestep`` / ``decode_noise_scale``: decode-time noise controls
            - ``image_cond_noise_scale``: noise applied to conditioning inputs

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class
        name (e.g. ``"txt2video"``).

    ic_lora : ICLoRaRegistry
        Registry used to attach a single Image-Conditioned LoRA (IC-LoRA)
        to this node. The registry exposes an AttachmentSink that allows
        an upstream video node to be wired as structural conditioning.
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by ``PromptMixin``.

    Inputs
    ------
    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Expected keys include ``prompt`` and ``negative_prompt``.

    Notes
    -----
    - This node does not consume any default DAG input.
    - When no IC-LoRA is attached, video motion and temporal structure
      are generated purely from the textual prompt.
    - When an IC-LoRA is attached, the conditioning video is used as a
      reference signal to guide motion and geometry, without directly
      copying pixel content.
    - Only one IC-LoRA attachment is supported by design.
    - The node executes in three conceptual stages:
        1. Latent video generation at reduced resolution
        2. Latent upsampling
        3. Short refinement pass to produce the final video
    """

    spec: Union[Dict[str, Any], str, Path] = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # HF env
        setup_env()

        spec, device, dtype, model_id, upscaler_id, guidance_scale, \
            guidance_rescale, height, width, fps, num_frames, steps_main, \
            steps_refine, denoise_strength, downscale_factor, upscale_factor, \
            decode_timestep, decode_noise_scale, image_cond_noise_scale, \
            max_sequence_length, seed, gen = resolve_ltx_common(self.spec)

        ic_lora_bundle = self.build_ic_lora_bundle(input)

        pipe = get_ltx_condition(model_id=model_id, device=device, dtype=dtype)
        pipe_upsample = get_ltx_latent_upsample(
            model_id=model_id,
            upscaler_id=upscaler_id,
            device=device,
            dtype=dtype
        )

        # --- sizes ---
        down_h, down_w = downscale_size(height, width, downscale_factor, pipe)
        up_h, up_w = upscale_size(down_h, down_w, upscale_factor)

        reference_video = apply_ic_lora(ic_lora_bundle, pipe)

        prompt_bundle = PromptBundle(
            spec=spec,
            input=input
        )

        cuda_prerun(device)

        t0 = time.perf_counter()

        # Part 1: generate at smaller res -> latent video
        latents = pipe(
            reference_video=reference_video,
            prompt=prompt_bundle.prompt,
            negative_prompt=prompt_bundle.negative_prompt,
            width=down_w,
            height=down_h,
            guidance_scale=guidance_scale,
            guidance_rescale=guidance_rescale,
            num_frames=num_frames,
            num_inference_steps=steps_main,
            decode_timestep=decode_timestep,
            decode_noise_scale=decode_noise_scale,
            image_cond_noise_scale=image_cond_noise_scale,
            generator=gen,
            output_type="latent",
            max_sequence_length=max_sequence_length
        ).frames


        # Part 2: latent upsample
        up_latents = pipe_upsample(
            latents=latents,
            output_type='latent'
        ).frames

        # Part 3: short denoise refine
        video_out = pipe(
            prompt=prompt_bundle.prompt,
            negative_prompt=prompt_bundle.negative_prompt,
            width=up_w,
            height=up_h,
            guidance_scale=guidance_scale,
            guidance_rescale=guidance_rescale,
            num_frames=num_frames,
            denoise_strength=denoise_strength,
            num_inference_steps=steps_refine,
            latents=up_latents,
            decode_timestep=decode_timestep,
            decode_noise_scale=decode_noise_scale,
            image_cond_noise_scale=image_cond_noise_scale,
            generator=gen,
            output_type="pil",
            max_sequence_length=max_sequence_length
        ).frames[0]

        cuda_sync(device)
        dt_s = time.perf_counter() - t0

        # Part 4: resize down to target
        video_out = [f.resize((width, height))
                     for f in video_out]

        out_dir = ensure_out_dir(output_dir)
        video_path = save_video(
            out_dir=out_dir,
            node_id=self.id,
            seed=seed,
            video_out=video_out,
            fps=fps
        )

        mem = cuda_mem_stats(device)

        out = finalize_video_output(
            node_kind=str(self.op),
            node_id=self.id,
            video_path=video_path,
            seed=seed,
            params={
                'guidance_scale': guidance_scale,
                'guidance_rescale': guidance_rescale,
                'width': width,
                'height': height,
                'fps': fps,
                'num_frames': num_frames,
                'seed': seed,
                'steps_main': steps_main,
                'steps_refine': steps_refine,
                'denoise_strength': denoise_strength,
                'downscale_factor': downscale_factor,
                'decode_timestep': decode_timestep,
                'image_cond_noise_scale': image_cond_noise_scale,
                'max_sequence_length': max_sequence_length
            },
            dt_s=dt_s,
            cuda_mem=mem,
            ic_lora_specs=self.ic_lora.spec,
            model_info={
                'id': model_id,
                'upscaler': upscaler_id,
                'device': device,
                'dtype': str(dtype).replace('torch.', ''),
            }
        )

        return out
