import json
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional

import torch
from diffusers.utils import export_to_video, load_video

from stability.cache.ltx_models import *
from stability.core.config import *
from stability.dag import NodeRef
from stability.nodes import *
from stability.nodes.ltx import *

_default_model = 'Lightricks/LTX-Video-0.9.7-dev'
_default_upscaler = 'Lightricks/ltxv-spatial-upscaler-0.9.7'


@dataclass
class Txt2Video(NodeRef):
    """
    Text-to-video node based on LTX-Video.

    This node generates a short video clip from a text prompt using the
    LTX-Video diffusion model. Video content is produced through a
    multi-stage process that first generates a low-resolution latent
    video and then refines it into a final high-resolution sequence.

    Optionally, the generation can be conditioned using a single
    Image-Conditioned LoRA (IC-LoRA). When an IC-LoRA is attached, an
    upstream video (typically edge-based, depth, or similar structural
    guidance) is used to constrain the generated motion and geometry
    while preserving the model's generative freedom.

    The node produces a single primary output dictionary containing at least:
    - ``video``: filesystem path to the generated MP4 video
    - ``metadata``: filesystem path to a JSON sidecar with generation details

    Parameters
    ----------
    id : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.
    spec : dict
        Configuration dictionary describing the model, prompts, and
        text-to-video parameters.

        Typical keys include:

        - ``model``: model identifiers and runtime options
        - ``prompt``: text prompt describing the desired video
        - ``negative_prompt``: optional negative prompt
        - ``seed``: random seed (or ``"random"``)
        - ``params``:
            - ``width`` / ``height``: target output resolution
            - ``fps``: frames per second
            - ``num_frames``: total number of frames
            - ``steps_main``: diffusion steps for latent generation
            - ``steps_refine``: diffusion steps for refinement
            - ``denoise_strength``: refinement denoise strength
            - ``guidance_scale`` / ``guidance_rescale``: classifier-free guidance parameters
            - ``downscale_factor``: spatial downscaling factor for latent generation
            - ``decode_timestep`` / ``decode_noise_scale``: decode-time noise controls
            - ``image_cond_noise_scale``: noise applied to conditioning inputs

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class
        name (e.g. ``"txt2video"``).

    ic_lora : ICLoRaRegistry
        Registry used to attach a single Image-Conditioned LoRA (IC-LoRA)
        to this node. The registry exposes an AttachmentSink that allows
        an upstream video node to be wired as structural conditioning.

    Notes
    -----
    - This node does not consume any default DAG input.
    - When no IC-LoRA is attached, video motion and temporal structure
      are generated purely from the textual prompt.
    - When an IC-LoRA is attached, the conditioning video is used as a
      reference signal to guide motion and geometry, without directly
      copying pixel content.
    - Only one IC-LoRA attachment is supported by design.
    - The node executes in three conceptual stages:
        1. Latent video generation at reduced resolution
        2. Latent upsampling
        3. Short refinement pass to produce the final video
    """

    spec: Union[Dict[str, Any], str, Path] = field(default_factory=dict)
    ic_lora: ICLoRaRegistry = field(init=False, repr=False)

    def __post_init__(self) -> None:
        super().__post_init__()
        self.ic_lora = ICLoRaRegistry(self)

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # HF env
        os.environ['HF_HOME'] = HF_HOME
        os.environ['HF_HUB_CACHE'] = HF_HUB_CACHE
        os.environ['HF_HUB_DISABLE_TELEMETRY'] = HF_HUB_DISABLE_TELEMETRY

        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        spec = resolve_spec(self.spec)

        # model settings
        model = spec.get('model', {})
        device = model.get('device', 'cuda')
        dtype = resolve_dtype(model.get('dtype', 'bf16'))
        model_id = model.get('id', _default_model)
        upscaler_id = model.get('upscaler', _default_upscaler)

        # prompts
        prompt = norm_prompt(spec.get('prompt'))
        negative_prompt = norm_prompt(
            spec.get('negative_prompt'),
            joiner=', '
        )

        # params
        params = spec.get('params', {})
        guidance_scale = float(params.get('guidance_scale', 3))
        guidance_rescale = float(params.get('guidance_rescale', 0.7))

        height = int(params.get('height', 480))
        width = int(params.get('width', 832))
        fps = int(params.get('fps', 24))
        num_frames = int(params.get('num_frames', 96))

        steps_main = int(params.get('steps_main', 30))
        steps_refine = int(params.get('steps_refine', 10))
        denoise_strength = float(params.get('denoise_strength', 0.4))
        downscale_factor = float(params.get('downscale_factor', 2 / 3))
        upscale_factor = float(params.get('upscale_latent_factor', 2))

        decode_timestep = float(params.get('decode_timestep', 0.05))
        decode_noise_scale = float(params.get('decode_noise_scale', 0.025))
        image_cond_noise_scale = float(
            params.get('image_cond_noise_scale', 0.025)
        )

        max_sequence_length = int(params.get('max_sequence_length', 512))

        # seed
        seed = resolve_seed(spec.get('seed', 'random'))
        gen = torch.Generator(device=device).manual_seed(seed)

        ic_lora_bundle = ICLoRaBundle(
            ic_lora=self.ic_lora.spec,
            input=input
        )

        pipe = get_ltx_condition(model_id=model_id, device=device, dtype=dtype)
        pipe_upsample = get_ltx_latent_upsample(
            model_id=model_id,
            upscaler_id=upscaler_id,
            device=device,
            dtype=dtype
        )

        # --- sizes ---
        expected_h, expected_w = height, width
        down_h = int(expected_h * downscale_factor)
        down_w = int(expected_w * downscale_factor)
        down_h, down_w = round_to_vae(down_h, down_w, pipe)

        gen = torch.Generator(device=device).manual_seed(seed)

        # --- measure time + memory ---
        if device.startswith('cuda'):
            torch.cuda.reset_peak_memory_stats()
            torch.cuda.synchronize()

        t0 = time.perf_counter()

        if ic_lora_bundle.has_has_ic_lora:
            pipe.load_lora_weights(
                ic_lora_bundle.model_id,
                weight_name=ic_lora_bundle.weight_name,
                adapter_name=ic_lora_bundle.adapter_name
            )

            pipe.set_adapters(
                [ic_lora_bundle.adapter_name],
                [ic_lora_bundle.adapter_weight]
            )

            control_frames = load_video(ic_lora_bundle.video_path)
            reference_video = read_video_tensor(control_frames, device=device)
        else:
            pipe.unload_lora_weights()
            reference_video = None

        # Part 1: generate at smaller res -> latent video
        latents = pipe(
            reference_video=reference_video,
            prompt=prompt,
            negative_prompt=negative_prompt,
            width=down_w,
            height=down_h,
            guidance_scale=guidance_scale,
            guidance_rescale=guidance_rescale,
            num_frames=num_frames,
            num_inference_steps=steps_main,
            decode_timestep=decode_timestep,
            decode_noise_scale=decode_noise_scale,
            image_cond_noise_scale=image_cond_noise_scale,
            generator=gen,
            output_type="latent",
            max_sequence_length=max_sequence_length
        ).frames

        # Part 2: latent upsample (2x)
        up_h, up_w = int(down_h * upscale_factor), int(down_w * upscale_factor)
        up_latents = pipe_upsample(
            latents=latents,
            output_type='latent'
        ).frames

        # Part 3: short denoise refine
        video_out = pipe(
            prompt=prompt,
            negative_prompt=negative_prompt,
            width=up_w,
            height=up_h,
            guidance_scale=guidance_scale,
            guidance_rescale=guidance_rescale,
            num_frames=num_frames,
            denoise_strength=denoise_strength,
            num_inference_steps=steps_refine,
            latents=up_latents,
            decode_timestep=decode_timestep,
            decode_noise_scale=decode_noise_scale,
            image_cond_noise_scale=image_cond_noise_scale,
            generator=gen,
            output_type="pil",
            max_sequence_length=max_sequence_length
        ).frames[0]

        dt_s = time.perf_counter() - t0

        # Part 4: resize down to target
        video_out = [f.resize((expected_w, expected_h))
                     for f in video_out]

        out_path = make_node_output_path(
            out_dir=out_dir,
            node_id=self.id,
            seed=seed,
            ext='mp4'
        )
        # out_path.parent.mkdir(parents=True, exist_ok=True)
        export_to_video(video_out, str(out_path), fps=fps)

        # --- memory stats ---
        mem = {}
        if device.startswith('cuda'):
            mem = {
                'allocated_gb': round(torch.cuda.memory_allocated() / 1024**3, 3),
                'reserved_gb': round(torch.cuda.memory_reserved() / 1024**3, 3),
                'peak_allocated_gb': round(torch.cuda.max_memory_allocated() / 1024**3, 3),
                'peak_reserved_gb': round(torch.cuda.max_memory_reserved() / 1024**3, 3),
            }

        meta = {
            'ok': True,
            'node': 'ltx_i2v',
            'id': self.id,
            'video': str(out_path),
            'model': {
                'id': model_id,
                'upscaler': upscaler_id,
                'device': device,
                'dtype': str(dtype).replace('torch.', ''),
            },
            'seed': seed,
            'params': {
                'guidance_scale': guidance_scale,
                'guidance_rescale': guidance_rescale,
                'width': expected_w,
                'height': expected_h,
                'fps': fps,
                'num_frames': num_frames,
                'seed': seed,
                'steps_main': steps_main,
                'steps_refine': steps_refine,
                'denoise_strength': denoise_strength,
                'downscale_factor': downscale_factor,
                'decode_timestep': decode_timestep,
                'image_cond_noise_scale': image_cond_noise_scale,
                'max_sequence_length': max_sequence_length
            },
            'timing': {'seconds': round(dt_s, 3)},
            'cuda_mem': mem,
        }
        meta_path = out_path.with_suffix('.json')
        meta_path.write_text(
            json.dumps(meta, indent=2, ensure_ascii=False),
            encoding='utf-8'
        )

        return meta
