from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from morphalo.core.paths import make_node_output_path
from morphalo.dag import NodeRef
from morphalo.nodes.common.io import write_json_sidecar
from morphalo.nodes.image_output import ImageOutputMixin


@dataclass
class FileImage(ImageOutputMixin, NodeRef):
    """
    Source node that exposes one or more existing image files from the filesystem.

    ``FileImage`` is a pure *source node*: it performs no computation and has no
    dependencies on upstream nodes. Its only responsibility is to validate that
    the referenced image files exist and to expose their absolute paths as a
    JSON-serializable output.

    This node is typically used at the edges of a DAG to provide external images
    to downstream nodes such as Img2Img pipelines, ControlNet-conditioned nodes,
    or IP-Adapter inputs (including reference images and masks).

    A single instance may expose either:
    - one image, or
    - an ordered list of images.

    When multiple images are provided, the order is preserved and can be relied
    upon by downstream nodes (for example, when associating images with
    per-index inputs such as IP-Adapter masks).

    Parameters
    ----------
    name : str, optional
        Unique node identifier within the DAG.
        If not provided, an identifier is automatically generated by the
        enclosing DAG.

    path : str or Path or Sequence[str or Path]
        Filesystem path or paths to the image file(s) to be exposed by this node.
        Paths may be relative or absolute and may include user home expansion
        (``~``).

    Attributes
    ----------
    op : str
        Operator identifier automatically derived from the concrete class name
        (for example ``'file_image'``).

    Outputs
    -------
    dict
        Primary output dictionary.

        The node may expose either a single image or multiple images,
        depending on the number of provided paths.

        **Single image output**

        - ``ok`` : bool
        - ``node`` : str (e.g. ``"file_image"``)
        - ``id`` : str
        - ``image`` : str
          Absolute path to the image file.
        - ``metadata`` : str
          Path to the JSON sidecar.

        **Multiple images output**

        - ``ok`` : bool
        - ``node`` : str
        - ``id`` : str
        - ``images`` : list[str]
          Absolute paths to the image files.
        - ``metadata`` : str
          Path to the JSON sidecar.

        The order of ``images`` is stable and corresponds to the input order.

    Notes
    -----
    - The JSON sidecar produced by this node is used as a persistent cache.
      If the node implementation, its configuration, or specification changes,
      any previously generated sidecar files must be removed manually in order
      to avoid reusing stale cached outputs.

    - This node does not perform any transformation: it only validates and
      exposes filesystem paths.

    - When multiple images are provided, downstream nodes may interpret them
      as ordered inputs (for example, per-slot conditioning in IP-Adapter or
      ControlNet pipelines).
    """

    path: Union[str, Path, List[Union[str, Path]]]

    def run(self, output_dir, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        if not isinstance(self.path, list):
            paths = [self.path]
        else:
            paths = self.path

        paths = [Path(str(p)).expanduser().resolve() for p in paths]

        for p in paths:
            if not p.exists():
                raise FileNotFoundError(
                    f"FileImage node '{self.id}': file not found: {p}")
            if not p.is_file():
                raise FileNotFoundError(
                    f"FileImage node '{self.id}': not a file: {p}")

        out = {
            'ok': True,
            'node': self.op,
            'id': self.id,
            # 'image': [str(p) for p in paths] if len(paths) > 1 else str(paths[0])
        }

        if len(paths) > 1:
            out['images'] = [str(p) for p in paths]
        else:
            out['image'] = str(paths[0])

        out_path = make_node_output_path(
            out_dir=Path(output_dir),
            node_id=self.id,
            ext='json',
        )

        meta_path = write_json_sidecar(out_path, out)
        out['metadata'] = str(meta_path)

        return out
