import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

from diffusers import (StableDiffusionXLControlNetImg2ImgPipeline,
                       StableDiffusionXLImg2ImgPipeline)
from PIL import Image

from morphalo.cache.models import get_sdxl_base_pipe
from morphalo.core.paths import ensure_out_dir
from morphalo.dag import NodeRef
from morphalo.nodes.common.config_resolve import SpecInput
from morphalo.nodes.common.cuda_stat import (cuda_mem_stats, cuda_prerun,
                                             cuda_sync)
from morphalo.nodes.common.env import setup_env
from morphalo.nodes.common.io import save_image
from morphalo.nodes.io import finalize_image_output
from morphalo.nodes.sdxl_pipe_builder import build_pipe_kwargs
from morphalo.nodes.sdxl_resolve import resolve_common
from morphalo.nodes.wiring.conditioning import apply_ip_adapter
from morphalo.nodes.wiring.mixins import ControlNetMixin, PromptMixin
from morphalo.nodes.wiring.prompt import PromptBundle


def _resolve_long_side_size(
    *,
    image: Image.Image,
    long_side: int,
    multiple: int = 8,
) -> Tuple[int, int]:
    """
    Resolve a proportional output size from an input image.

    The longest side is scaled toward ``long_side`` and then aligned to the
    specified ``multiple`` and the shorter side is scaled proportionally
    from the input image aspect ratio.

    Parameters
    ----------
    image : PIL.Image.Image
        Input image.
    long_side : int
        Target size for the longest side.
    multiple : int, default=8
        Round each resolved dimension down to a multiple of this value.

    Returns
    -------
    tuple[int, int]
        Resolved ``(width, height)``.
    """
    if long_side <= 0:
        raise ValueError(f"'long_side' must be > 0, got {long_side}")

    src_w, src_h = image.size

    if src_w <= 0 or src_h <= 0:
        raise ValueError(f'invalid input image size {src_w}x{src_h}')

    if src_w >= src_h:
        width = int(long_side)
        height = int(round(src_h * (width / src_w)))
    else:
        height = int(long_side)
        width = int(round(src_w * (height / src_h)))

    if multiple > 1:
        width = max(multiple, (width // multiple) * multiple)
        height = max(multiple, (height // multiple) * multiple)

    return width, height


@dataclass
class Img2Img(ControlNetMixin, PromptMixin, NodeRef):
    """
    SDXL image-to-image generation node with optional ControlNet and IP-Adapter/FaceID conditioning.

    This node performs an image-to-image transformation using Stable Diffusion XL.
    The init image is provided by the upstream node connected to the default input
    channel (``input_id="default"``). Text prompts are resolved from the node
    configuration and may optionally be overridden by an upstream prompt bundle
    connected through the prompt channel (see Notes).

    If one or more ControlNet specifications are configured on this node, the
    underlying pipeline switches to ``StableDiffusionXLControlNetImg2ImgPipeline``
    and uses the attached ControlNet conditioning images. Otherwise, it uses the
    standard ``StableDiffusionXLImg2ImgPipeline``. IP-Adapter / FaceID conditioning
    is enabled or disabled based on the resolved bundles. IP-Adapter and FaceID are
    mutually exclusive.

    Parameters
    ----------
    name : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : dict or str or pathlib.Path or sequence of (dict or str or pathlib.Path)
        Node configuration specification.

        The specification may be provided as an in-memory dictionary, as a path
        to a HOCON configuration file, or as a sequence of such elements. When a
        sequence is given, each element is resolved independently and merged from
        left to right, with later elements overriding earlier ones.

        The node uses :func:`resolve_common` to resolve the shared SDXL configuration.
        Expected keys include:

        **Model / runtime**
        Exactly one of the following keys must be provided under ``spec.model``:

        - ``model.id`` : str
            Identifier of a pretrained model (e.g. a Hugging Face repository ID).
            The model will be loaded via the Diffusers "from_pretrained" mechanism.
            If not already cached locally, it will be downloaded on first use.

        - ``model.path`` : str
            Path to a local model file or directory.
            This is typically used for:
            - Single-file checkpoints (e.g. ``.safetensors``)
            - Fully downloaded model directories
            - Custom or fine-tuned local models

            The path is expanded via ``os.path.expanduser`` and must exist locally.

        Providing both ``model.id`` and ``model.path`` is an error.
        Providing neither is also an error.

        Additional runtime options:

        - ``model.device`` : str, optional
            Device to run on (default: ``"cuda"``).
        - ``model.dtype`` : str, optional
            DType name resolved by ``resolve_dtype`` (default: ``"bf16"``).

        **VAE**
        - ``vae`` : str or dict, optional
            Either a VAE id string, or a dict with ``vae.id``.

        **Generation parameters** (under ``params``)
        - ``params.steps`` : int, optional
            Number of denoising steps (default: 30).
        - ``params.cfg`` or ``params.guidance_scale`` : float, optional
            Classifier-free guidance scale (default: 6.0). ``cfg`` takes precedence.
        - ``params.strength`` : float, optional
            Denoising strength controlling how strongly the init image is transformed
            (default: 0.7).
        - ``params.width`` : int, optional
            Output width (default: 1024).
        - ``params.height`` : int, optional
            Output height (default: 1024).
        - ``params.long_side`` : int, optional
            If provided, overrides ``params.width`` and ``params.height`` and
            resolves the generation size proportionally from the input image so
            that its longest side matches this value.

        **Batch and randomness**
        - ``batch`` : int, optional
            Number of images to generate.

            - Must be greater than 0.
            - If ``seed`` is a list, defaults to ``len(seed)``.
            - If ``seed`` is a single integer, must be ``1``.
            - If ``seed`` is ``"rand"`` or ``"random"``, controls how many
            independent random seeds are generated.

        - ``seed`` : int or list[int] or str, optional
            Seed specification controlling stochastic sampling.

            Supported forms:

            - ``int``
            Single deterministic seed. Implies ``batch = 1``.

            - ``list[int]``
            Explicit list of seeds. If ``batch`` is not provided, it is inferred
            as ``len(seed)``. If ``batch`` is provided, it must match the list
            length.

            - ``"rand"`` or ``"random"``
            Generate one or more random seeds. If ``batch`` is not provided,
            defaults to ``1``. Otherwise, ``batch`` independent seeds are generated.

    Attributes
    ----------
    op : str
        Operator identifier derived from the concrete node class name (e.g.
        ``"img2img"``).
    controlnet : ControlNetRegistry
        Registry used to declare ControlNet conditioning inputs (via sinks),
        provided by ``ControlNetMixin``.
    ip_adapter : IpAdapterRegistry
        Registry used to declare IP-Adapter reference inputs (via sinks),
        provided by ``ControlNetMixin``.
    face_id : FaceIdRegistry
        Registry used to declare FaceID reference inputs (via sinks),
        provided by ``ControlNetMixin``.
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by
        ``PromptMixin``.

    Inputs
    ------
    default : dict
        Required. Upstream output dictionary containing the init image path. The node
        expects either ``"image"`` or ``"path"`` to point to the image file.

    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Expected keys include ``prompt``, ``prompt_2``,
        ``negative_prompt``, and ``negative_prompt_2``.

    Additional typed inputs may be attached via ControlNet/IP-Adapter/FaceID sinks
    declared on this node (see Notes).

    Outputs
    -------
    dict
        Primary output dictionary.

        The node may produce either a single image or a batch of images,
        depending on the resolved ``batch`` size.

        **Single image output (batch = 1)**

        - ``ok`` : bool
        - ``node`` : str (e.g. ``"img2img"``)
        - ``id`` : str
        - ``image`` : str
        Path to the generated image.
        - ``seed`` : int
        Seed used to generate the image.
        - ``metadata`` : str
        Path to the JSON sidecar.

        **Batch output (batch > 1)**

        - ``ok`` : bool
        - ``node`` : str
        - ``id`` : str
        - ``images`` : list[str]
        Paths to generated images.
        - ``seeds`` : list[int]
        Seeds aligned with ``images`` (same order).
        - ``batch`` : int
        Number of generated images.
        - ``metadata`` : str
        Path to the JSON sidecar (shared across the batch).

        The metadata sidecar includes resolved parameters, model information,
        timing information, and (when running on CUDA) memory statistics.

        For batch outputs, a single sidecar file is written per node execution.
        The order of ``images`` and ``seeds`` is stable and corresponds to the
        internal generation order.

    Notes
    -----
    - The init image is loaded from the upstream path and converted to RGB.
      The effective generation size is resolved either from ``params.width`` /
      ``params.height`` or, when ``params.long_side`` is provided, from the
      input image aspect ratio.
    - Prompt resolution is performed by :class:`PromptBundle`: 
      if a prompt bundle is
      wired into ``prompt:default``, it takes precedence over the local ``spec``;
      otherwise the local ``spec`` is used.
    - ControlNet, IP-Adapter, and FaceID inputs are collected from DAG wiring
      through their respective registries and bundled via
      ``build_control_bundles``.
    - When ControlNet is enabled, this node calls the img2img pipeline with
      ``image=init_image`` and passes ControlNet conditioning via ``control_image``
      (through ``build_pipe_kwargs(..., init_image_already_passed=True)``).
    - IP-Adapter and FaceID are mutually exclusive in this node.
    """

    spec: SpecInput = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        # HF env
        setup_env()

        ctx = resolve_common(self.spec)

        input = input or {}

        # 1) init image comes from default input_id
        init_up = input.get('default')
        if init_up is None:
            raise ValueError(
                'Img2Img requires an init image wired into the default input (src >> img2img).')

        init_path = init_up.get('image') or init_up.get('path')
        if not init_path:
            raise ValueError(
                "Init image upstream output must contain 'image' (path)."
            )

        with Image.open(init_path) as im:
            init_image = im.convert('RGB')

        long_side = ctx.long_side

        if long_side is not None:
            width, height = _resolve_long_side_size(
                image=init_image,
                long_side=long_side,
                multiple=8,
            )
        else:
            width = ctx.width
            height = ctx.height

        init_image = init_image.resize((width, height), resample=Image.LANCZOS)

        # --- resolve inputs from DAG wiring ---
        cn_bundle, ip_bundle, face_bundle = self.build_control_bundles(
            input=input,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        base = get_sdxl_base_pipe(
            model_ref=ctx.model.model_ref,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
            vae_id=ctx.model.vae_id,
        )

        if ip_bundle.has_ip_adapter and face_bundle.has_face_id:
            raise ValueError(
                'IP_Adapter and IP-Adapter-FaceID are mutually exclusive (chose one).'
            )

        # pipeline load (two-path: direct or via base components)
        if cn_bundle.has_controlnet:
            pipe = StableDiffusionXLControlNetImg2ImgPipeline(
                **base.components,
                controlnet=cn_bundle.controlnet_arg
            )
        else:
            pipe = StableDiffusionXLImg2ImgPipeline(
                **base.components
            )

        prompt_bundle = PromptBundle(spec=ctx.spec, input=input)

        cuda_prerun(ctx.model.device)
        t0 = time.perf_counter()

        apply_ip_adapter(
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            pipe=pipe,
            batch=ctx.batch,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        pipe_kwargs = build_pipe_kwargs(
            cn_bundle=cn_bundle,
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            height=height,
            width=width,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
            init_image_already_passed=True,
        )

        if 'cross_attention_kwargs' in pipe_kwargs:
            l = len(ip_bundle.weight_names_arg) + \
                len(face_bundle.weight_names_arg)
            masks = pipe_kwargs['cross_attention_kwargs']['ip_adapter_masks']
            assert len(masks) == l

        if ctx.strength <= 0:
            raise ValueError(
                'params.strength cannot be 0 or lesser.'
            )

        # IMPORTANT: Img2Img + ControlNet uses image=init and control_image=control
        result = pipe(
            prompt=prompt_bundle.prompt,
            prompt_2=prompt_bundle.prompt_2,
            negative_prompt=prompt_bundle.negative_prompt,
            negative_prompt_2=prompt_bundle.negative_prompt_2,
            image=init_image,
            strength=ctx.strength,
            num_inference_steps=ctx.steps,
            guidance_scale=ctx.cfg,
            generator=ctx.rng.generators,
            width=width,
            height=height,
            num_images_per_prompt=ctx.batch,
            **pipe_kwargs
        )

        cuda_sync(ctx.model.device)
        dt_s = time.perf_counter() - t0

        images = result.images
        if len(images) != len(ctx.rng.seeds):
            raise ValueError(
                f'Expected {len(ctx.rng.seeds)} output images, got {len(images)}'
            )

        out_dir = ensure_out_dir(output_dir)
        img_paths = [save_image(
            out_dir,
            node_id=self.id,
            seed=seed,
            img=img,
        ) for img, seed in zip(images, ctx.rng.seeds)]

        mem = cuda_mem_stats(ctx.model.device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_paths,
            seed=ctx.rng.seeds,
            params={
                'steps': ctx.steps,
                'guidance_scale': ctx.cfg,
                'strength': ctx.strength,
                'width': width,
                'height': height,
                **({'long_side': ctx.long_side} if ctx.long_side is not None else {}),
            },
            dt_s=dt_s,
            cuda_mem=mem,
            controlnet_specs=self.controlnet.specs,
            ip_adapter_specs=self.ip_adapter.specs,
            face_id_specs=self.face_id.specs,
            model_info={
                'source': ctx.model.model_ref.source,
                'ref': ctx.model.model_ref.ref,
                **({'vae_id': ctx.model.vae_id} if ctx.model.vae_id is not None else {}),
                'dtype': str(ctx.model.dtype).replace('torch.', ''),
                'device': ctx.model.device,
            }
        )

        return out
