import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Literal, Optional

from PIL import Image

from morphalo.cache.models import get_sdxl_base_pipe
from morphalo.dag import AttachmentSink, NodeRef
from morphalo.nodes.common.config_resolve import SpecInput, resolve_spec
from morphalo.nodes.common.cuda_mem import CudaPostRunMixin
from morphalo.nodes.common.cuda_stat import (cuda_mem_stats, cuda_prerun,
                                             cuda_sync)
from morphalo.nodes.common.device import is_cuda_device
from morphalo.nodes.common.env import setup_env
from morphalo.nodes.common.io import save_image
from morphalo.nodes.img import resolve_long_side_size
from morphalo.nodes.io import finalize_image_output
from morphalo.nodes.sdxl_pipe_builder import build_pipe_kwargs
from morphalo.nodes.sdxl_resolve import ImageGenerationContext, resolve_common
from morphalo.nodes.wiring.conditioning import apply_ip_adapter
from morphalo.nodes.wiring.mixins import ControlNetMixin, PromptMixin
from morphalo.nodes.wiring.prompt import PromptBundle

ImageMode = Literal['RGB', 'L']


def _load_resize_image(
    image_path: str,
    *,
    mode: ImageMode,
    width: int,
    height: int,
    resample: Image.Resampling = Image.Resampling.LANCZOS,
) -> Image.Image:
    """
    Load an image, convert it to the requested PIL mode, and resize it.

    Parameters
    ----------
    image_path : str
        Filesystem path to the image.
    mode : {'RGB', 'L'}
        Target PIL image mode.

        Use ``'RGB'`` for init images and ``'L'`` for inpaint masks.
    width : int
        Target output width.
    height : int
        Target output height.
    resample : PIL.Image.Resampling, optional
        Resampling filter used during resize.

    Returns
    -------
    PIL.Image.Image
        Loaded, converted, and resized image.
    """
    with Image.open(image_path) as im:
        image = im.convert(mode)

    return image.resize((width, height), resample=resample)


def _resolve_inpaint_size(
    ctx: ImageGenerationContext,
    init_path: str,
) -> tuple[int, int]:
    """
    Resolve the inpaint generation size from the init image.

    Parameters
    ----------
    ctx : ImageGenerationContext
        Resolved generation context.
    init_path : str
        Filesystem path to the init image.

    Returns
    -------
    tuple[int, int]
        Resolved ``(width, height)``.
    """
    if ctx.long_side is None:
        return ctx.width, ctx.height

    with Image.open(init_path) as im:
        image = im.convert('RGB')

    return resolve_long_side_size(
        image=image,
        long_side=ctx.long_side,
        multiple=8,
    )


@dataclass
class Inpaint(CudaPostRunMixin, ControlNetMixin, PromptMixin, NodeRef):
    """
    SDXL inpainting node with optional ControlNet and IP-Adapter/FaceID conditioning.

    This node performs inpainting using Stable Diffusion XL and may produce a single
    image or a batch of images. The init image is provided by the upstream node
    connected to the default input channel (``input_id="default"``). The inpainting
    mask is provided by an upstream node connected to the mask input channel
    (``input_id="mask"``). Text prompts are resolved from the node configuration and
    may optionally be overridden by an upstream prompt bundle connected through the
    prompt channel (see Notes).

    If one or more ControlNet specifications are configured on this node, the
    underlying pipeline switches to ``StableDiffusionXLControlNetInpaintPipeline``
    and uses the attached ControlNet conditioning images. Otherwise, it uses the
    standard ``StableDiffusionXLInpaintPipeline``. IP-Adapter / FaceID conditioning
    is enabled or disabled based on the resolved bundles. IP-Adapter and FaceID are
    mutually exclusive.

    Parameters
    ----------
    name : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    spec : dict or str or pathlib.Path or sequence of (dict or str or pathlib.Path)
        Node configuration specification.

        The specification may be provided as an in-memory dictionary, as a path
        to a HOCON configuration file, or as a sequence of such elements. When a
        sequence is given, each element is resolved independently and merged from
        left to right, with later elements overriding earlier ones.

        The node uses :func:`resolve_common` to resolve the shared SDXL configuration.
        Expected keys include:

        **Model / runtime**
        - ``model.path`` : str (required)
            Local path or identifier for the SDXL base model to load.
        - ``model.device`` : str, optional
            Device to run on (default: ``"cuda"``).
        - ``model.dtype`` : str, optional
            DType name resolved by ``resolve_dtype`` (default: ``"bf16"``).

        **VAE**
        - ``vae`` : str or dict, optional
            Either a VAE id string, or a dict with ``vae.id``.

        **Generation parameters** (under ``params``)
        - ``params.steps`` : int, optional
            Number of denoising steps (default: 30).
        - ``params.cfg`` or ``params.guidance_scale`` : float, optional
            Classifier-free guidance scale (default: 6.0). ``cfg`` takes precedence.
        - ``params.strength`` : float, optional
            Denoising strength controlling how strongly the masked region is
            re-synthesized (default: 0.7).
        - ``params.width`` : int, optional
            Output width (default: 1024).
        - ``params.height`` : int, optional
            Output height (default: 1024).
        - ``params.long_side`` : int, optional
            If provided, overrides ``params.width`` and ``params.height`` and
            resolves the generation size proportionally from the input image so
            that its longest side matches this value.

        **Batch and randomness**
        - ``batch`` : int, optional
            Number of images to generate.

            - Must be greater than 0.
            - If ``seed`` is a list, defaults to ``len(seed)``.
            - If ``seed`` is a single integer, must be ``1``.
            - If ``seed`` is ``"rand"`` or ``"random"``, controls how many
            independent random seeds are generated.

        - ``seed`` : int or list[int] or str, optional
            Seed specification controlling stochastic sampling.

            Supported forms:

            - ``int``
            Single deterministic seed. Implies ``batch = 1``.

            - ``list[int]``
            Explicit list of seeds. If ``batch`` is not provided, it is inferred
            as ``len(seed)``. If ``batch`` is provided, it must match the list
            length.

            - ``"rand"`` or ``"random"``
            Generate one or more random seeds. If ``batch`` is not provided,
            defaults to ``1``. Otherwise, ``batch`` independent seeds are generated.

    Attributes
    ----------
    op : str
        Operator identifier derived from the concrete node class name (e.g.
        ``"inpaint"``).
    controlnet : ControlNetRegistry
        Registry used to declare ControlNet conditioning inputs (via sinks),
        provided by ``ControlNetMixin``.
    ip_adapter : IpAdapterRegistry
        Registry used to declare IP-Adapter reference inputs (via sinks),
        provided by ``ControlNetMixin``.
    face_id : FaceIdRegistry
        Registry used to declare FaceID reference inputs (via sinks),
        provided by ``ControlNetMixin``.
    prompt : PromptRegistry
        Registry used to attach an upstream prompt bundle, provided by
        ``PromptMixin``.

    Inputs
    ------
    default : dict
        Required. Upstream output dictionary containing the init image path. The
        node expects either ``"image"`` or ``"path"`` to point to the image file.

    mask : dict
        Required. Upstream output dictionary containing the mask image path. The
        node expects either ``"image"`` or ``"path"`` to point to the mask file.
        Convention: white areas are repainted; black areas are preserved.

    prompt:default : dict, optional
        Optional upstream prompt bundle. If present, it overrides prompt fields from
        ``spec``. Expected keys include ``prompt``, ``prompt_2``,
        ``negative_prompt``, and ``negative_prompt_2``.

    Additional typed inputs may be attached via ControlNet/IP-Adapter/FaceID sinks
    declared on this node (see Notes).

    Outputs
    -------
    dict
        Primary output dictionary.

        The node may produce either a single image or a batch of images,
        depending on the resolved ``batch`` size.

        **Single image output (batch = 1)**

        - ``ok`` : bool
        - ``node`` : str (e.g. ``"inpaint"``)
        - ``id`` : str
        - ``image`` : str
        Path to the generated image.
        - ``seed`` : int
        Seed used to generate the image.
        - ``metadata`` : str
        Path to the JSON sidecar.

        **Batch output (batch > 1)**

        - ``ok`` : bool
        - ``node`` : str
        - ``id`` : str
        - ``images`` : list[str]
        Paths to generated images.
        - ``seeds`` : list[int]
        Seeds aligned with ``images`` (same order).
        - ``batch`` : int
        Number of generated images.
        - ``metadata`` : str
        Path to the JSON sidecar (shared across the batch).

        The metadata sidecar includes resolved parameters, timing information,
        model information, and (when running on CUDA) memory statistics.

        For batch outputs, a single sidecar file is written per node execution.

    Notes
    -----
    - Prompt resolution is performed by :class:`PromptBundle`: if a prompt bundle
      is wired into ``prompt:default``, it takes precedence over the local
    ``spec``; otherwise the local ``spec`` is used.
    - The init image and mask are shared across the generated batch. When
    ``batch > 1``, the node produces multiple stochastic samples from the same
      inpainting setup.
    - The init image is resized to the resolved ``width`` and ``height`` before
      being passed to the pipeline. The mask is expected to be aligned with the
      init image and is resized accordingly.
    - ControlNet inputs are collected from DAG wiring through the ControlNet
      registry and resolved into a runtime bundle before pipeline construction.
    - For ``StableDiffusionXLControlNetInpaintPipeline``, ControlNet conditioning
      images are passed through the pipeline kwargs built by
      :func:`build_pipe_kwargs`.
    - IP-Adapter and FaceID inputs are collected from DAG wiring through their
      respective registries and resolved into runtime bundles before pipeline
      invocation.
    - IP-Adapter conditioning uses one or more reference images passed through
      ``ip_adapter_image``; FaceID uses precomputed embeddings passed through
      ``ip_adapter_image_embeds``. IP-Adapter and FaceID are mutually exclusive.
    - Outputs are written as one or more image files plus a single JSON sidecar
      for the node execution. In batch mode, the sidecar is shared across all
      generated images.
      The effective generation size is resolved either from ``params.width`` /
      ``params.height`` or, when ``params.long_side`` is provided, from the
      input image aspect ratio.
    """

    spec: SpecInput = field(default_factory=dict)

    def __post_init__(self) -> None:
        super().__post_init__()

    @property
    def uses_cuda(self) -> bool:
        spec = resolve_spec(self.spec)
        return is_cuda_device(spec.get('model', {}).get('device', 'cuda'))

    def mask(self):
        """
        Declare the mask input sink for the inpainting operation.

        This method exposes an :class:`AttachmentSink` that allows an upstream node
        to provide the inpainting mask. The mask defines which regions of the init
        image are subject to modification during generation.

        The attached upstream output must contain an image path under either the
        ``"image"`` or ``"path"`` key. The mask image is interpreted according to
        Stable Diffusion XL inpainting conventions: white regions are repainted,
        while black regions are preserved.

        Returns
        -------
        AttachmentSink
            A sink bound to this node with ``input_id="mask"``, used to wire an
            upstream mask-producing node into the inpainting pipeline.

        Notes
        -----
        - The mask is loaded at runtime, converted to single-channel (``"L"``),
        and resized to match the resolved ``(width, height)`` of the generation.
        - Mask polarity (white = repaint, black = keep) follows Diffusers SDXL
        inpainting conventions; users are responsible for providing masks with
        the correct polarity.
        - This sink is required for successful execution of the ``Inpaint`` node.
        """
        return AttachmentSink(
            name=f'inpaint_mask:{self.id}',
            target=self,
            input_id='mask',
        )

    def run(self, output_dir: str | Path, input: Optional[Dict[str, Dict]] = None) -> Dict[str, Any]:
        from diffusers import (StableDiffusionXLControlNetInpaintPipeline,
                               StableDiffusionXLInpaintPipeline)

        setup_env()
        ctx = resolve_common(self.spec)

        input = input or {}

        # 1) init image (default)
        init_up = input.get('default')
        if init_up is None:
            raise ValueError(
                'Inpaint requires an init image wired into the default input (src >> inpaint).'
            )

        init_path = init_up.get('image') or init_up.get('path')
        if not init_path:
            raise ValueError(
                "Init image upstream output must contain 'image' or 'path'.")

        width, height = _resolve_inpaint_size(
            ctx=ctx,
            init_path=init_path,
        )

        init_image = _load_resize_image(
            init_path,
            mode='RGB',
            width=width,
            height=height,
            resample=Image.Resampling.LANCZOS,
        )

        # 2) mask image (mask)
        mask_up = input.get('mask')
        if mask_up is None:
            raise ValueError(
                'Inpaint requires a mask image wired into input_id="mask" (src >> inpaint.mask). '
            )

        mask_path = mask_up.get('image') or mask_up.get('path')
        if not mask_path:
            raise ValueError(
                "Mask upstream output must contain 'image' or 'path'.")

        # keep mask as single channel for sanity; resize to match
        mask_image = _load_resize_image(
            mask_path,
            mode='L',
            width=width,
            height=height,
            resample=Image.Resampling.NEAREST,
        )

        # --- resolve conditioning bundles from DAG wiring ---
        cn_bundle, ip_bundle, face_bundle = self.build_control_bundles(
            input=input,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        base = get_sdxl_base_pipe(
            model_ref=ctx.model.model_ref,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
            vae_id=ctx.model.vae_id,
        )

        if ip_bundle.has_ip_adapter and face_bundle.has_face_id:
            raise ValueError(
                'IP_Adapter and IP-Adapter-FaceID are mutually exclusive (chose one).'
            )

        # pipeline load (two-path: standard vs controlnet)
        if cn_bundle.has_controlnet:
            pipe = StableDiffusionXLControlNetInpaintPipeline(
                **base.components,
                controlnet=cn_bundle.controlnet_arg
            )
        else:
            pipe = StableDiffusionXLInpaintPipeline(
                **base.components
            )

        prompt_bundle = PromptBundle(spec=ctx.spec, input=input)

        cuda_prerun(ctx.model.device)
        t0 = time.perf_counter()

        apply_ip_adapter(
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            pipe=pipe,
            batch=ctx.batch,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
        )

        pipe_kwargs = build_pipe_kwargs(
            cn_bundle=cn_bundle,
            ip_bundle=ip_bundle,
            face_bundle=face_bundle,
            height=height,
            width=width,
            device=ctx.model.device,
            dtype=ctx.model.dtype,
            init_image_already_passed=True,
        )

        # sanity-check ip-adapter masks length if present
        if 'cross_attention_kwargs' in pipe_kwargs:
            expected = len(ip_bundle.weight_names_arg) + \
                len(face_bundle.weight_names_arg)
            masks = pipe_kwargs['cross_attention_kwargs']['ip_adapter_masks']

            if len(masks) != expected:
                raise ValueError(
                    f'Invalid IP-Adapter mask count: expected {expected}, '
                    f'got {len(masks)}.'
                )

        result = pipe(
            prompt=prompt_bundle.prompt,
            prompt_2=prompt_bundle.prompt_2,
            negative_prompt=prompt_bundle.negative_prompt,
            negative_prompt_2=prompt_bundle.negative_prompt_2,
            image=init_image,
            mask_image=mask_image,
            strength=ctx.strength,
            num_inference_steps=ctx.steps,
            guidance_scale=ctx.cfg,
            generator=ctx.rng.generators,
            width=width,
            height=height,
            num_images_per_prompt=ctx.batch,
            **pipe_kwargs
        )

        cuda_sync(ctx.model.device)
        dt_s = time.perf_counter() - t0

        images = result.images
        if len(images) != len(ctx.rng.seeds):
            raise ValueError(
                f'Expected {len(ctx.rng.seeds)} output images, got {len(images)}'
            )

        img_paths = [save_image(
            output_dir,
            node_id=self.id,
            seed=seed,
            img=img,
        ) for img, seed in zip(images, ctx.rng.seeds)]

        mem = cuda_mem_stats(ctx.model.device)

        out = finalize_image_output(
            node_kind=str(self.op),
            node_id=self.id,
            img_path=img_paths,
            seed=ctx.rng.seeds,
            params={
                'steps': ctx.steps,
                'guidance_scale': ctx.cfg,
                'strength': ctx.strength,
                'width': width,
                'height': height,
                **({'long_side': ctx.long_side} if ctx.long_side is not None else {}),
            },
            dt_s=dt_s,
            cuda_mem=mem,
            controlnet_specs=self.controlnet.specs,
            ip_adapter_specs=self.ip_adapter.specs,
            face_id_specs=self.face_id.specs,
            model_info={
                'source': ctx.model.model_ref.source,
                'ref': ctx.model.model_ref.ref,
                **({'vae_id': ctx.model.vae_id} if ctx.model.vae_id is not None else {}),
                'dtype': str(ctx.model.dtype).replace('torch.', ''),
                'device': ctx.model.device,
            }
        )

        return out
