from dataclasses import dataclass
from typing import Any, Dict

from morphalo.dag.control_nodes import MaterializedPassthrough
from morphalo.nodes.image_output import ImageOutputMixin
from morphalo.nodes.prompt_output import PromptOutputMixin

Output = Dict[str, Any]


@dataclass
class Tap(ImageOutputMixin, PromptOutputMixin, MaterializedPassthrough):
    """
    Minimal pass-through checkpoint node.

    Tap forwards the single upstream output under input_id 'default',
    rewrites node metadata to itself, and materializes the result to JSON.

    Parameters
    ----------
    name : str, optional
        Unique node identifier within the DAG. If not provided, an identifier is
        automatically generated by the enclosing DAG.
    strict : bool, default=True
        If True, the node fails when no upstream payload is available.
        If False, missing input produces a minimal materialized payload.
    """

    strict: bool = True

    def _missing_input(self, output_dir: str, *, upstream_none: bool) -> Output:
        if self.strict:
            if upstream_none:
                raise RuntimeError(
                    f'Tap {self.id!r} received None upstream output.'
                )
            raise RuntimeError(f'Tap {self.id!r} received no input.')

        return self._forward_output(output_dir, {})
