# preprocessing
preserve_bg = false
thickness = 2
point_radius = 2
max_frames = -1
long_side = 384

# Extractor params
conf_min_pose = 0.3
conf_min_hand = 0.1
conf_min_face = 0.1
max_poses = 4
max_faces = 4
max_hands = 8


models {
    pose_task = "~/models/mediapipe/pose_landmarker_heavy.task",
    hand_task = "~/models/mediapipe/hand_landmarker.task",
    face_task = "~/models/mediapipe/face_landmarker.task",
}
