model {
    id = "Intel/dpt-hybrid-midas"
    device = "cuda"
    autocast = true
}

detect_resolution = 512
image_resolution = 384

normalize = "running"
invert_depth = false
clip_p_low = 10.0
clip_p_high = 70.0
max_frames = -1
