lang: ita_Latn

prompt {
  content = [
    """
    Principessa guerriera elfica. Orechie a punta.
    Volto ovale con mento prominente. capelli neri lunghi, occhi azzurri. 
    Armatura di piastre, argento.
    Scollatura profonda nel pettorale.
    Cammina insieme a una ragazza maga, vestita di grigio, capelli corti color argento e occhi viola.
    Giardino con statue di marmo, e fontane monumentali. Sentieri di selciato e siepi fiorite.
    """
  ]
  style = [
    "Pelle naturale, imperfetta. Pallida, eburnea."
    "fotoritratto; stile Lord of The Rings, Studio Ghibli, tratti facciali Final Fantasy."
    "Orecchie a punta."
    "Giardino rinascimentale, lucido marmo e siepi di fiori"
    "Atmosfera crepuscolare, buio. Luci e ombre consistenti"
    "Armatura lamellare, metallo lucido intyarsi in oro"
    "Vesti da mago in tessuto grizio e naturale, grezzo"
  ]
}
