lang: ita_Latn

prompt {
  content = [
    """
    Principessa guerriera elfo. Orechie a punta. Stile Lord Of The Rings.
    Volto ovale con mento prominente. Capelli neri lunghi ben acconciati, occhi azzurri.
    Indossa una corazza di piastre minimale; copre il petto lasciando scollatura profonda.
    Braccia e gambe nude.
    """
  ]
  style = [
    "Metallo dell'armatura lucido, robusto, con intarsi e decotrazioni d'oro e d'argento; protezione minimale, braccia e gambe nude."
    "Pelle pulita e naturale. Pallida"
    "fotoritratto; stile Lord of The Rings, Studio Ghibli, tratti facciali Final Fantasy."
    "Orecchie a punta."
  ]
}
