include "../common.conf"

negative_prompt {
  content = [
    ${defaults.negative_prompt},
    "modern clothing, runway, fashion show, jeans, sneakers, logos",
    "extra fingers, extra limbs, deformed face",
    "Long dress, veils, floating tissue"
  ]
  style = [
    "low quality, inconsistent lighting"
  ]
}

params {
  steps = 50
  cfg = 7.0
}

seed = random
