lang: ita_Latn

prompt {
  content = [
    """
    Principessa guerriera elfica. Orechie a punta.
    Volto ovale con mento prominente. capelli neri lunghi, occhi azzurri. 
    Armatura di piastre, argento. Impugna spada.
    Scollatura profonda nel pettorale.
    È in piedi, braccia e gambe non sono coperte dall'armatura.
    Sguardo amichevole ma determinato.
    Giardino con statue di marmo, e fontane monumentali. Sentieri di selciato e siepi fiorite.
    """
  ]
  style = [
    "Pelle naturale, imperfetta. Pallida, eburnea."
    "fotoritratto; stile Lord of The Rings, Studio Ghibli, tratti facciali Final Fantasy."
    "Orecchie a punta."
    "Giardino rinascimentale, lucido marmo e siepi di fiori"
    "Atmosfera crepuscolare, buio. Luci e ombre consistenti"
    "Armatura lamellare, metallo lucido intyarsi in oro"
  ]
}
