lang: ita_Latn
translate_max_length: 512

prompt = [
    """
    Giovane principessa guerriera elfica sulla ventina.
    Sguardo dolce ma determinato.
    Passeggia in un giardino rinascimentale con fontane monumentali e statue di marmo raffiguranti ninfe.
    Ha orecchie a punta e lineamenti aristocratici stile Lord of The Rings.
    Il suo viso è ovale con un mento pronunciato, pelle chiara e liscia e occhi azzurri profondi.
    Ha lunghi capelli neri finemente acconciati con trecce laterali.
    """,
    """
    Indossa un'armatura di piastre, minimale con scollatura profonda,
    realizzata in metallo trasparente e intricati intarsi in oro e argento.
    Le sue braccia e gambe sono nude. L'armatura è funzionale ma al tempo stesso elegante, di metallo
    trasparente e lucido come uno specchio""",
    "Fiori e statue si specchiano sull'armatura.",
    "Illuminazione debole, pelle e materiali realistici.",
]

negative_prompt = [
    "bassa qualità",
    "sfocato",
    "rumore",
    "artefatti di compressione",
    "pelle di plastica",
    "pelle da bambola",
    "effetto cera",
    "occhi storti",
    "occhi asimmetrici",
    "mani deformi",
    "dita extra",
    "proporzioni sbagliate",
    "anatomia errata",
    "stile cartoon",
    "stile anime",
    "illustrazione",
]
