lang: ita_Latn

prompt {
  content = [
    "Ragazza maga. Stile Gandalf. Capelli color argento, splendenti, finemente acconciati con trecce laterali"
    "Volto affilato con mento prominente"
    "Occhi viola, grandi e profondi"
    "Carnagione pallida"
  ]
  style = [
    "Pelle pulita e naturale. Pallida"
    "fotoritratto; stile Lord of The Rings, Studio Ghibli, tratti facciali Final Fantasy"
  ]
}
