lang: ita_Latn

prompt {
  content = [
    "Giovane ragazza sulla ventina. Caucasica"
    "Capelli corti color argento, finemente acconciati con trecce laterali, raccolti a cipolla."
    "Volto affilato con mento prominente."
    "Occhi viola, grandi e profondi"
    "Carnagione pallida."
    "Fisico minuto."
    "Indossa una tunica di lino grigia  a maniche lunghe, con cappuccio calato sulla schiena."
  ]
  style = [
    "fotoritratto stile Lord of The Rings, Studio Ghibli, tratti facciali Final Fantasy."
    "Pelle pulita e naturale. Pallida."
    "Capelli splendenti, trecce laterali, raccolti a cipolla."
    "Tunica a maniche lunghe di materiale naturale, iuta, grigia."
  ]
}
